/*
 * Copyright 2012  Samsung Electronics Co., Ltd
 *
 * Licensed under the Flora License, Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.tizenopensource.org/license
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#ifndef __VC_CORE_ERROR_H_
#define __VC_CORE_ERROR_H_

/**
 * Voicecall Engine Error Codes
 */

typedef enum __voicecall_api_error_t {
	ERROR_VOICECALL_NONE,	/*0 */
	ERROR_VOICECALL_INVALID_CALL_TYPE,
	ERROR_VOICECALL_INVALID_TELEPHONE_NUMBER,
	ERROR_VOICECALL_MEMALLOC_FAILURE,
	ERROR_VOICECALL_DBUS_FAILURE,
	ERROR_VOICECALL_INVALID_MO_REF_HANDLE,
	ERROR_VOICECALL_INVALID_CALL_HANDLE,
	ERROR_VOICECALL_CALL_INFO_NOT_AVAILABLE,
	ERROR_VOICECALL_CALL_NOT_ALLOWED,
	ERROR_VOICECALL_NOT_SUPPORTED,
	ERROR_VOICECALL_INVALID_ACTION_TYPE,	/*10 */
	ERROR_VOICECALL_TAPI_ERROR,
	ERROR_VOICECALL_FDN_ONLY,
	ERROR_VOICECALL_EMERGENCY_CALLS_ONLY,
	ERROR_VOICECALL_OUTGOING_ABORTED,
	ERROR_VOICECALL_ENGINE_STATE_NOT_NONE,
	ERROR_VOICECALL_EMPTY_SPEED_DIAL,
	ERROR_VOICECALL_CONTACT_READ_FAILED,
	ERROR_VOICECALL_MO_CALL_NOT_AVAILABLE,
	ERROR_VOICECALL_NO_NW_SERVICE,
	ERROR_VOICECALL_TAPI_CAUSE_CALL_FAILED,	/*20 */
	ERROR_VOICECALL_NO_INCOMING_CALL_EXIST,
	ERROR_VOICECALL_ENGINE_STATE_NONE,
	ERROR_VOICECALL_BOTH_ACTIVE_HELD_CALLS_EXIST,
	ERROR_VOICECALL_OFFLINE_MODE,
	ERROR_VOICECALL_CALL_IMPOSSIBLE_NOSIM_NOEMERGNUM,
	ERROR_VOICECALL_PHONE_NOT_INITIALIZED,
	ERROR_VOICECALL_HOLD_REJECTED,
	ERROR_VOICECALL_ACTIVATE_REJECTED,
	ERROR_VOICECALL_SWAP_REJECTED,
	ERROR_VOICECALL_HOLD_FAILED,	/*30 */
	ERROR_VOICECALL_RETREIVE_FAILED,
	ERROR_VOICECALL_SETUP_CONF_FAILED,
	ERROR_VOICECALL_SPLIT_CONF_FAILED,
	ERROR_VOICECALL_SWAP_FAILED,
	ERROR_VOICECALL_TRANSFER_FAILED,
	ERROR_VOICECALL_INCOMPLETE,
	ERROR_VOICECALL_UNAVAILABLE,
	ERROR_VOICECALL_HOLD_NOT_SUPPORTED,
	ERROR_VOICECALL_RETREIVE_NOT_SUPPORTED,
	ERROR_VOICECALL_SETUP_CONF_NOT_SUPPORTED,	/*40 */
	ERROR_VOICECALL_SPLIT_CONF_NOT_SUPPORTED,
	ERROR_VOICECALL_SWAP_NOT_SUPPORTED,
	ERROR_VOICECALL_TRANSFER_NOT_SUPPORTED,
	ERROR_VOICECALL_DTMF_FAILED,
	ERROR_VOICECALL_ANSWER_FAILED,
	ERROR_VOICECALL_PREVIOUS_REQUEST_IN_PROGRESS,
	ERROR_VOICECALL_INSUFFICIENT_BUFFER,
	ERROR_VOICECALL_INVALID_ARGUMENTS,
	ERROR_VOICECALL_NOTI_FAILED,
	ERROR_VOICECALL_OPERATION_NOT_ALLOWED,	/*50 */
	ERROR_VOICECALL_REQUEST_FAILED,
	ERROR__vc_core_engine_private_call_NOT_POSSIBLE,
	ERROR_VOICECALL_TRANSFER_CALL_NOT_POSSIBLE,
	ERROR_VOICECALL_CONF_NOT_POSSIBLE,
	ERROR_VOICECALL_INVALID_CALLID,
	ERROR_VOICECALL_CALL_IS_IN_PROGRESS,
	ERROR__vc_core_engine_private_call_FAILED,
	ERROR_VOICECALL_INVALID_DTMF_CHAR,	/*58 */
	ERROR_VOICECALL_MAX
} voicecall_error_t;

#endif				/*__VC_CORE_ERROR_H_*/
