/*
 * Copyright 2012  Samsung Electronics Co., Ltd
 *
 * Licensed under the Flora License, Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.tizenopensource.org/license
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#ifndef _VCUI_VIEW_LAYOUT_HD_H_
#define _VCUI_VIEW_LAYOUT_HD_H_

#define COLOR_DEFAULT 0 0 0 255
#define COLOR_BG_ALPHA 0 0 0 0
#define COLOR_BG_FOR_HELD_CALL_DIM 0 0 0 150

#define FONT_SLP_Bold "SLP:style=Bold"
#define FONT_SLP_Medium "SLP:style=Medium"
#define FONT_SLP_Roman "SLP:style=Roman"
#define FONT_SLP_Light "SLP:style=Light"
#define FONT_SLP_Regular "SLP:style=Regular"

#define TEXT_CLASS_SLP_BOLD "slp_bold"
#define TEXT_CLASS_SLP_MEDIUM "slp_medium"
#define TEXT_CLASS_SLP_ROMAN "slp_roman"
#define TEXT_CLASS_SLP_LIGHT "slp_light"
#define TEXT_CLASS_SLP_REGULAR "slp_regular"

/*#define BTN_EDGE_W 9*/

/*
 * NBEAT-HD GUI Widget Dimensions
 * In Portrait mode
 */
#define MAIN_SCREEN_W 720
#define MAIN_SCREEN_H 1280

#define INDICATOR_HEIGHT 50
#define NAVIFRAME_TITLE_HEIGHT 100

#define MAIN_NAVIFRAME_W MAIN_SCREEN_W
#define MAIN_NAVIFRAME_H (MAIN_SCREEN_H-INDICATOR_HEIGHT-NAVIFRAME_TITLE_HEIGHT)
#define NAVIFRAME_T_PAD 50

#define QP_WIN_W MAIN_SCREEN_W
#define QP_WIN_H 170

#define CALLER_INFO_L_PAD 0
#define CALLER_INFO_WIDTH MAIN_SCREEN_W
#define CALLER_INFO_T_PAD 50
#define CALLER_INFO_HEIGHT 162

#define CALLER_INFO_MAIN_WIDTH 680
#define CALLER_INFO_MAIN_GAP 16

#define CALLER_INFO_TOP_PAD_HEIGHT 10

#define CALLER_INFO_NAME_L_PAD 24
#define CALLER_INFO_NAME_WIDTH 595
#define CALLER_INFO_NAME_T_PAD 24
#define CALLER_INFO_NAME_HEIGHT 69

#define CALLER_INFO_VERT_SEP_L_PAD 600
#define CALLER_INFO_VERT_SEP_WIDTH 2
#define CALLER_INFO_VERT_SEP_T_PAD 24
#define CALLER_INFO_VERT_SEP_HEIGHT 70

#define CALLER_INFO_ICON_L_PAD 626
#define CALLER_INFO_ICON_WIDTH 70
#define CALLER_INFO_ICON_T_PAD CALLER_INFO_NAME_T_PAD
#define CALLER_INFO_ICON_HEIGHT 70

#define CALLER_INFO_NUMBER_L_PAD CALLER_INFO_NAME_L_PAD
#define CALLER_INFO_NUMBER_WIDTH (CALLER_INFO_MAIN_WIDTH-CALLER_INFO_MAIN_GAP-250)
#define CALLER_INFO_NUMBER_T_PAD (CALLER_INFO_NAME_T_PAD+CALLER_INFO_NAME_HEIGHT+CALLER_INFO_MAIN_GAP)
#define CALLER_INFO_NUMBER_HEIGHT 28

#define CALLER_INFO_TIME_L_PAD (CALLER_INFO_NAME_L_PAD+CALLER_INFO_NUMBER_WIDTH+CALLER_INFO_MAIN_GAP)
#define CALLER_INFO_TIME_WIDTH 250
#define CALLER_INFO_TIME_T_PAD CALLER_INFO_NUMBER_T_PAD
#define CALLER_INFO_TIME_HEIGHT CALLER_INFO_NUMBER_HEIGHT

#define CALLER_INFO_STR_MAX_WIDTH 500
#define CALLER_INFO_STR_MIN_WIDTH 180

#define DIALING_STATUS_L_PAD 0
#define DIALING_STATUS_WIDTH MAIN_SCREEN_W
#define DIALING_STATUS_T_PAD 868
#define	DIALING_STATUS_HEIGHT 52

#define CALL_NAME_L_PAD 20
#define CALL_NAME_WIDTH 680
#define CALL_NAME_T_PAD 83
#define	CALL_NAME_HEIGHT 80

#define CALL_NUMBER_T_GAP 6

#define CALL_NUMBER_L_PAD CALL_NAME_L_PAD
#define CALL_NUMBER_WIDTH CALL_NAME_WIDTH
#define CALL_NUMBER_T_PAD (CALL_NAME_T_PAD+CALL_NAME_HEIGHT+CALL_NUMBER_T_GAP)
#define	CALL_NUMBER_HEIGHT 52

#define CALLER_ID_L_PAD 208
#define CALLER_ID_WIDTH 304
#define CALLER_ID_T_PAD 268
#define	CALLER_ID_HEIGHT 304

#define ENDCALL_CALLER_ID_L_PAD 150
#define ENDCALL_CALLER_ID_WIDTH 420
#define ENDCALL_CALLER_ID_T_PAD 292
#define ENDCALL_CALLER_ID_HEIGHT 420

#define ENDCALL_BTN_BG_L_PAD 0
#define ENDCALL_BTN_BG_WIDTH 720
#define ENDCALL_BTN_BG_T_PAD 1058
#define ENDCALL_BTN_BG_HEIGHT 222

#define NOIMAGE_L_PAD 0
#define NOIMAGE_WIDTH 720
#define NOIMAGE_T_PAD 212
#define NOIMAGE_HEIGHT 500

#define BACKGROUND_CID_L_PAD 0
#define BACKGROUND_CID_WIDTH MAIN_SCREEN_W
#define BACKGROUND_CID_T_PAD 0
#define BACKGROUND_CID_HEIGHT MAIN_SCREEN_H

#define	MT_CALLING_NAME_BG_WIDTH MAIN_SCREEN_W
#define	MT_CALLING_NAME_BG_HEIGHT 590

#define	MTLOCK_ACCEPT_OUTER_CIRCLE_BG_L_PAD (-152)
#define	MTLOCK_ACCEPT_OUTER_CIRCLE_BG_WIDTH 526
#define	MTLOCK_ACCEPT_OUTER_CIRCLE_BG_T_PAD 775
#define	MTLOCK_ACCEPT_OUTER_CIRCLE_BG_HEIGHT 526

#define	MTLOCK_ACCEPT_INNER_CIRCLE_BG_L_PAD 14
#define	MTLOCK_ACCEPT_INNER_CIRCLE_BG_WIDTH 194
#define	MTLOCK_ACCEPT_INNER_CIRCLE_BG_T_PAD 941
#define	MTLOCK_ACCEPT_INNER_CIRCLE_BG_HEIGHT 194

#define	MTLOCK_ACCEPT_ICON_L_PAD 60
#define	MTLOCK_ACCEPT_ICON_WIDTH 102
#define	MTLOCK_ACCEPT_ICON_T_PAD 987
#define	MTLOCK_ACCEPT_ICON_HEIGHT 102

#define	MTLOCK_ACCEPT_ARROW1_L_PAD 228
#define	MTLOCK_ACCEPT_ARROW1_WIDTH 20
#define	MTLOCK_ACCEPT_ARROW1_T_PAD 1022
#define	MTLOCK_ACCEPT_ARROW1_HEIGHT 32

#define	MTLOCK_ACCEPT_ARROW2_L_PAD 276
#define	MTLOCK_ACCEPT_ARROW2_WIDTH MTLOCK_ACCEPT_ARROW1_WIDTH
#define	MTLOCK_ACCEPT_ARROW2_T_PAD MTLOCK_ACCEPT_ARROW1_T_PAD
#define	MTLOCK_ACCEPT_ARROW2_HEIGHT MTLOCK_ACCEPT_ARROW1_HEIGHT

#define	MTLOCK_ACCEPT_ARROW3_L_PAD 324
#define	MTLOCK_ACCEPT_ARROW3_WIDTH MTLOCK_ACCEPT_ARROW1_WIDTH
#define	MTLOCK_ACCEPT_ARROW3_T_PAD MTLOCK_ACCEPT_ARROW1_T_PAD
#define	MTLOCK_ACCEPT_ARROW3_HEIGHT MTLOCK_ACCEPT_ARROW1_HEIGHT

#define	MTLOCK_REJECT_OUTER_CIRCLE_BG_L_PAD 346
#define	MTLOCK_REJECT_OUTER_CIRCLE_BG_WIDTH MTLOCK_ACCEPT_OUTER_CIRCLE_BG_WIDTH
#define	MTLOCK_REJECT_OUTER_CIRCLE_BG_T_PAD MTLOCK_ACCEPT_OUTER_CIRCLE_BG_T_PAD
#define	MTLOCK_REJECT_OUTER_CIRCLE_BG_HEIGHT MTLOCK_ACCEPT_OUTER_CIRCLE_BG_HEIGHT

#define	MTLOCK_REJECT_INNER_CIRCLE_BG_L_PAD 512
#define	MTLOCK_REJECT_INNER_CIRCLE_BG_WIDTH MTLOCK_ACCEPT_INNER_CIRCLE_BG_WIDTH
#define	MTLOCK_REJECT_INNER_CIRCLE_BG_T_PAD MTLOCK_ACCEPT_INNER_CIRCLE_BG_T_PAD
#define	MTLOCK_REJECT_INNER_CIRCLE_BG_HEIGHT MTLOCK_ACCEPT_INNER_CIRCLE_BG_HEIGHT

#define	MTLOCK_REJECT_ICON_R_PAD 60
#define	MTLOCK_REJECT_ICON_WIDTH MTLOCK_ACCEPT_ICON_WIDTH
#define	MTLOCK_REJECT_ICON_L_PAD (MAIN_SCREEN_W-MTLOCK_REJECT_ICON_R_PAD-MTLOCK_REJECT_ICON_WIDTH)
#define	MTLOCK_REJECT_ICON_T_PAD MTLOCK_ACCEPT_ICON_T_PAD
#define	MTLOCK_REJECT_ICON_HEIGHT MTLOCK_ACCEPT_ICON_HEIGHT

#define	MTLOCK_REJECT_ARROW1_L_PAD 376
#define	MTLOCK_REJECT_ARROW1_WIDTH 20
#define	MTLOCK_REJECT_ARROW1_T_PAD MTLOCK_ACCEPT_ARROW1_T_PAD
#define	MTLOCK_REJECT_ARROW1_HEIGHT MTLOCK_ACCEPT_ARROW1_HEIGHT

#define	MTLOCK_REJECT_ARROW2_L_PAD 424
#define	MTLOCK_REJECT_ARROW2_WIDTH MTLOCK_REJECT_ARROW1_WIDTH
#define	MTLOCK_REJECT_ARROW2_T_PAD MTLOCK_REJECT_ARROW1_T_PAD
#define	MTLOCK_REJECT_ARROW2_HEIGHT MTLOCK_REJECT_ARROW1_HEIGHT

#define	MTLOCK_REJECT_ARROW3_L_PAD 472
#define	MTLOCK_REJECT_ARROW3_WIDTH MTLOCK_REJECT_ARROW1_WIDTH
#define	MTLOCK_REJECT_ARROW3_T_PAD MTLOCK_REJECT_ARROW1_T_PAD
#define	MTLOCK_REJECT_ARROW3_HEIGHT MTLOCK_REJECT_ARROW1_HEIGHT

#define MTLOCK_REJECT_MSG_BG_L_PAD 0
#define MTLOCK_REJECT_MSG_BG_WIDTH MAIN_SCREEN_W
#define MTLOCK_REJECT_MSG_BG_HEIGHT 92
#define MTLOCK_REJECT_MSG_BG_T_PAD (MAIN_SCREEN_H-MTLOCK_REJECT_MSG_BG_HEIGHT)

#define MTLOCK_REJECT_MSG_ARW_L_PAD 351
#define MTLOCK_REJECT_MSG_ARW_WIDTH 18
#define MTLOCK_REJECT_MSG_ARW_T_PAD (MTLOCK_REJECT_MSG_BG_T_PAD+12)
#define MTLOCK_REJECT_MSG_ARW_HEIGHT 12

#define MTLOCK_REJECT_MSG_TEXT_L_PAD 0
#define MTLOCK_REJECT_MSG_TEXT_WIDTH MAIN_SCREEN_W
#define MTLOCK_REJECT_MSG_TEXT_T_PAD (MTLOCK_REJECT_MSG_BG_T_PAD+24)
#define MTLOCK_REJECT_MSG_TEXT_HEIGHT 68

#define MTLOCK_REJECT_MSG_ICON_WIDTH 50
#define MTLOCK_REJECT_MSG_ICON_HEIGHT 50

#define MTLOCK_REJECT_MSG_PAD 20

#define MTLOCK_REJECT_MSG_LIST_L_PAD 0
#define MTLOCK_REJECT_MSG_LIST_WIDTH MAIN_SCREEN_W
#define MTLOCK_REJECT_MSG_LIST_T_PAD MAIN_SCREEN_H
#define MTLOCK_REJECT_MSG_ONE_LINE_LIST_HEIGHT 118
#define MTLOCK_REJECT_MSG_TWO_LINE_LIST_HEIGHT 230
#define MTLOCK_REJECT_MSG_THREE_LINE_LIST_HEIGHT 342
#define MTLOCK_REJECT_MSG_FOUR_LINE_LIST_HEIGHT 454
#define MTLOCK_REJECT_MSG_FIVE_LINE_LIST_HEIGHT 566
#define MTLOCK_REJECT_MSG_SIX_LINE_LIST_HEIGHT 678

#define MTLOCK_REJECT_MSG_TOOLBAR_HEIGHT 114

#define SNS_ALERTS_LAYOUT_L_PAD 0
#define SNS_ALERTS_LAYOUT_WIDTH MAIN_SCREEN_W
#define SNS_ALERTS_LAYOUT_T_PAD 586
#define SNS_ALERTS_LAYOUT_SHIFT_T_PAD 696
#define SNS_ALERTS_LAYOUT_HEIGHT 170

#define SNS_ALERTS_LAYOUT_SHIFT_EXPANDED_T_PAD 494
#define SNS_ALERTS_LAYOUT_EXPANDED_T_PAD 362
#define SNS_ALERTS_LAYOUT_EXPANDED_HEIGHT 380

#define BIRTHDAY_ICON_L_PAD 20
#define BIRTHDAY_ICON_WIDTH 55
#define BIRTHDAY_ICON_T_PAD 0 //584
#define BIRTHDAY_ICON_HEIGHT 55

/*#define BIRTHDAY_ICON_SHIFT_L_PAD 20
#define BIRTHDAY_ICON_SHIFT_WIDTH 55
#define BIRTHDAY_ICON_SHIFT_T_PAD 716
#define BIRTHDAY_ICON_SHIFT_HEIGHT 55*/

#define BIRTHDAY_TEXT_L_PAD (BIRTHDAY_ICON_L_PAD+BIRTHDAY_ICON_WIDTH+16)
#define BIRTHDAY_TEXT_WIDTH 609
#define BIRTHDAY_TEXT_T_PAD (BIRTHDAY_ICON_T_PAD+20)
#define BIRTHDAY_TEXT_HEIGHT 42

/*#define BIRTHDAY_TEXT_SHIFT_L_PAD (BIRTHDAY_ICON_SHIFT_L_PAD+BIRTHDAY_ICON_SHIFT_WIDTH+16)
#define BIRTHDAY_TEXT_SHIFT_WIDTH 609
#define BIRTHDAY_TEXT_SHIFT_T_PAD (BIRTHDAY_ICON_SHIFT_T_PAD+20)
#define BIRTHDAY_TEXT_SHIFT_HEIGHT 42*/

#define SNS_STATUS_ICON_L_PAD 20
#define SNS_STATUS_ICON_WIDTH 55
#define SNS_STATUS_ICON_T_PAD (BIRTHDAY_ICON_T_PAD+BIRTHDAY_ICON_HEIGHT+22)
#define SNS_STATUS_ICON_HEIGHT 55

#define SNS_STATUS_TEXT_L_PAD BIRTHDAY_TEXT_L_PAD
#define SNS_STATUS_TEXT_WIDTH BIRTHDAY_TEXT_WIDTH
#define SNS_STATUS_TEXT_T_PAD (BIRTHDAY_TEXT_T_PAD+BIRTHDAY_TEXT_HEIGHT+24)
#define SNS_STATUS_TEXT_HEIGHT (42*2)

#define SNS_STATUS_ARROW_WIDTH 52
#define SNS_STATUS_ARROW_L_PAD (MAIN_SCREEN_W-20-SNS_STATUS_ARROW_WIDTH)
#define SNS_STATUS_ARROW_T_PAD (BIRTHDAY_TEXT_T_PAD+BIRTHDAY_TEXT_HEIGHT+38)
#define SNS_STATUS_ARROW_HEIGHT 52

#define SNS_STATUS_EXPANDED_TEXT_WIDTH (BIRTHDAY_TEXT_WIDTH-SNS_STATUS_ARROW_WIDTH-16)
#define SNS_STATUS_EXPANDED_TEXT_HEIGHT (42*7)

#define	ACCEPT_BTN_L_PAD 40
#define	ACCEPT_BTN_WIDTH 300
#define	ACCEPT_BTN_T_PAD 992
#define	ACCEPT_BTN_HEIGHT 112

#define REJECT_BTN_L_GAP 40

#define	REJECT_BTN_L_PAD (ACCEPT_BTN_L_PAD+ACCEPT_BTN_WIDTH+REJECT_BTN_L_GAP)
#define	REJECT_BTN_WIDTH ACCEPT_BTN_WIDTH
#define	REJECT_BTN_T_PAD ACCEPT_BTN_T_PAD
#define	REJECT_BTN_HEIGHT ACCEPT_BTN_HEIGHT

#define REJECT_W_MSG_BTN_T_GAP 40

#define	REJECT_W_MSG_BTN_L_PAD ACCEPT_BTN_L_PAD
#define	REJECT_W_MSG_BTN_WIDTH 640
#define	REJECT_W_MSG_BTN_T_PAD (ACCEPT_BTN_T_PAD+ACCEPT_BTN_HEIGHT+REJECT_W_MSG_BTN_T_GAP)
#define	REJECT_W_MSG_BTN_HEIGHT 90

#define	INCALL_EXTRA_VOL_BTN_L_PAD 636
#define	INCALL_EXTRA_VOL_BTN_WIDTH 64
#define	INCALL_EXTRA_VOL_BTN_T_PAD 236
#define	INCALL_EXTRA_VOL_BTN_HEIGHT 64

#define	INCALL_HOLD_BTN_L_PAD 475
#define	INCALL_HOLD_BTN_WIDTH 78
#define	INCALL_HOLD_BTN_T_PAD 852
#define	INCALL_HOLD_BTN_HEIGHT 78

#define	INCALL_HOLD_TXT_L_PAD 573
#define	INCALL_HOLD_TXT_WIDTH 147
#define	INCALL_HOLD_TXT_T_PAD 852
#define	INCALL_HOLD_TXT_HEIGHT 78

#define	INCALL_TIMER_L_PAD 40
#define	INCALL_TIMER_WIDTH 640
#define	INCALL_TIMER_T_PAD 687
#define	INCALL_TIMER_HEIGHT 52

#define	INCALL_NOISE_ICN_L_PAD 18
#define	INCALL_NOISE_ICN_WIDTH 58
#define	INCALL_NOISE_ICN_T_PAD 852
#define	INCALL_NOISE_ICN_HEIGHT 58

#define	INCALL_SOUND_EQ_ICN_L_PAD 72
#define	INCALL_SOUND_EQ_ICN_WIDTH 58
#define	INCALL_SOUND_EQ_ICN_T_PAD INCALL_NOISE_ICN_T_PAD
#define	INCALL_SOUND_EQ_ICN_HEIGHT 58

#define INCALL_SHARE_BG_T_PAD 584
#define INCALL_SHARE_BG_HEIGHT 654

#define KEYPAD_ENTRY_TXT_L_PAD 40
#define KEYPAD_ENTRY_TXT_WIDTH 640
#define KEYPAD_ENTRY_TXT_T_PAD 0
#define KEYPAD_ENTRY_TXT_HEIGHT 100

#define KEYPAD_AREA_L_PAD 0
#define	KEYPAD_AREA_WIDTH MAIN_SCREEN_W
#define	KEYPAD_AREA_T_PAD 252
#define	KEYPAD_AREA_HEIGHT 662

#define KEYPAD_BTNS_BG_L_PAD 40
#define KEYPAD_BTNS_BG_WIDTH 640
#define KEYPAD_BTNS_BG_T_PAD 112
#define KEYPAD_BTNS_BG_HEIGHT 550

#define	KEYPAD_EACH_BTN_WIDTH 212
#define	KEYPAD_EACH_BTN_HEIGHT 134

#define	KEYPAD_COL1_BTN_L_PAD 40
#define	KEYPAD_COL2_BTN_L_PAD 254
#define	KEYPAD_COL3_BTN_L_PAD 468

#define	KEYPAD_BTN_TXT_REGION_HEIGHT 112

#define	KEYPAD_ROW1_BTN_T_PAD 116	/*w.r.t button region layout*/
#define	KEYPAD_ROW2_BTN_T_PAD 252
#define	KEYPAD_ROW3_BTN_T_PAD 388
#define	KEYPAD_ROW4_BTN_T_PAD 524

#define KP_LVERT_SEP1_L_PAD 212
#define KP_RVERT_SEP1_L_PAD 426
#define KP_ROW1_VERT_SEP_T_PAD 17
#define KP_ROW2_VERT_SEP_T_PAD 153
#define KP_ROW3_VERT_SEP_T_PAD 289
#define KP_ROW4_VERT_SEP_T_PAD 425

#define KP_HORIZ_SEP_L_PAD 14
#define KP_ROW1_HORIZ_SEP_T_PAD 138
#define KP_ROW2_HORIZ_SEP_T_PAD 274
#define KP_ROW3_HORIZ_SEP_T_PAD 410

#define KEYPAD_VERT_SEP_WIDTH 1
#define KEYPAD_VERT_SEP_HEIGHT 108
#define KEYPAD_HORIZ_SEP_WIDTH 612
#define KEYPAD_HORIZ_SEP_HEIGHT 1

#define RIGHT_ICON_L_PAD 18
#define RIGHT_ICON_WIDTH 94
#define RIGHT_ICON_HEIGHT 36

#define LEFT_TXT_L_PAD 24
#define LEFT_TXT_WIDTH 64
#define RIGHT_TXT_TYPE1_L_PAD 18
#define RIGHT_TXT_TYPE2_L_PAD 18

#define	SPLIT_CID1_L_PAD 0
#define SPLIT_CID1_WIDTH CALLER_INFO_WIDTH
#define SPLIT_CID1_T_PAD INDICATOR_HEIGHT
#define SPLIT_CID1_HEIGHT 445

#define	SPLIT_PAUSE_L_PAD (SPLIT_CID1_L_PAD+8)
#define SPLIT_PAUSE_WIDTH 62
#define SPLIT_PAUSE_HEIGHT 62
#define SPLIT_PAUSE_T_PAD (SPLIT_CID1_T_PAD+SPLIT_CID1_HEIGHT-8-SPLIT_PAUSE_HEIGHT)

#define CALLER_INFO_HOLD_T_PAD (CALLER_INFO_T_PAD+SPLIT_CID1_HEIGHT)

#define	SPLIT_CID2_L_PAD 0
#define SPLIT_CID2_WIDTH CALLER_INFO_WIDTH
#define SPLIT_CID2_T_PAD CALLER_INFO_HOLD_T_PAD
#define SPLIT_CID2_HEIGHT 445

#define	SPLIT_PLAY_L_PAD (SPLIT_CID2_L_PAD+12)
#define SPLIT_PLAY_WIDTH 40
#define SPLIT_PLAY_HEIGHT 40
#define SPLIT_PLAY_T_PAD (SPLIT_CID2_T_PAD+SPLIT_CID2_HEIGHT-8-SPLIT_PLAY_HEIGHT)

#define	SPLIT_NAME1_L_PAD 38
#define SPLIT_NAME1_WIDTH 364
#define SPLIT_NAME1_T_PAD 145
#define SPLIT_NAME1_HEIGHT 58

#define	SPLIT_NAME2_L_PAD (SPLIT_NAME1_L_PAD+SPLIT_NAME1_WIDTH+22)
#define SPLIT_NAME2_WIDTH 258
#define SPLIT_NAME2_T_PAD 217
#define SPLIT_NAME2_HEIGHT 40

#define SPLIT_EXTRA_VOL_T_PAD 650

#define SPLIT_TIMER_TXT_T_PAD 549
#define SPLIT_TIMER_TXT_HEIGHT 46

#define SPLIT_MORE_BTN_WIDTH 40
#define SPLIT_MORE_BTN_L_PAD (SPLIT_CID2_L_PAD+SPLIT_CID2_WIDTH-SPLIT_MORE_BTN_WIDTH)
#define SPLIT_ONHOLD_TXT_W_ICON_WIDTH (SPLIT_CID2_WIDTH-SPLIT_MORE_BTN_WIDTH)
#define SPLIT_ONHOLD_TXT_T_PAD 492
#define SPLIT_ONHOLD_TXT_HEIGHT 40

#define	SPLIT_SWAP_CID1_L_PAD 70
#define SPLIT_SWAP_CID1_WIDTH 208

#define	SPLIT_SWAP_PLAY_L_PAD (SPLIT_SWAP_CID1_L_PAD+12)
#define SPLIT_SWAP_PLAY_WIDTH 40

#define	SPLIT_SWAP_CID2_L_PAD 336
#define SPLIT_SWAP_CID2_WIDTH 304

#define	SPLIT_SWAP_PAUSE_L_PAD (SPLIT_SWAP_CID2_L_PAD+8)
#define SPLIT_SWAP_PAUSE_WIDTH 62

#define	SPLIT_SWAP_NAME1_L_PAD 38
#define SPLIT_SWAP_NAME1_WIDTH 258

#define	SPLIT_SWAP_NAME2_L_PAD (SPLIT_SWAP_NAME1_L_PAD+SPLIT_SWAP_NAME1_WIDTH+22)
#define SPLIT_SWAP_NAME2_WIDTH 364

#define SPLIT_SWAP_MORE_BTN_WIDTH 60
#define SPLIT_SWAP_MORE_BTN_L_PAD (SPLIT_SWAP_CID2_L_PAD+SPLIT_SWAP_CID2_WIDTH-SPLIT_SWAP_MORE_BTN_WIDTH)
#define SPLIT_SWAP_MORE_BTN_T_PAD (SPLIT_TIMER_TXT_T_PAD-7)
#define SPLIT_SWAP_MORE_BTN_HEIGHT 60
#define SPLIT_TIMER_TXT_W_ICON_WIDTH (SPLIT_SWAP_CID2_WIDTH-SPLIT_SWAP_MORE_BTN_WIDTH)

#define	MULTI_LIST_HEIGHT 1008

#define	CONF_LIST_T_PAD 0
#define	CONF_LIST_HEIGHT 565

#define	CONF_HOLD_WIDTH 82
#define	CONF_HOLD_L_PAD (MAIN_SCREEN_W-40-CONF_HOLD_WIDTH)
#define	CONF_HOLD_T_PAD 674
#define	CONF_HOLD_HEIGHT 78

#define	CONF_TIMER_T_PAD 674
#define	CONF_TIMER_HEIGHT 78

#define CONF_CALL_BIG_END_L_PAD 16
#define	CONF_CALL_BIG_END_T_PAD 870
#define CONF_CALL_BIG_END_WIDTH 688

#define	REJ_MSG_NEW_BTN_L_PAD 40
#define	REJ_MSG_NEW_BTN_WIDTH 640
#define	REJ_MSG_NEW_BTN_T_PAD 120
#define	REJ_MSG_NEW_BTN_HEIGHT 128

#define REJ_MSG_LIST_T_PAD 32
#define	REJ_MSG_LIST_HEIGHT 1096

#define	SIX_BTN_LAYOUT_L_PAD 0
#define	SIX_BTN_LAYOUT_WIDTH 720
#define	SIX_BTN_LAYOUT_T_PAD 940
#define	SIX_BTN_LAYOUT_HEIGHT 340

#define THREE_BTN_LAYOUT_WIDTH MAIN_SCREEN_W
#define THREE_BTN_LAYOUT_HEIGHT 222

#define	BTN_LAYOUT_SINGLE_BTN_WIDTH 216
#define	BTN_LAYOUT_SINGLE_BTN_HEIGHT 168
#define	BTN_LAYOUT_BTN_GAP 2

#define	BTN_LAYOUT_LEFT_BTN_L_PAD 34
#define	BTN_LAYOUT_MIDDLE_BTN_L_PAD (BTN_LAYOUT_LEFT_BTN_L_PAD+BTN_LAYOUT_SINGLE_BTN_WIDTH+BTN_LAYOUT_BTN_GAP)
#define	BTN_LAYOUT_RIGHT_BTN_L_PAD (BTN_LAYOUT_MIDDLE_BTN_L_PAD+BTN_LAYOUT_SINGLE_BTN_WIDTH+BTN_LAYOUT_BTN_GAP)

#define	BTN_LAYOUT_TOP_BTN_T_PAD 0
#define	BTN_LAYOUT_BOTTOM_BTN_T_PAD (BTN_LAYOUT_TOP_BTN_T_PAD+BTN_LAYOUT_SINGLE_BTN_HEIGHT+BTN_LAYOUT_BTN_GAP)

#define LEFT_VERT_SEP_L_PAD 250
#define RIGHT_VERT_SEP_L_PAD 468
#define TOP_VERT_SEP_T_PAD 22
#define BOTTOM_VERT_SEP_T_PAD 192
#define HORIZ_SEP_L_PAD 34
#define TOP_HORIZ_SEP_T_PAD 168
#define BOTTOM_HORIZ_SEP_T_PAD 338
#define SEPARTOR_WIDTH 1
#define VERT_SEP_HEIGHT 124
#define HORIZ_SEP_WIDTH 652

#define ENDCALL_LEFT_VERT_SEP_L_PAD 250
#define ENDCALL_SEPARTOR_WIDTH 1
#define ENDCALL_VERT_SEP_T_PAD 49
#define ENDCALL_VERT_SEP_HEIGHT 124
#define ENDCALL_RIGHT_VERT_SEP_L_PAD 468

#define	CALL_BIG_END_L_PAD 40
#define	CALL_BIG_END_WIDTH 640
#define	CALL_BIG_END_T_PAD 1140
#define	CALL_BIG_END_HEIGHT 112

#define INCMG_CALL_BTN1_T_PAD 700
#define INCMG_CALL_BTN_HEIGHT CALL_BIG_END_HEIGHT
#define INCMG_CALL_BTN2_T_PAD 838
#define INCMG_CALL_BTN3_T_PAD 976

#define	ENDCALL_VOICE_BTN_L_PAD 34
#define	ENDCALL_VOICE_BTN_WIDTH 216
#define	ENDCALL_VOICE_BTN_T_PAD 1058
#define	ENDCALL_VOICE_BTN_HEIGHT 222
#define	ENDCALL_VIDEO_BTN_L_PAD (ENDCALL_VOICE_BTN_L_PAD+ENDCALL_VOICE_BTN_WIDTH+2)
#define	ENDCALL_MSG_BTN_L_PAD (ENDCALL_VIDEO_BTN_L_PAD+ENDCALL_VOICE_BTN_WIDTH+2)

#define	ENDCALL_CONTACT_BTN_L_PAD 40
#define	ENDCALL_CONTACT_BTN_WIDTH 640
#define	ENDCALL_CONTACT_BTN_T_PAD 896
#define	ENDCALL_CONTACT_BTN_HEIGHT 92

#define QP_CID_L_PAD 16
#define QP_CID_WIDTH 105
#define QP_CID_T_PAD 33
#define QP_CID_HEIGHT 105

#define QP_MUTE_BTN_L_PAD 172
#define QP_MUTE_BTN_WIDTH 256
#define QP_MUTE_BTN_T_PAD 78
#define QP_MUTE_BTN_HEIGHT 74

#define QP_END_BTN_L_PAD 448
#define QP_END_BTN_WIDTH QP_MUTE_BTN_WIDTH
#define QP_END_BTN_T_PAD QP_MUTE_BTN_T_PAD
#define QP_END_BTN_HEIGHT QP_MUTE_BTN_HEIGHT

#define QP_NAME_L_PAD QP_MUTE_BTN_L_PAD
#define QP_NAME_WIDTH 532
#define QP_NAME_T_PAD 22
#define QP_NAME_HEIGHT 36

#define QP_STR_MIN_WIDTH 50
/*
 * End of NBEAT-HD GUI Widget Dimensions
 */


/*
 * Relative positions
 * In Portrait mode
 */
/* Relative X & Y positions of widgets w.r.t. Full Screen */
#define REL_W(x) ((x)/MAIN_SCREEN_W)
#define REL_H(y) ((y)/MAIN_SCREEN_H)

/* Relative X & Y positions of widgets w.r.t. Navi-frame layout */
/*#define WL_NB_H 94*/
#define REL_NAVIFRAME_W(x) ((x)/MAIN_NAVIFRAME_W)
#define REL_NAVIFRAME_H(y) ((y)/MAIN_NAVIFRAME_H)

/* Relative X & Y positions of widgets w.r.t. ACC/REJ ICON layout */
#define REL_LOCK_W(x) ((x)/483)
#define REL_LOCK_H(y) ((y)/198)
/* Relative X & Y positions of widgets w.r.t. REJ-W-MSG ICON layout */
#define REL_LOCK_MSG_W(x) ((x)/348)
#define REL_LOCK_MSG_H(y) ((y)/200)

/* Relative X & Y positions of widgets w.r.t. Keypad layout */
#define REL_KEYPAD_W(x) ((x)/KEYPAD_AREA_WIDTH)
#define REL_KEYPAD_H(y) ((y)/KEYPAD_AREA_HEIGHT)

/* Relative X & Y positions of widgets w.r.t. Keypad Buttons layout */
#define REL_KEYPAD_BTNS_W(x) ((x)/KEYPAD_BTNS_BG_WIDTH)
#define REL_KEYPAD_BTNS_H(y) ((y)/KEYPAD_BTNS_BG_HEIGHT)

/* Relative X & Y positions of widgets w.r.t. Quick-panel layout */
#define REL_QP_W(x) ((x)/QP_WIN_W)
#define REL_QP_H(y) ((y)/QP_WIN_H)

/* Relative X & Y positions of buttons w.r.t. Six-Button layout */
#define	REL_BTN_LY_W(x) ((x)/SIX_BTN_LAYOUT_WIDTH)
#define	REL_BTN_LY_H(y) ((y)/SIX_BTN_LAYOUT_HEIGHT)

/* Relative X & Y positions of buttons w.r.t. Three-Button layout of ENDCALL*/
#define REL_THREE_BTN_LY_W(x) ((x)/THREE_BTN_LAYOUT_WIDTH)
#define REL_THREE_BTN_LY_H(y) ((y)/THREE_BTN_LAYOUT_HEIGHT)

/* Relative X position of elements w.r.t. Keypad-Button layout */
#define	REL_KEYPAD_BTN_W(x) ((x)/KEYPAD_EACH_BTN_WIDTH)

/*Relative Y postions of elements w.r.t. Caller info layout*/
#define REL_CALLER_INFO_H(y) ((y)/CALLER_INFO_HEIGHT)

/*Relative Y postions of elements w.r.t. Multi list layout*/
#define REL_MULTI_LIST_H(y) ((y)/MULTI_LIST_HEIGHT)

/*Relative X and Y positions of elements w.r.t. SNS-Alerts layout*/
#define	REL_ALERTS_LY_W(x) ((x)/SNS_ALERTS_LAYOUT_WIDTH)
#define	REL_ALERTS_LY_H(y) ((y)/SNS_ALERTS_LAYOUT_HEIGHT)
#define	REL_ALERTS_EXP_LY_H(y) ((y)/SNS_ALERTS_LAYOUT_EXPANDED_HEIGHT)
/*
 * End of Relative positions
 */


/*
 * MO/Dialing view & MT/Incoming view
 * In Portrait mode
 */

#define DIALLING_CID_L REL_W(CALLER_ID_L_PAD)
#define DIALLING_CID_R REL_W(CALLER_ID_L_PAD+CALLER_ID_WIDTH)
#define DIALLING_CID_T REL_H(CALLER_ID_T_PAD)
#define DIALLING_CID_B REL_H(CALLER_ID_T_PAD+CALLER_ID_HEIGHT)

#define DIALLING_CID_NOIMAGE_L REL_W(NOIMAGE_L_PAD)
#define DIALLING_CID_NOIMAGE_R REL_W(NOIMAGE_L_PAD+NOIMAGE_WIDTH)
#define DIALLING_CID_NOIMAGE_T REL_H(NOIMAGE_T_PAD)
#define DIALLING_CID_NOIMAGE_B REL_H(NOIMAGE_T_PAD+NOIMAGE_HEIGHT)

#define DIALLING_BACKGROUND_CID_L REL_W(BACKGROUND_CID_L_PAD)
#define DIALLING_BACKGROUND_CID_R REL_W(BACKGROUND_CID_L_PAD+BACKGROUND_CID_WIDTH)
#define DIALLING_BACKGROUND_CID_T REL_H(BACKGROUND_CID_T_PAD)
#define DIALLING_BACKGROUND_CID_B REL_H(BACKGROUND_CID_T_PAD+BACKGROUND_CID_HEIGHT)

#define MT_CALLING_BG_L REL_W(0)
#define MT_CALLING_BG_R REL_W(0+MT_CALLING_NAME_BG_WIDTH)
#define MT_CALLING_BG_T REL_H(0)
#define MT_CALLING_BG_B REL_H(0+MT_CALLING_NAME_BG_HEIGHT)

/* accept - MT view */
#define DIALLING_MT_BTN1_L REL_W(ACCEPT_BTN_L_PAD)
#define DIALLING_MT_BTN1_R REL_W(ACCEPT_BTN_L_PAD+ACCEPT_BTN_WIDTH)
#define DIALLING_MT_BTN1_T REL_H(ACCEPT_BTN_T_PAD)
#define DIALLING_MT_BTN1_B REL_H(ACCEPT_BTN_T_PAD+ACCEPT_BTN_HEIGHT)

/* reject - MT view */
#define DIALLING_MT_BTN2_L  REL_W(REJECT_BTN_L_PAD)
#define DIALLING_MT_BTN2_R  REL_W(REJECT_BTN_L_PAD+REJECT_BTN_WIDTH)
#define DIALLING_MT_BTN2_T  REL_H(REJECT_BTN_T_PAD)
#define DIALLING_MT_BTN2_B  REL_H(REJECT_BTN_T_PAD+REJECT_BTN_HEIGHT)

/* reject with msg - MT view */
#define DIALLING_MT_BTN3_L  REL_W(REJECT_W_MSG_BTN_L_PAD)
#define DIALLING_MT_BTN3_R  REL_W(REJECT_W_MSG_BTN_L_PAD+REJECT_W_MSG_BTN_WIDTH)
#define DIALLING_MT_BTN3_T  REL_H(REJECT_W_MSG_BTN_T_PAD)
#define DIALLING_MT_BTN3_B  REL_H(REJECT_W_MSG_BTN_T_PAD+REJECT_W_MSG_BTN_HEIGHT)

#define DIALLING_MT_SNS_ALERTS_LAYOUT_L REL_W(SNS_ALERTS_LAYOUT_L_PAD)
#define DIALLING_MT_SNS_ALERTS_LAYOUT_R REL_W(SNS_ALERTS_LAYOUT_L_PAD+SNS_ALERTS_LAYOUT_WIDTH)
#define DIALLING_MT_SNS_ALERTS_LAYOUT_T REL_H(SNS_ALERTS_LAYOUT_T_PAD)
#define DIALLING_MT_SNS_ALERTS_LAYOUT_B REL_H(SNS_ALERTS_LAYOUT_T_PAD+SNS_ALERTS_LAYOUT_HEIGHT)

#define DIALLING_MT_SNS_ALERTS_LAYOUT_EXPANDED_T REL_H(SNS_ALERTS_LAYOUT_EXPANDED_T_PAD)
#define DIALLING_MT_SNS_ALERTS_LAYOUT_EXPANDED_B REL_H(SNS_ALERTS_LAYOUT_EXPANDED_T_PAD+SNS_ALERTS_LAYOUT_EXPANDED_HEIGHT)

#define DIALLING_MT_SNS_ALERTS_LAYOUT_SHIFT_T REL_H(SNS_ALERTS_LAYOUT_SHIFT_T_PAD)
#define DIALLING_MT_SNS_ALERTS_LAYOUT_SHIFT_B REL_H(SNS_ALERTS_LAYOUT_SHIFT_T_PAD+SNS_ALERTS_LAYOUT_HEIGHT)

#define DIALLING_MT_SNS_ALERTS_LAYOUT_SHIFT_EXPANDED_T REL_H(SNS_ALERTS_LAYOUT_SHIFT_EXPANDED_T_PAD)
#define DIALLING_MT_SNS_ALERTS_LAYOUT_SHIFT_EXPANDED_B REL_H(SNS_ALERTS_LAYOUT_SHIFT_EXPANDED_T_PAD+SNS_ALERTS_LAYOUT_EXPANDED_HEIGHT)
/*
#define	DIALLING_MT_BDAY_ICON_L	REL_W(BIRTHDAY_ICON_L_PAD)
#define	DIALLING_MT_BDAY_ICON_R	REL_W(BIRTHDAY_ICON_L_PAD+BIRTHDAY_ICON_WIDTH)
#define	DIALLING_MT_BDAY_ICON_T	REL_H(BIRTHDAY_ICON_T_PAD)
#define	DIALLING_MT_BDAY_ICON_B	REL_H(BIRTHDAY_ICON_T_PAD+BIRTHDAY_ICON_HEIGHT)

#define DIALLING_MT_BDAY_ICON_SHIFT_L REL_W(BIRTHDAY_ICON_SHIFT_L_PAD)
#define DIALLING_MT_BDAY_ICON_SHIFT_R REL_W(BIRTHDAY_ICON_SHIFT_L_PAD+BIRTHDAY_ICON_SHIFT_WIDTH)
#define DIALLING_MT_BDAY_ICON_SHIFT_T REL_H(BIRTHDAY_ICON_SHIFT_T_PAD)
#define DIALLING_MT_BDAY_ICON_SHIFT_B REL_H(BIRTHDAY_ICON_SHIFT_T_PAD+BIRTHDAY_ICON_SHIFT_HEIGHT)

#define	DIALLING_MT_BDAY_TEXT_L	REL_W(BIRTHDAY_TEXT_L_PAD)
#define	DIALLING_MT_BDAY_TEXT_R	REL_W(BIRTHDAY_TEXT_L_PAD+BIRTHDAY_TEXT_WIDTH)
#define	DIALLING_MT_BDAY_TEXT_T	REL_H(BIRTHDAY_TEXT_T_PAD)
#define	DIALLING_MT_BDAY_TEXT_B	REL_H(BIRTHDAY_TEXT_T_PAD+BIRTHDAY_TEXT_HEIGHT)

#define DIALLING_MT_BDAY_TEXT_SHIFT_L REL_W(BIRTHDAY_TEXT_SHIFT_L_PAD)
#define DIALLING_MT_BDAY_TEXT_SHIFT_R REL_W(BIRTHDAY_TEXT_SHIFT_L_PAD+BIRTHDAY_TEXT_SHIFT_WIDTH)
#define DIALLING_MT_BDAY_TEXT_SHIFT_T REL_H(BIRTHDAY_TEXT_SHIFT_T_PAD)
#define DIALLING_MT_BDAY_TEXT_SHIFT_B REL_H(BIRTHDAY_TEXT_SHIFT_T_PAD+BIRTHDAY_TEXT_SHIFT_HEIGHT)
*/
/*
 * End of MO/Dialing view & MT/Incoming view
 */

/*
 * Endcall view
 * In Portrait mode
 */
#define ENDCALL_DIALLING_CID_L REL_W(ENDCALL_CALLER_ID_L_PAD)
#define ENDCALL_DIALLING_CID_R REL_W(ENDCALL_CALLER_ID_L_PAD+ENDCALL_CALLER_ID_WIDTH)
#define ENDCALL_DIALLING_CID_T REL_H(ENDCALL_CALLER_ID_T_PAD)
#define ENDCALL_DIALLING_CID_B REL_H(ENDCALL_CALLER_ID_T_PAD+ENDCALL_CALLER_ID_HEIGHT)

#define ENDCALL_DIALLING_BTN_BG_L REL_W(ENDCALL_BTN_BG_L_PAD)
#define ENDCALL_DIALLING_BTN_BG_R REL_W(ENDCALL_BTN_BG_L_PAD+ENDCALL_BTN_BG_WIDTH)
#define ENDCALL_DIALLING_BTN_BG_T REL_H(ENDCALL_BTN_BG_T_PAD)
#define ENDCALL_DIALLING_BTN_BG_B REL_H(ENDCALL_BTN_BG_T_PAD+ENDCALL_BTN_BG_HEIGHT)

/*
 * End of Endcall view
 */

/*
 * MT LOCK View - check
 * In Portrait mode
 */
#define INCOMING_LOCK_ACCEPT_BG_L REL_W(-273)
#define INCOMING_LOCK_ACCEPT_BG_R REL_W(210)
#define INCOMING_LOCK_ACCEPT_BG_T REL_H(945)
#define INCOMING_LOCK_ACCEPT_BG_B REL_H(1144)

#define INCOMING_LOCK_ACCEPT_ICON_L REL_LOCK_W(303)
#define INCOMING_LOCK_ACCEPT_ICON_R REL_LOCK_W(408)
#define INCOMING_LOCK_ACCEPT_ICON_T REL_LOCK_H(37)
#define INCOMING_LOCK_ACCEPT_ICON_B REL_LOCK_H(149)

#define INCOMING_LOCK_ACCEPT_TEXT_L REL_LOCK_W(45)
#define INCOMING_LOCK_ACCEPT_TEXT_R REL_LOCK_W(273)
#define INCOMING_LOCK_ACCEPT_TEXT_T INCOMING_LOCK_ACCEPT_ICON_T
#define INCOMING_LOCK_ACCEPT_TEXT_B INCOMING_LOCK_ACCEPT_ICON_B

#define INCOMING_LOCK_REJECT_BG_L REL_W(510)
#define INCOMING_LOCK_REJECT_BG_R REL_W(993)
#define INCOMING_LOCK_REJECT_BG_T INCOMING_LOCK_ACCEPT_BG_T
#define INCOMING_LOCK_REJECT_BG_B INCOMING_LOCK_ACCEPT_BG_B

#define INCOMING_LOCK_REJECT_ICON_L REL_LOCK_W(75)
#define INCOMING_LOCK_REJECT_ICON_R REL_LOCK_W(180)
#define INCOMING_LOCK_REJECT_ICON_T INCOMING_LOCK_ACCEPT_ICON_T
#define INCOMING_LOCK_REJECT_ICON_B INCOMING_LOCK_ACCEPT_ICON_B

#define INCOMING_LOCK_REJECT_TEXT_L REL_LOCK_W(195)
#define INCOMING_LOCK_REJECT_TEXT_R REL_LOCK_W(423)
#define INCOMING_LOCK_REJECT_TEXT_T INCOMING_LOCK_REJECT_ICON_T
#define INCOMING_LOCK_REJECT_TEXT_B INCOMING_LOCK_REJECT_ICON_B

#define INCOMING_LOCK_REJECT_WITH_MSG_BG_L REL_W(186)
#define INCOMING_LOCK_REJECT_WITH_MSG_BG_R REL_W(534)
#define INCOMING_LOCK_REJECT_WITH_MSG_BG_T REL_H(1208)
#define INCOMING_LOCK_REJECT_WITH_MSG_BG_B REL_H(1408)

#define INCOMING_LOCK_REJECT_WITH_MSG_TEXT_L REL_LOCK_MSG_W(0)
#define INCOMING_LOCK_REJECT_WITH_MSG_TEXT_R REL_LOCK_MSG_W(348)
#define INCOMING_LOCK_REJECT_WITH_MSG_TEXT_T REL_LOCK_MSG_H(0)
#define INCOMING_LOCK_REJECT_WITH_MSG_TEXT_B REL_LOCK_MSG_H(72)

#define MTLOCK_ACCEPT_INNER_CIRCLE_L REL_W(MTLOCK_ACCEPT_INNER_CIRCLE_BG_L_PAD)
#define MTLOCK_ACCEPT_INNER_CIRCLE_R REL_W(MTLOCK_ACCEPT_INNER_CIRCLE_BG_L_PAD+MTLOCK_ACCEPT_INNER_CIRCLE_BG_WIDTH)
#define MTLOCK_ACCEPT_INNER_CIRCLE_T REL_H(MTLOCK_ACCEPT_INNER_CIRCLE_BG_T_PAD)
#define MTLOCK_ACCEPT_INNER_CIRCLE_B REL_H(MTLOCK_ACCEPT_INNER_CIRCLE_BG_T_PAD+MTLOCK_ACCEPT_INNER_CIRCLE_BG_HEIGHT)

#define MTLOCK_ACCEPT_ICON_L REL_W(MTLOCK_ACCEPT_ICON_L_PAD)
#define MTLOCK_ACCEPT_ICON_R REL_W(MTLOCK_ACCEPT_ICON_L_PAD+MTLOCK_ACCEPT_ICON_WIDTH)
#define MTLOCK_ACCEPT_ICON_T REL_H(MTLOCK_ACCEPT_ICON_T_PAD)
#define MTLOCK_ACCEPT_ICON_B REL_H(MTLOCK_ACCEPT_ICON_T_PAD+MTLOCK_ACCEPT_ICON_HEIGHT)

#define MTLOCK_ACCEPT_OUTER_CIRCLE_L REL_W(MTLOCK_ACCEPT_OUTER_CIRCLE_BG_L_PAD)
#define MTLOCK_ACCEPT_OUTER_CIRCLE_R REL_W(MTLOCK_ACCEPT_OUTER_CIRCLE_BG_L_PAD+MTLOCK_ACCEPT_OUTER_CIRCLE_BG_WIDTH)
#define MTLOCK_ACCEPT_OUTER_CIRCLE_T REL_H(MTLOCK_ACCEPT_OUTER_CIRCLE_BG_T_PAD)
#define MTLOCK_ACCEPT_OUTER_CIRCLE_B REL_H(MTLOCK_ACCEPT_OUTER_CIRCLE_BG_T_PAD+MTLOCK_ACCEPT_OUTER_CIRCLE_BG_HEIGHT)

#define MTLOCK_ACCEPT_ARROW1_L REL_W(MTLOCK_ACCEPT_ARROW1_L_PAD)
#define MTLOCK_ACCEPT_ARROW1_R REL_W(MTLOCK_ACCEPT_ARROW1_L_PAD+MTLOCK_ACCEPT_ARROW1_WIDTH)
#define MTLOCK_ACCEPT_ARROW1_T REL_H(MTLOCK_ACCEPT_ARROW1_T_PAD)
#define MTLOCK_ACCEPT_ARROW1_B REL_H(MTLOCK_ACCEPT_ARROW1_T_PAD+MTLOCK_ACCEPT_ARROW1_HEIGHT)

#define MTLOCK_ACCEPT_ARROW2_L REL_W(MTLOCK_ACCEPT_ARROW2_L_PAD)
#define MTLOCK_ACCEPT_ARROW2_R REL_W(MTLOCK_ACCEPT_ARROW2_L_PAD+MTLOCK_ACCEPT_ARROW2_WIDTH)
#define MTLOCK_ACCEPT_ARROW2_T REL_H(MTLOCK_ACCEPT_ARROW2_T_PAD)
#define MTLOCK_ACCEPT_ARROW2_B REL_H(MTLOCK_ACCEPT_ARROW2_T_PAD+MTLOCK_ACCEPT_ARROW2_HEIGHT)

#define MTLOCK_ACCEPT_ARROW3_L REL_W(MTLOCK_ACCEPT_ARROW3_L_PAD)
#define MTLOCK_ACCEPT_ARROW3_R REL_W(MTLOCK_ACCEPT_ARROW3_L_PAD+MTLOCK_ACCEPT_ARROW3_WIDTH)
#define MTLOCK_ACCEPT_ARROW3_T REL_H(MTLOCK_ACCEPT_ARROW3_T_PAD)
#define MTLOCK_ACCEPT_ARROW3_B REL_H(MTLOCK_ACCEPT_ARROW3_T_PAD+MTLOCK_ACCEPT_ARROW3_HEIGHT)

#define MTLOCK_REJECT_INNER_CIRCLE_L REL_W(MTLOCK_REJECT_INNER_CIRCLE_BG_L_PAD)
#define MTLOCK_REJECT_INNER_CIRCLE_R REL_W(MTLOCK_REJECT_INNER_CIRCLE_BG_L_PAD+MTLOCK_REJECT_INNER_CIRCLE_BG_WIDTH)
#define MTLOCK_REJECT_INNER_CIRCLE_T REL_H(MTLOCK_REJECT_INNER_CIRCLE_BG_T_PAD)
#define MTLOCK_REJECT_INNER_CIRCLE_B REL_H(MTLOCK_REJECT_INNER_CIRCLE_BG_T_PAD+MTLOCK_REJECT_INNER_CIRCLE_BG_HEIGHT)

#define MTLOCK_REJECT_ICON_L REL_W(MTLOCK_REJECT_ICON_L_PAD)
#define MTLOCK_REJECT_ICON_R REL_W(MTLOCK_REJECT_ICON_L_PAD+MTLOCK_REJECT_ICON_WIDTH)
#define MTLOCK_REJECT_ICON_T REL_H(MTLOCK_REJECT_ICON_T_PAD)
#define MTLOCK_REJECT_ICON_B REL_H(MTLOCK_REJECT_ICON_T_PAD+MTLOCK_REJECT_ICON_HEIGHT)

#define MTLOCK_REJECT_OUTER_CIRCLE_L REL_W(MTLOCK_REJECT_OUTER_CIRCLE_BG_L_PAD)
#define MTLOCK_REJECT_OUTER_CIRCLE_R REL_W(MTLOCK_REJECT_OUTER_CIRCLE_BG_L_PAD+MTLOCK_REJECT_OUTER_CIRCLE_BG_WIDTH)
#define MTLOCK_REJECT_OUTER_CIRCLE_T REL_H(MTLOCK_REJECT_OUTER_CIRCLE_BG_T_PAD)
#define MTLOCK_REJECT_OUTER_CIRCLE_B REL_H(MTLOCK_REJECT_OUTER_CIRCLE_BG_T_PAD+MTLOCK_REJECT_OUTER_CIRCLE_BG_HEIGHT)

#define MTLOCK_REJECT_ARROW1_L REL_W(MTLOCK_REJECT_ARROW1_L_PAD)
#define MTLOCK_REJECT_ARROW1_R REL_W(MTLOCK_REJECT_ARROW1_L_PAD+MTLOCK_REJECT_ARROW1_WIDTH)
#define MTLOCK_REJECT_ARROW1_T REL_H(MTLOCK_REJECT_ARROW1_T_PAD)
#define MTLOCK_REJECT_ARROW1_B REL_H(MTLOCK_REJECT_ARROW1_T_PAD+MTLOCK_REJECT_ARROW1_HEIGHT)

#define MTLOCK_REJECT_ARROW2_L REL_W(MTLOCK_REJECT_ARROW2_L_PAD)
#define MTLOCK_REJECT_ARROW2_R REL_W(MTLOCK_REJECT_ARROW2_L_PAD+MTLOCK_REJECT_ARROW2_WIDTH)
#define MTLOCK_REJECT_ARROW2_T REL_H(MTLOCK_REJECT_ARROW2_T_PAD)
#define MTLOCK_REJECT_ARROW2_B REL_H(MTLOCK_REJECT_ARROW2_T_PAD+MTLOCK_REJECT_ARROW2_HEIGHT)

#define MTLOCK_REJECT_ARROW3_L REL_W(MTLOCK_REJECT_ARROW3_L_PAD)
#define MTLOCK_REJECT_ARROW3_R REL_W(MTLOCK_REJECT_ARROW3_L_PAD+MTLOCK_REJECT_ARROW3_WIDTH)
#define MTLOCK_REJECT_ARROW3_T REL_H(MTLOCK_REJECT_ARROW3_T_PAD)
#define MTLOCK_REJECT_ARROW3_B REL_H(MTLOCK_REJECT_ARROW3_T_PAD+MTLOCK_REJECT_ARROW3_HEIGHT)

#define MTLOCK_REJECT_MSG_BG_L REL_W(MTLOCK_REJECT_MSG_BG_L_PAD)
#define MTLOCK_REJECT_MSG_BG_R REL_W(MTLOCK_REJECT_MSG_BG_L_PAD+MTLOCK_REJECT_MSG_BG_WIDTH)
#define MTLOCK_REJECT_MSG_BG_T REL_H(MTLOCK_REJECT_MSG_BG_T_PAD)
#define MTLOCK_REJECT_MSG_BG_B REL_H(MTLOCK_REJECT_MSG_BG_T_PAD+MTLOCK_REJECT_MSG_BG_HEIGHT)

#define	MTLOCK_REJECT_MSG_ARW_L REL_W(MTLOCK_REJECT_MSG_ARW_L_PAD)
#define	MTLOCK_REJECT_MSG_ARW_R REL_W(MTLOCK_REJECT_MSG_ARW_L_PAD+MTLOCK_REJECT_MSG_ARW_WIDTH)
#define	MTLOCK_REJECT_MSG_ARW_T REL_H(MTLOCK_REJECT_MSG_ARW_T_PAD)
#define	MTLOCK_REJECT_MSG_ARW_B REL_H(MTLOCK_REJECT_MSG_ARW_T_PAD+MTLOCK_REJECT_MSG_ARW_HEIGHT)

#define MTLOCK_REJECT_MSG_TEXT_L REL_W(MTLOCK_REJECT_MSG_TEXT_L_PAD)
#define MTLOCK_REJECT_MSG_TEXT_R REL_W(MTLOCK_REJECT_MSG_TEXT_L_PAD+MTLOCK_REJECT_MSG_TEXT_WIDTH)
#define MTLOCK_REJECT_MSG_TEXT_T REL_H(MTLOCK_REJECT_MSG_TEXT_T_PAD)
#define MTLOCK_REJECT_MSG_TEXT_B REL_H(MTLOCK_REJECT_MSG_TEXT_T_PAD+MTLOCK_REJECT_MSG_TEXT_HEIGHT)

#define MTLOCK_REJECT_MSG_LIST_L REL_W(MTLOCK_REJECT_MSG_LIST_L_PAD)
#define MTLOCK_REJECT_MSG_LIST_R REL_W(MTLOCK_REJECT_MSG_LIST_L_PAD+MTLOCK_REJECT_MSG_LIST_WIDTH)
#define MTLOCK_REJECT_MSG_LIST_T REL_H(MTLOCK_REJECT_MSG_LIST_T_PAD)
#define MTLOCK_REJECT_MSG_ONE_LINE_LIST_B REL_H(MTLOCK_REJECT_MSG_LIST_T_PAD+MTLOCK_REJECT_MSG_ONE_LINE_LIST_HEIGHT)
#define MTLOCK_REJECT_MSG_TWO_LINE_LIST_B REL_H(MTLOCK_REJECT_MSG_LIST_T_PAD+MTLOCK_REJECT_MSG_TWO_LINE_LIST_HEIGHT)
#define MTLOCK_REJECT_MSG_THREE_LINE_LIST_B REL_H(MTLOCK_REJECT_MSG_LIST_T_PAD+MTLOCK_REJECT_MSG_THREE_LINE_LIST_HEIGHT)
#define MTLOCK_REJECT_MSG_FOUR_LINE_LIST_B REL_H(MTLOCK_REJECT_MSG_LIST_T_PAD+MTLOCK_REJECT_MSG_FOUR_LINE_LIST_HEIGHT)
#define MTLOCK_REJECT_MSG_FIVE_LINE_LIST_B REL_H(MTLOCK_REJECT_MSG_LIST_T_PAD+MTLOCK_REJECT_MSG_FIVE_LINE_LIST_HEIGHT)
#define MTLOCK_REJECT_MSG_SIX_LINE_LIST_B REL_H(MTLOCK_REJECT_MSG_LIST_T_PAD+MTLOCK_REJECT_MSG_SIX_LINE_LIST_HEIGHT)
/*
 * End of MT LOCK View
 */


/*
 * KEYPAD View
 * In Portrait mode
 */
#define KEYPAD_AREA_L REL_W(KEYPAD_AREA_L_PAD)
#define KEYPAD_AREA_R REL_W(KEYPAD_AREA_WIDTH)
#define KEYPAD_AREA_T REL_H(KEYPAD_AREA_T_PAD)
#define KEYPAD_AREA_B REL_H(KEYPAD_AREA_T_PAD+KEYPAD_AREA_HEIGHT)

#define KEYPAD_ENTRY_TEXT_L REL_KEYPAD_W(KEYPAD_ENTRY_TXT_L_PAD)
#define KEYPAD_ENTRY_TEXT_R REL_KEYPAD_W(KEYPAD_ENTRY_TXT_L_PAD+KEYPAD_ENTRY_TXT_WIDTH)
#define KEYPAD_ENTRY_TEXT_T REL_KEYPAD_H(KEYPAD_ENTRY_TXT_T_PAD)
#define KEYPAD_ENTRY_TEXT_B REL_KEYPAD_H(KEYPAD_ENTRY_TXT_T_PAD+KEYPAD_ENTRY_TXT_HEIGHT)

#define KEYPAD_BTNS_BG_L REL_KEYPAD_W(KEYPAD_BTNS_BG_L_PAD)
#define KEYPAD_BTNS_BG_R REL_KEYPAD_W(KEYPAD_BTNS_BG_L_PAD+KEYPAD_BTNS_BG_WIDTH)
#define KEYPAD_BTNS_BG_T REL_KEYPAD_H(KEYPAD_BTNS_BG_T_PAD)
#define KEYPAD_BTNS_BG_B REL_KEYPAD_H(KEYPAD_BTNS_BG_T_PAD+KEYPAD_BTNS_BG_HEIGHT)

#define	KEYPAD_BTN_LEFT_TXT_L REL_KEYPAD_BTN_W(LEFT_TXT_L_PAD)
#define	KEYPAD_BTN_LEFT_TXT_R REL_KEYPAD_BTN_W(LEFT_TXT_L_PAD+LEFT_TXT_WIDTH)
#define	KEYPAD_BTN_RIGHT_TXT_TYPE1_L REL_KEYPAD_BTN_W(LEFT_TXT_L_PAD+LEFT_TXT_WIDTH+RIGHT_TXT_TYPE1_L_PAD)
#define	KEYPAD_BTN_RIGHT_TXT_TYPE2_L REL_KEYPAD_BTN_W(LEFT_TXT_L_PAD+LEFT_TXT_WIDTH+RIGHT_TXT_TYPE2_L_PAD)
#define KEYPAD_BTN_RIGHT_ICON_L REL_KEYPAD_BTN_W(LEFT_TXT_L_PAD+LEFT_TXT_WIDTH+RIGHT_ICON_L_PAD)
#define KEYPAD_BTN_RIGHT_ICON_R REL_KEYPAD_BTN_W(LEFT_TXT_L_PAD+LEFT_TXT_WIDTH+RIGHT_ICON_L_PAD+RIGHT_ICON_WIDTH)

#define KEYPAD_ROW1_LVERT_SEP1_L REL_KEYPAD_BTNS_W(KP_LVERT_SEP1_L_PAD)
#define KEYPAD_ROW1_LVERT_SEP1_R REL_KEYPAD_BTNS_W(KP_LVERT_SEP1_L_PAD+KEYPAD_VERT_SEP_WIDTH)
#define KEYPAD_ROW1_LVERT_SEP1_T REL_KEYPAD_BTNS_H(KP_ROW1_VERT_SEP_T_PAD)
#define KEYPAD_ROW1_LVERT_SEP1_B REL_KEYPAD_BTNS_H(KP_ROW1_VERT_SEP_T_PAD+KEYPAD_VERT_SEP_HEIGHT)

#define KEYPAD_ROW1_LVERT_SEP2_L KEYPAD_ROW1_LVERT_SEP1_R
#define KEYPAD_ROW1_LVERT_SEP2_R REL_KEYPAD_BTNS_W(KP_LVERT_SEP1_L_PAD+2*KEYPAD_VERT_SEP_WIDTH)
#define KEYPAD_ROW1_LVERT_SEP2_T KEYPAD_ROW1_LVERT_SEP1_T
#define KEYPAD_ROW1_LVERT_SEP2_B KEYPAD_ROW1_LVERT_SEP1_B

#define KEYPAD_ROW1_RVERT_SEP1_L REL_KEYPAD_BTNS_W(KP_RVERT_SEP1_L_PAD)
#define KEYPAD_ROW1_RVERT_SEP1_R REL_KEYPAD_BTNS_W(KP_RVERT_SEP1_L_PAD+KEYPAD_VERT_SEP_WIDTH)
#define KEYPAD_ROW1_RVERT_SEP1_T KEYPAD_ROW1_LVERT_SEP1_T
#define KEYPAD_ROW1_RVERT_SEP1_B KEYPAD_ROW1_LVERT_SEP1_B

#define KEYPAD_ROW1_RVERT_SEP2_L KEYPAD_ROW1_RVERT_SEP1_R
#define KEYPAD_ROW1_RVERT_SEP2_R REL_KEYPAD_BTNS_W(KP_RVERT_SEP1_L_PAD+2*KEYPAD_VERT_SEP_WIDTH)
#define KEYPAD_ROW1_RVERT_SEP2_T KEYPAD_ROW1_LVERT_SEP1_T
#define KEYPAD_ROW1_RVERT_SEP2_B KEYPAD_ROW1_LVERT_SEP1_B

#define KEYPAD_ROW2_LVERT_SEP1_L REL_KEYPAD_BTNS_W(KP_LVERT_SEP1_L_PAD)
#define KEYPAD_ROW2_LVERT_SEP1_R REL_KEYPAD_BTNS_W(KP_LVERT_SEP1_L_PAD+KEYPAD_VERT_SEP_WIDTH)
#define KEYPAD_ROW2_LVERT_SEP1_T REL_KEYPAD_BTNS_H(KP_ROW2_VERT_SEP_T_PAD)
#define KEYPAD_ROW2_LVERT_SEP1_B REL_KEYPAD_BTNS_H(KP_ROW2_VERT_SEP_T_PAD+KEYPAD_VERT_SEP_HEIGHT)

#define KEYPAD_ROW2_LVERT_SEP2_L KEYPAD_ROW2_LVERT_SEP1_R
#define KEYPAD_ROW2_LVERT_SEP2_R REL_KEYPAD_BTNS_W(KP_LVERT_SEP1_L_PAD+2*KEYPAD_VERT_SEP_WIDTH)
#define KEYPAD_ROW2_LVERT_SEP2_T KEYPAD_ROW2_LVERT_SEP1_T
#define KEYPAD_ROW2_LVERT_SEP2_B KEYPAD_ROW2_LVERT_SEP1_B

#define KEYPAD_ROW2_RVERT_SEP1_L REL_KEYPAD_BTNS_W(KP_RVERT_SEP1_L_PAD)
#define KEYPAD_ROW2_RVERT_SEP1_R REL_KEYPAD_BTNS_W(KP_RVERT_SEP1_L_PAD+KEYPAD_VERT_SEP_WIDTH)
#define KEYPAD_ROW2_RVERT_SEP1_T KEYPAD_ROW2_LVERT_SEP1_T
#define KEYPAD_ROW2_RVERT_SEP1_B KEYPAD_ROW2_LVERT_SEP1_B

#define KEYPAD_ROW2_RVERT_SEP2_L KEYPAD_ROW2_RVERT_SEP1_R
#define KEYPAD_ROW2_RVERT_SEP2_R REL_KEYPAD_BTNS_W(KP_RVERT_SEP1_L_PAD+2*KEYPAD_VERT_SEP_WIDTH)
#define KEYPAD_ROW2_RVERT_SEP2_T KEYPAD_ROW2_LVERT_SEP1_T
#define KEYPAD_ROW2_RVERT_SEP2_B KEYPAD_ROW2_LVERT_SEP1_B

#define KEYPAD_ROW3_LVERT_SEP1_L REL_KEYPAD_BTNS_W(KP_LVERT_SEP1_L_PAD)
#define KEYPAD_ROW3_LVERT_SEP1_R REL_KEYPAD_BTNS_W(KP_LVERT_SEP1_L_PAD+KEYPAD_VERT_SEP_WIDTH)
#define KEYPAD_ROW3_LVERT_SEP1_T REL_KEYPAD_BTNS_H(KP_ROW3_VERT_SEP_T_PAD)
#define KEYPAD_ROW3_LVERT_SEP1_B REL_KEYPAD_BTNS_H(KP_ROW3_VERT_SEP_T_PAD+KEYPAD_VERT_SEP_HEIGHT)

#define KEYPAD_ROW3_LVERT_SEP2_L KEYPAD_ROW3_LVERT_SEP1_R
#define KEYPAD_ROW3_LVERT_SEP2_R REL_KEYPAD_BTNS_W(KP_LVERT_SEP1_L_PAD+2*KEYPAD_VERT_SEP_WIDTH)
#define KEYPAD_ROW3_LVERT_SEP2_T KEYPAD_ROW3_LVERT_SEP1_T
#define KEYPAD_ROW3_LVERT_SEP2_B KEYPAD_ROW3_LVERT_SEP1_B

#define KEYPAD_ROW3_RVERT_SEP1_L REL_KEYPAD_BTNS_W(KP_RVERT_SEP1_L_PAD)
#define KEYPAD_ROW3_RVERT_SEP1_R REL_KEYPAD_BTNS_W(KP_RVERT_SEP1_L_PAD+KEYPAD_VERT_SEP_WIDTH)
#define KEYPAD_ROW3_RVERT_SEP1_T KEYPAD_ROW3_LVERT_SEP1_T
#define KEYPAD_ROW3_RVERT_SEP1_B KEYPAD_ROW3_LVERT_SEP1_B

#define KEYPAD_ROW3_RVERT_SEP2_L KEYPAD_ROW3_RVERT_SEP1_R
#define KEYPAD_ROW3_RVERT_SEP2_R REL_KEYPAD_BTNS_W(KP_RVERT_SEP1_L_PAD+2*KEYPAD_VERT_SEP_WIDTH)
#define KEYPAD_ROW3_RVERT_SEP2_T KEYPAD_ROW3_LVERT_SEP1_T
#define KEYPAD_ROW3_RVERT_SEP2_B KEYPAD_ROW3_LVERT_SEP1_B

#define KEYPAD_ROW4_LVERT_SEP1_L REL_KEYPAD_BTNS_W(KP_LVERT_SEP1_L_PAD)
#define KEYPAD_ROW4_LVERT_SEP1_R REL_KEYPAD_BTNS_W(KP_LVERT_SEP1_L_PAD+KEYPAD_VERT_SEP_WIDTH)
#define KEYPAD_ROW4_LVERT_SEP1_T REL_KEYPAD_BTNS_H(KP_ROW4_VERT_SEP_T_PAD)
#define KEYPAD_ROW4_LVERT_SEP1_B REL_KEYPAD_BTNS_H(KP_ROW4_VERT_SEP_T_PAD+KEYPAD_VERT_SEP_HEIGHT)

#define KEYPAD_ROW4_LVERT_SEP2_L KEYPAD_ROW4_LVERT_SEP1_R
#define KEYPAD_ROW4_LVERT_SEP2_R REL_KEYPAD_BTNS_W(KP_LVERT_SEP1_L_PAD+2*KEYPAD_VERT_SEP_WIDTH)
#define KEYPAD_ROW4_LVERT_SEP2_T KEYPAD_ROW4_LVERT_SEP1_T
#define KEYPAD_ROW4_LVERT_SEP2_B KEYPAD_ROW4_LVERT_SEP1_B

#define KEYPAD_ROW4_RVERT_SEP1_L REL_KEYPAD_BTNS_W(KP_RVERT_SEP1_L_PAD)
#define KEYPAD_ROW4_RVERT_SEP1_R REL_KEYPAD_BTNS_W(KP_RVERT_SEP1_L_PAD+KEYPAD_VERT_SEP_WIDTH)
#define KEYPAD_ROW4_RVERT_SEP1_T KEYPAD_ROW4_LVERT_SEP1_T
#define KEYPAD_ROW4_RVERT_SEP1_B KEYPAD_ROW4_LVERT_SEP1_B

#define KEYPAD_ROW4_RVERT_SEP2_L KEYPAD_ROW4_RVERT_SEP1_R
#define KEYPAD_ROW4_RVERT_SEP2_R REL_KEYPAD_BTNS_W(KP_RVERT_SEP1_L_PAD+2*KEYPAD_VERT_SEP_WIDTH)
#define KEYPAD_ROW4_RVERT_SEP2_T KEYPAD_ROW4_LVERT_SEP1_T
#define KEYPAD_ROW4_RVERT_SEP2_B KEYPAD_ROW4_LVERT_SEP1_B

#define KEYPAD_ROW1_HORIZ_SEP1_L REL_KEYPAD_BTNS_W(KP_HORIZ_SEP_L_PAD)
#define KEYPAD_ROW1_HORIZ_SEP1_R REL_KEYPAD_BTNS_W(KP_HORIZ_SEP_L_PAD+KEYPAD_HORIZ_SEP_WIDTH)
#define KEYPAD_ROW1_HORIZ_SEP1_T REL_KEYPAD_BTNS_H(KP_ROW1_HORIZ_SEP_T_PAD)
#define KEYPAD_ROW1_HORIZ_SEP1_B REL_KEYPAD_BTNS_H(KP_ROW1_HORIZ_SEP_T_PAD+KEYPAD_HORIZ_SEP_HEIGHT)

#define KEYPAD_ROW1_HORIZ_SEP2_L KEYPAD_ROW1_HORIZ_SEP1_L
#define KEYPAD_ROW1_HORIZ_SEP2_R KEYPAD_ROW1_HORIZ_SEP1_R
#define KEYPAD_ROW1_HORIZ_SEP2_T KEYPAD_ROW1_HORIZ_SEP1_B
#define KEYPAD_ROW1_HORIZ_SEP2_B REL_KEYPAD_BTNS_H(KP_ROW1_HORIZ_SEP_T_PAD+2*KEYPAD_HORIZ_SEP_HEIGHT)

#define KEYPAD_ROW2_HORIZ_SEP1_L KEYPAD_ROW1_HORIZ_SEP1_L
#define KEYPAD_ROW2_HORIZ_SEP1_R KEYPAD_ROW1_HORIZ_SEP1_R
#define KEYPAD_ROW2_HORIZ_SEP1_T REL_KEYPAD_BTNS_H(KP_ROW2_HORIZ_SEP_T_PAD)
#define KEYPAD_ROW2_HORIZ_SEP1_B REL_KEYPAD_BTNS_H(KP_ROW2_HORIZ_SEP_T_PAD+KEYPAD_HORIZ_SEP_HEIGHT)

#define KEYPAD_ROW2_HORIZ_SEP2_L KEYPAD_ROW1_HORIZ_SEP1_L
#define KEYPAD_ROW2_HORIZ_SEP2_R KEYPAD_ROW1_HORIZ_SEP1_R
#define KEYPAD_ROW2_HORIZ_SEP2_T KEYPAD_ROW2_HORIZ_SEP1_B
#define KEYPAD_ROW2_HORIZ_SEP2_B REL_KEYPAD_BTNS_H(KP_ROW2_HORIZ_SEP_T_PAD+2*KEYPAD_HORIZ_SEP_HEIGHT)

#define KEYPAD_ROW3_HORIZ_SEP1_L KEYPAD_ROW1_HORIZ_SEP1_L
#define KEYPAD_ROW3_HORIZ_SEP1_R KEYPAD_ROW1_HORIZ_SEP1_R
#define KEYPAD_ROW3_HORIZ_SEP1_T REL_KEYPAD_BTNS_H(KP_ROW3_HORIZ_SEP_T_PAD)
#define KEYPAD_ROW3_HORIZ_SEP1_B REL_KEYPAD_BTNS_H(KP_ROW3_HORIZ_SEP_T_PAD+KEYPAD_HORIZ_SEP_HEIGHT)

#define KEYPAD_ROW3_HORIZ_SEP2_L KEYPAD_ROW1_HORIZ_SEP1_L
#define KEYPAD_ROW3_HORIZ_SEP2_R KEYPAD_ROW1_HORIZ_SEP1_R
#define KEYPAD_ROW3_HORIZ_SEP2_T KEYPAD_ROW3_HORIZ_SEP1_B
#define KEYPAD_ROW3_HORIZ_SEP2_B REL_KEYPAD_BTNS_H(KP_ROW3_HORIZ_SEP_T_PAD+2*KEYPAD_HORIZ_SEP_HEIGHT)
/*
 * End of KEYPAD View
 */


/*
 * INCALL View
 * In Portrait mode
 */
#define INCALL_CID_L DIALLING_CID_L
#define INCALL_CID_R DIALLING_CID_R
#define INCALL_CID_T DIALLING_CID_T
#define INCALL_CID_B DIALLING_CID_B

/*
#define INCALL_CID_DIM_T DIALLING_CID_T
#define INCALL_CID_DIM_B DIALLING_CID_B
#define INCALL_CID_DIM_L REL_W(145)
#define INCALL_CID_DIM_R REL_W(334)
*/

#define INCALL_BACKGROUND_CID_L DIALLING_BACKGROUND_CID_L
#define INCALL_BACKGROUND_CID_R DIALLING_BACKGROUND_CID_R
#define INCALL_BACKGROUND_CID_T DIALLING_BACKGROUND_CID_T
#define INCALL_BACKGROUND_CID_B DIALLING_BACKGROUND_CID_B

#define INCALL_EXTRA_VOL_ICON_L REL_W(INCALL_EXTRA_VOL_BTN_L_PAD)
#define INCALL_EXTRA_VOL_ICON_R REL_W(INCALL_EXTRA_VOL_BTN_L_PAD+INCALL_EXTRA_VOL_BTN_WIDTH)
#define INCALL_EXTRA_VOL_ICON_T REL_H(INCALL_EXTRA_VOL_BTN_T_PAD)
#define INCALL_EXTRA_VOL_ICON_B REL_H(INCALL_EXTRA_VOL_BTN_T_PAD+INCALL_EXTRA_VOL_BTN_HEIGHT)

#define INCALL_HOLD_L REL_W(INCALL_HOLD_BTN_L_PAD)
#define INCALL_HOLD_R REL_W(INCALL_HOLD_BTN_L_PAD+INCALL_HOLD_BTN_WIDTH)
#define INCALL_HOLD_T REL_H(INCALL_HOLD_BTN_T_PAD)
#define INCALL_HOLD_B REL_H(INCALL_HOLD_BTN_T_PAD+INCALL_HOLD_BTN_HEIGHT)

#define INCALL_HOLD_TXT_L REL_W(INCALL_HOLD_TXT_L_PAD)
#define INCALL_HOLD_TXT_R REL_W(INCALL_HOLD_TXT_L_PAD+INCALL_HOLD_TXT_WIDTH)
#define INCALL_HOLD_TXT_T REL_H(INCALL_HOLD_TXT_T_PAD)
#define INCALL_HOLD_TXT_B REL_H(INCALL_HOLD_TXT_T_PAD+INCALL_HOLD_TXT_HEIGHT)

#define INCALL_NOISE_ICON_L REL_W(INCALL_NOISE_ICN_L_PAD)
#define INCALL_NOISE_ICON_R REL_W(INCALL_NOISE_ICN_L_PAD+INCALL_NOISE_ICN_WIDTH)
#define INCALL_NOISE_ICON_T REL_H(INCALL_NOISE_ICN_T_PAD)
#define INCALL_NOISE_ICON_B REL_H(INCALL_NOISE_ICN_T_PAD+INCALL_NOISE_ICN_HEIGHT)

#define INCALL_SOUND_EQ_ICON_L REL_W(INCALL_SOUND_EQ_ICN_L_PAD)
#define INCALL_SOUND_EQ_ICON_R REL_W(INCALL_SOUND_EQ_ICN_L_PAD+INCALL_SOUND_EQ_ICN_WIDTH)
#define INCALL_SOUND_EQ_ICON_T REL_H(INCALL_SOUND_EQ_ICN_T_PAD)
#define INCALL_SOUND_EQ_ICON_B REL_H(INCALL_SOUND_EQ_ICN_T_PAD+INCALL_SOUND_EQ_ICN_HEIGHT)

/*
#define INCALL_RECORDER_T REL_H(389)
#define INCALL_RECORDER_B REL_H(443)
#define INCALL_RECORDER_L REL_W(381)
#define INCALL_RECORDER_R REL_W(454)

#define INCALL_RECORDING_T REL_H(359)
#define INCALL_RECORDING_B REL_H(383)
#define INCALL_RECORDING_L REL_W(381)
#define INCALL_RECORDING_R REL_W(454)
*/

#define INCALL_BACKGROUND_SHARE_L	REL_W(0)
#define INCALL_BACKGROUND_SHARE_R	REL_W(MAIN_SCREEN_W)
#define INCALL_BACKGROUND_SHARE_T	REL_H(INCALL_SHARE_BG_T_PAD)
#define INCALL_BACKGROUND_SHARE_B	REL_H(INCALL_SHARE_BG_T_PAD+INCALL_SHARE_BG_HEIGHT)
/*
 * End of INCALL View
 */


/*
 * MULTI-CALL SPLIT View
 * In Portrait mode
 */
/* L[ACT] + R[HLD] */
#define MULTICALL_SPLIT_BACKGROUND_CID_L INCALL_BACKGROUND_CID_L
#define MULTICALL_SPLIT_BACKGROUND_CID_R INCALL_BACKGROUND_CID_R
#define MULTICALL_SPLIT_BACKGROUND_CID_T INCALL_BACKGROUND_CID_T
#define MULTICALL_SPLIT_BACKGROUND_CID_B INCALL_BACKGROUND_CID_B

#define MULTICALL_SPLIT_CID_1_L REL_W(SPLIT_CID1_L_PAD)
#define MULTICALL_SPLIT_CID_1_R REL_W(SPLIT_CID1_L_PAD+SPLIT_CID1_WIDTH)
#define MULTICALL_SPLIT_CID_1_T REL_H(SPLIT_CID1_T_PAD)
#define MULTICALL_SPLIT_CID_1_B REL_H(SPLIT_CID1_T_PAD+SPLIT_CID1_HEIGHT)

#define MULTICALL_SPLIT_CID_2_L REL_W(SPLIT_CID2_L_PAD)
#define MULTICALL_SPLIT_CID_2_R REL_W(SPLIT_CID2_L_PAD+SPLIT_CID2_WIDTH)
#define MULTICALL_SPLIT_CID_2_T REL_H(SPLIT_CID2_T_PAD)
#define MULTICALL_SPLIT_CID_2_B REL_H(SPLIT_CID2_T_PAD+SPLIT_CID2_HEIGHT)

#define MULTICALL_SPLIT_ON_HOLD_TXT_L MULTICALL_SPLIT_CID_2_L
#define MULTICALL_SPLIT_ON_HOLD_TXT_R MULTICALL_SPLIT_CID_2_R
#define MULTICALL_SPLIT_ON_HOLD_TXT_T REL_H(SPLIT_ONHOLD_TXT_T_PAD)
#define MULTICALL_SPLIT_ON_HOLD_TXT_B REL_H(SPLIT_ONHOLD_TXT_T_PAD+SPLIT_ONHOLD_TXT_HEIGHT)

#define MULTICALL_SPLIT_ON_HOLD_TXT_WITH_ICON_L MULTICALL_SPLIT_CID_2_L
#define MULTICALL_SPLIT_ON_HOLD_TXT_WITH_ICON_R REL_W(SPLIT_CID2_L_PAD+SPLIT_CID2_WIDTH-SPLIT_MORE_BTN_WIDTH)
#define MULTICALL_SPLIT_ON_HOLD_TXT_WITH_ICON_T MULTICALL_SPLIT_ON_HOLD_TXT_T
#define MULTICALL_SPLIT_ON_HOLD_TXT_WITH_ICON_B MULTICALL_SPLIT_ON_HOLD_TXT_B

/*
 * End of MULTI-CALL SPLIT View
 */

/*
 * MULTI-CALL LIST View
 * In Portrait mode
 */
#define MULTICALL_LIST_L REL_W(0)
#define MULTICALL_LIST_R REL_W(MAIN_SCREEN_W)
#define MULTICALL_LIST_T REL_MULTI_LIST_H(CONF_LIST_T_PAD)
#define MULTICALL_LIST_B REL_MULTI_LIST_H(CONF_LIST_T_PAD+CONF_LIST_HEIGHT)

#define MULTICALL_LIST_HOLD_L REL_W(CONF_HOLD_L_PAD)
#define MULTICALL_LIST_HOLD_R REL_W(CONF_HOLD_L_PAD+CONF_HOLD_WIDTH)
#define MULTICALL_LIST_HOLD_T REL_MULTI_LIST_H(CONF_HOLD_T_PAD)
#define MULTICALL_LIST_HOLD_B REL_MULTI_LIST_H(CONF_HOLD_T_PAD+CONF_HOLD_HEIGHT)

#define MULTICALL_LIST_TIMER_L REL_W(0)
#define MULTICALL_LIST_TIMER_R REL_W(MAIN_SCREEN_W)
#define MULTICALL_LIST_TIMER_T REL_MULTI_LIST_H(CONF_TIMER_T_PAD)
#define MULTICALL_LIST_TIMER_B REL_MULTI_LIST_H(CONF_TIMER_T_PAD+CONF_TIMER_HEIGHT)

#define MULTICALL_LIST_BIG_END_L REL_W(CONF_CALL_BIG_END_L_PAD)
#define MULTICALL_LIST_BIG_END_R REL_W(CONF_CALL_BIG_END_L_PAD+CONF_CALL_BIG_END_WIDTH)
#define MULTICALL_LIST_BIG_END_T REL_MULTI_LIST_H(CONF_CALL_BIG_END_T_PAD)
#define MULTICALL_LIST_BIG_END_B REL_MULTI_LIST_H(CONF_CALL_BIG_END_T_PAD+CALL_BIG_END_HEIGHT)
/*
 * End of MULTI-CALL LIST View
 */


/*
 * Reject with MSG View
 * In Portrait mode
 */
#define REJECT_W_MSG_CREATE_NEW_L REL_W(REJ_MSG_NEW_BTN_L_PAD)
#define REJECT_W_MSG_CREATE_NEW_R REL_W(REJ_MSG_NEW_BTN_L_PAD+REJ_MSG_NEW_BTN_WIDTH)
#define REJECT_W_MSG_CREATE_NEW_T REL_H(REJ_MSG_NEW_BTN_T_PAD)
#define REJECT_W_MSG_CREATE_NEW_B REL_H(REJ_MSG_NEW_BTN_T_PAD+REJ_MSG_NEW_BTN_HEIGHT)
/*
#define REJECT_W_MSG_LIST_T REL_H(135)
#define REJECT_W_MSG_LIST_B REL_H(MAIN_SCREEN_H)
#define REJECT_W_MSG_LIST_L REL_W(0)
#define REJECT_W_MSG_LIST_R REL_W(MAIN_SCREEN_W)
*/
#define REJECT_W_MSG_LIST_L REL_NAVIFRAME_W(0)
#define REJECT_W_MSG_LIST_R REL_NAVIFRAME_W(MAIN_SCREEN_W)
#define REJECT_W_MSG_LIST_T REL_NAVIFRAME_H(REJ_MSG_LIST_T_PAD)
#define REJECT_W_MSG_LIST_B REL_NAVIFRAME_H(REJ_MSG_LIST_T_PAD+REJ_MSG_LIST_HEIGHT)
/*
 * End of Reject with MSG View
 */


/*
 * SIX BUTTON Layout
 * In Portrait mode
 */

#define	TOP_LEFT_BUTTON_L REL_BTN_LY_W(BTN_LAYOUT_LEFT_BTN_L_PAD)
#define	TOP_LEFT_BUTTON_R REL_BTN_LY_W(BTN_LAYOUT_LEFT_BTN_L_PAD+BTN_LAYOUT_SINGLE_BTN_WIDTH)
#define	TOP_LEFT_BUTTON_T REL_BTN_LY_H(BTN_LAYOUT_TOP_BTN_T_PAD)
#define	TOP_LEFT_BUTTON_B REL_BTN_LY_H(BTN_LAYOUT_TOP_BTN_T_PAD+BTN_LAYOUT_SINGLE_BTN_HEIGHT)

#define	TOP_MIDDLE_BUTTON_L REL_BTN_LY_W(BTN_LAYOUT_MIDDLE_BTN_L_PAD)
#define	TOP_MIDDLE_BUTTON_R REL_BTN_LY_W(BTN_LAYOUT_MIDDLE_BTN_L_PAD+BTN_LAYOUT_SINGLE_BTN_WIDTH)
#define	TOP_MIDDLE_BUTTON_T TOP_LEFT_BUTTON_T
#define	TOP_MIDDLE_BUTTON_B TOP_LEFT_BUTTON_B

#define	TOP_RIGHT_BUTTON_L REL_BTN_LY_W(BTN_LAYOUT_RIGHT_BTN_L_PAD)
#define	TOP_RIGHT_BUTTON_R REL_BTN_LY_W(BTN_LAYOUT_RIGHT_BTN_L_PAD+BTN_LAYOUT_SINGLE_BTN_WIDTH)
#define	TOP_RIGHT_BUTTON_T TOP_LEFT_BUTTON_T
#define	TOP_RIGHT_BUTTON_B TOP_LEFT_BUTTON_B

#define	BOTTOM_LEFT_BUTTON_L TOP_LEFT_BUTTON_L
#define	BOTTOM_LEFT_BUTTON_R TOP_LEFT_BUTTON_R
#define	BOTTOM_LEFT_BUTTON_T REL_BTN_LY_H(BTN_LAYOUT_BOTTOM_BTN_T_PAD)
#define	BOTTOM_LEFT_BUTTON_B REL_BTN_LY_H(BTN_LAYOUT_BOTTOM_BTN_T_PAD+BTN_LAYOUT_SINGLE_BTN_HEIGHT)

#define	BOTTOM_MIDDLE_BUTTON_L TOP_MIDDLE_BUTTON_L
#define	BOTTOM_MIDDLE_BUTTON_R TOP_MIDDLE_BUTTON_R
#define	BOTTOM_MIDDLE_BUTTON_T BOTTOM_LEFT_BUTTON_T
#define	BOTTOM_MIDDLE_BUTTON_B BOTTOM_LEFT_BUTTON_B

#define	BOTTOM_RIGHT_BUTTON_L TOP_RIGHT_BUTTON_L
#define	BOTTOM_RIGHT_BUTTON_R TOP_RIGHT_BUTTON_R
#define	BOTTOM_RIGHT_BUTTON_T BOTTOM_LEFT_BUTTON_T
#define	BOTTOM_RIGHT_BUTTON_B BOTTOM_LEFT_BUTTON_B

#define TOPLINE_LEFT_VERT_SEP_1_L REL_BTN_LY_W(LEFT_VERT_SEP_L_PAD)
#define TOPLINE_LEFT_VERT_SEP_1_R REL_BTN_LY_W(LEFT_VERT_SEP_L_PAD+SEPARTOR_WIDTH)
#define TOPLINE_LEFT_VERT_SEP_1_T REL_BTN_LY_H(TOP_VERT_SEP_T_PAD)
#define TOPLINE_LEFT_VERT_SEP_1_B REL_BTN_LY_H(TOP_VERT_SEP_T_PAD+VERT_SEP_HEIGHT)

#define TOPLINE_LEFT_VERT_SEP_2_L TOPLINE_LEFT_VERT_SEP_1_R
#define TOPLINE_LEFT_VERT_SEP_2_R REL_BTN_LY_W(LEFT_VERT_SEP_L_PAD+2*SEPARTOR_WIDTH)
#define TOPLINE_LEFT_VERT_SEP_2_T TOPLINE_LEFT_VERT_SEP_1_T
#define TOPLINE_LEFT_VERT_SEP_2_B TOPLINE_LEFT_VERT_SEP_1_B

#define TOPLINE_RIGHT_VERT_SEP_1_L REL_BTN_LY_W(RIGHT_VERT_SEP_L_PAD)
#define TOPLINE_RIGHT_VERT_SEP_1_R REL_BTN_LY_W(RIGHT_VERT_SEP_L_PAD+SEPARTOR_WIDTH)
#define TOPLINE_RIGHT_VERT_SEP_1_T TOPLINE_LEFT_VERT_SEP_1_T
#define TOPLINE_RIGHT_VERT_SEP_1_B TOPLINE_LEFT_VERT_SEP_1_B

#define TOPLINE_RIGHT_VERT_SEP_2_L TOPLINE_RIGHT_VERT_SEP_1_R
#define TOPLINE_RIGHT_VERT_SEP_2_R REL_BTN_LY_W(RIGHT_VERT_SEP_L_PAD+2*SEPARTOR_WIDTH)
#define TOPLINE_RIGHT_VERT_SEP_2_T TOPLINE_RIGHT_VERT_SEP_1_T
#define TOPLINE_RIGHT_VERT_SEP_2_B TOPLINE_RIGHT_VERT_SEP_1_B

#define BOTLINE_LEFT_VERT_SEP_1_L TOPLINE_LEFT_VERT_SEP_1_L
#define BOTLINE_LEFT_VERT_SEP_1_R TOPLINE_LEFT_VERT_SEP_1_R
#define BOTLINE_LEFT_VERT_SEP_1_T REL_BTN_LY_H(BOTTOM_VERT_SEP_T_PAD)
#define BOTLINE_LEFT_VERT_SEP_1_B REL_BTN_LY_H(BOTTOM_VERT_SEP_T_PAD+VERT_SEP_HEIGHT)

#define BOTLINE_LEFT_VERT_SEP_2_L TOPLINE_LEFT_VERT_SEP_2_L
#define BOTLINE_LEFT_VERT_SEP_2_R TOPLINE_LEFT_VERT_SEP_2_R
#define BOTLINE_LEFT_VERT_SEP_2_T BOTLINE_LEFT_VERT_SEP_1_T
#define BOTLINE_LEFT_VERT_SEP_2_B BOTLINE_LEFT_VERT_SEP_1_B

#define BOTLINE_RIGHT_VERT_SEP_1_L TOPLINE_RIGHT_VERT_SEP_1_L
#define BOTLINE_RIGHT_VERT_SEP_1_R TOPLINE_RIGHT_VERT_SEP_1_R
#define BOTLINE_RIGHT_VERT_SEP_1_T BOTLINE_LEFT_VERT_SEP_1_T
#define BOTLINE_RIGHT_VERT_SEP_1_B BOTLINE_LEFT_VERT_SEP_1_B

#define BOTLINE_RIGHT_VERT_SEP_2_L BOTLINE_RIGHT_VERT_SEP_1_R
#define BOTLINE_RIGHT_VERT_SEP_2_R TOPLINE_RIGHT_VERT_SEP_2_R
#define BOTLINE_RIGHT_VERT_SEP_2_T BOTLINE_LEFT_VERT_SEP_1_T
#define BOTLINE_RIGHT_VERT_SEP_2_B BOTLINE_LEFT_VERT_SEP_1_T

#define TOPLINE_HORIZ_SEP_1_L REL_BTN_LY_W(HORIZ_SEP_L_PAD)
#define TOPLINE_HORIZ_SEP_1_R REL_BTN_LY_W(HORIZ_SEP_L_PAD+HORIZ_SEP_WIDTH)
#define TOPLINE_HORIZ_SEP_1_T REL_BTN_LY_H(TOP_HORIZ_SEP_T_PAD)
#define TOPLINE_HORIZ_SEP_1_B REL_BTN_LY_H(TOP_HORIZ_SEP_T_PAD+SEPARTOR_WIDTH)

#define TOPLINE_HORIZ_SEP_2_L TOPLINE_HORIZ_SEP_1_L
#define TOPLINE_HORIZ_SEP_2_R TOPLINE_HORIZ_SEP_1_R
#define TOPLINE_HORIZ_SEP_2_T TOPLINE_HORIZ_SEP_1_B
#define TOPLINE_HORIZ_SEP_2_B REL_BTN_LY_H(TOP_HORIZ_SEP_T_PAD+2*SEPARTOR_WIDTH)

#define BOTLINE_HORIZ_SEP_1_L TOPLINE_HORIZ_SEP_1_L
#define BOTLINE_HORIZ_SEP_1_R TOPLINE_HORIZ_SEP_1_R
#define BOTLINE_HORIZ_SEP_1_T REL_BTN_LY_H(BOTTOM_HORIZ_SEP_T_PAD)
#define BOTLINE_HORIZ_SEP_1_B REL_BTN_LY_H(BOTTOM_HORIZ_SEP_T_PAD+SEPARTOR_WIDTH)

#define BOTLINE_HORIZ_SEP_2_L TOPLINE_HORIZ_SEP_1_L
#define BOTLINE_HORIZ_SEP_2_R TOPLINE_HORIZ_SEP_1_R
#define BOTLINE_HORIZ_SEP_2_T BOTLINE_HORIZ_SEP_1_B
#define BOTLINE_HORIZ_SEP_2_B REL_BTN_LY_H(BOTTOM_HORIZ_SEP_T_PAD+2*SEPARTOR_WIDTH)
/*
 * End of SIX Button Layout
 */

/*
 * THREE BUTTON Layout for ENDCALL
 * In Portrait mode
 */
#define ENDCALL_LEFT_VERT_SEP_1_L REL_THREE_BTN_LY_W(ENDCALL_LEFT_VERT_SEP_L_PAD)
#define ENDCALL_LEFT_VERT_SEP_1_R REL_THREE_BTN_LY_W(ENDCALL_LEFT_VERT_SEP_L_PAD+ENDCALL_SEPARTOR_WIDTH)
#define ENDCALL_LEFT_VERT_SEP_1_T REL_THREE_BTN_LY_H(ENDCALL_VERT_SEP_T_PAD)
#define ENDCALL_LEFT_VERT_SEP_1_B REL_THREE_BTN_LY_H(ENDCALL_VERT_SEP_T_PAD+ENDCALL_VERT_SEP_HEIGHT)

#define ENDCALL_LEFT_VERT_SEP_2_L ENDCALL_LEFT_VERT_SEP_1_R
#define ENDCALL_LEFT_VERT_SEP_2_R REL_THREE_BTN_LY_W(ENDCALL_LEFT_VERT_SEP_L_PAD+2*ENDCALL_SEPARTOR_WIDTH)
#define ENDCALL_LEFT_VERT_SEP_2_T ENDCALL_LEFT_VERT_SEP_1_T
#define ENDCALL_LEFT_VERT_SEP_2_B ENDCALL_LEFT_VERT_SEP_1_B

#define ENDCALL_RIGHT_VERT_SEP_1_L REL_THREE_BTN_LY_W(ENDCALL_RIGHT_VERT_SEP_L_PAD)
#define ENDCALL_RIGHT_VERT_SEP_1_R REL_THREE_BTN_LY_W(ENDCALL_RIGHT_VERT_SEP_L_PAD+ENDCALL_SEPARTOR_WIDTH)
#define ENDCALL_RIGHT_VERT_SEP_1_T ENDCALL_LEFT_VERT_SEP_1_T
#define ENDCALL_RIGHT_VERT_SEP_1_B ENDCALL_LEFT_VERT_SEP_1_B

#define ENDCALL_RIGHT_VERT_SEP_2_L ENDCALL_RIGHT_VERT_SEP_1_R
#define ENDCALL_RIGHT_VERT_SEP_2_R REL_THREE_BTN_LY_W(ENDCALL_RIGHT_VERT_SEP_L_PAD+2*ENDCALL_SEPARTOR_WIDTH)
#define ENDCALL_RIGHT_VERT_SEP_2_T ENDCALL_LEFT_VERT_SEP_1_T
#define ENDCALL_RIGHT_VERT_SEP_2_B ENDCALL_LEFT_VERT_SEP_1_B
/*
 * End of THREE Button Layout
 */

/*
 * General Button Layout
 */
#define SIX_BTN_LAYOUT_L REL_W(SIX_BTN_LAYOUT_L_PAD)
#define SIX_BTN_LAYOUT_R REL_W(SIX_BTN_LAYOUT_L_PAD+SIX_BTN_LAYOUT_WIDTH)
#define SIX_BTN_LAYOUT_T REL_H(SIX_BTN_LAYOUT_T_PAD)
#define SIX_BTN_LAYOUT_B REL_H(SIX_BTN_LAYOUT_T_PAD+SIX_BTN_LAYOUT_HEIGHT)

#define SIX_BTN_BIG_END_L REL_W(CALL_BIG_END_L_PAD)
#define SIX_BTN_BIG_END_R REL_W(CALL_BIG_END_L_PAD+CALL_BIG_END_WIDTH)
#define SIX_BTN_BIG_END_T REL_H(CALL_BIG_END_T_PAD)
#define SIX_BTN_BIG_END_B REL_H(CALL_BIG_END_T_PAD+CALL_BIG_END_HEIGHT)

#define SIX_BTN_INCOMING_1_L SIX_BTN_BIG_END_L
#define SIX_BTN_INCOMING_1_R SIX_BTN_BIG_END_R
#define SIX_BTN_INCOMING_1_T REL_H(INCMG_CALL_BTN1_T_PAD)
#define SIX_BTN_INCOMING_1_B REL_H(INCMG_CALL_BTN1_T_PAD+INCMG_CALL_BTN_HEIGHT)

#define SIX_BTN_INCOMING_2_L SIX_BTN_BIG_END_L
#define SIX_BTN_INCOMING_2_R SIX_BTN_BIG_END_R
#define SIX_BTN_INCOMING_2_T REL_H(INCMG_CALL_BTN2_T_PAD)
#define SIX_BTN_INCOMING_2_B REL_H(INCMG_CALL_BTN2_T_PAD+INCMG_CALL_BTN_HEIGHT)

#define SIX_BTN_INCOMING_3_L SIX_BTN_BIG_END_L
#define SIX_BTN_INCOMING_3_R SIX_BTN_BIG_END_R
#define SIX_BTN_INCOMING_3_T REL_H(INCMG_CALL_BTN3_T_PAD)
#define SIX_BTN_INCOMING_3_B REL_H(INCMG_CALL_BTN3_T_PAD+INCMG_CALL_BTN_HEIGHT)
/*
 * End of SIX Button Layout
 */


/*
 * Navigation bar layout
 */
#define CALL_NAVIGATION_BAR_T REL_H(NAVIFRAME_T_PAD)
#define CALL_NAVIGATION_BAR_B REL_H(MAIN_SCREEN_H)
#define CALL_NAVIGATION_BAR_L REL_W(0)
#define CALL_NAVIGATION_BAR_R REL_W(MAIN_SCREEN_W)
/*
 * End of Navigation bar layout
 */


/*
 * END CALL View
 * In Portrait mode
 */
#define	ENDSINGLECALL_BACKGROUND_CID_L DIALLING_BACKGROUND_CID_L
#define	ENDSINGLECALL_BACKGROUND_CID_R DIALLING_BACKGROUND_CID_R
#define	ENDSINGLECALL_BACKGROUND_CID_T DIALLING_BACKGROUND_CID_T
#define	ENDSINGLECALL_BACKGROUND_CID_B DIALLING_BACKGROUND_CID_B

#define ENDSINGLECALL_CID_L ENDCALL_DIALLING_CID_L
#define ENDSINGLECALL_CID_R ENDCALL_DIALLING_CID_R
#define ENDSINGLECALL_CID_T ENDCALL_DIALLING_CID_T
#define ENDSINGLECALL_CID_B ENDCALL_DIALLING_CID_B

#define ENDSINGLECALL_BTN_BG_L ENDCALL_DIALLING_BTN_BG_L
#define ENDSINGLECALL_BTN_BG_R ENDCALL_DIALLING_BTN_BG_R
#define ENDSINGLECALL_BTN_BG_T ENDCALL_DIALLING_BTN_BG_T
#define ENDSINGLECALL_BTN_BG_B ENDCALL_DIALLING_BTN_BG_B

#define	ENDSINGLECALL_VOICE_BTN_L REL_W(ENDCALL_VOICE_BTN_L_PAD)
#define	ENDSINGLECALL_VOICE_BTN_R REL_W(ENDCALL_VOICE_BTN_L_PAD+ENDCALL_VOICE_BTN_WIDTH)
#define	ENDSINGLECALL_VOICE_BTN_T REL_H(ENDCALL_VOICE_BTN_T_PAD)
#define	ENDSINGLECALL_VOICE_BTN_B REL_H(ENDCALL_VOICE_BTN_T_PAD+ENDCALL_VOICE_BTN_HEIGHT)

#define	ENDSINGLECALL_VIDEO_BTN_L REL_W(ENDCALL_VIDEO_BTN_L_PAD)
#define	ENDSINGLECALL_VIDEO_BTN_R REL_W(ENDCALL_VIDEO_BTN_L_PAD+ENDCALL_VOICE_BTN_WIDTH)
#define	ENDSINGLECALL_VIDEO_BTN_T ENDSINGLECALL_VOICE_BTN_T
#define	ENDSINGLECALL_VIDEO_BTN_B ENDSINGLECALL_VOICE_BTN_B

#define	ENDSINGLECALL_MSG_BTN_L REL_W(ENDCALL_MSG_BTN_L_PAD)
#define	ENDSINGLECALL_MSG_BTN_R REL_W(ENDCALL_MSG_BTN_L_PAD+ENDCALL_VOICE_BTN_WIDTH)
#define	ENDSINGLECALL_MSG_BTN_T ENDSINGLECALL_VOICE_BTN_T
#define	ENDSINGLECALL_MSG_BTN_B ENDSINGLECALL_VOICE_BTN_B

#define	ENDSINGLECALL_CONTACT_BTN_L REL_W(ENDCALL_CONTACT_BTN_L_PAD)
#define	ENDSINGLECALL_CONTACT_BTN_R REL_W(ENDCALL_CONTACT_BTN_L_PAD+ENDCALL_CONTACT_BTN_WIDTH)
#define	ENDSINGLECALL_CONTACT_BTN_T REL_H(ENDCALL_CONTACT_BTN_T_PAD)
#define	ENDSINGLECALL_CONTACT_BTN_B REL_H(ENDCALL_CONTACT_BTN_T_PAD+ENDCALL_CONTACT_BTN_HEIGHT)
/*
 * End of END CALL View
 */


/*
 * QUICK-PANEL layout
 * In Portrait mode
 */
#define	CALL_QUICKPANEL_CID_L REL_QP_W(QP_CID_L_PAD)
#define	CALL_QUICKPANEL_CID_R REL_QP_W(QP_CID_L_PAD+QP_CID_WIDTH)
#define	CALL_QUICKPANEL_CID_T REL_QP_H(QP_CID_T_PAD)
#define	CALL_QUICKPANEL_CID_B REL_QP_H(QP_CID_T_PAD+QP_CID_HEIGHT)

#define	CALL_QUICKPANEL_BTN_MUTE_L REL_QP_W(QP_MUTE_BTN_L_PAD)
#define	CALL_QUICKPANEL_BTN_MUTE_R REL_QP_W(QP_MUTE_BTN_L_PAD+QP_END_BTN_WIDTH)
#define	CALL_QUICKPANEL_BTN_MUTE_T REL_QP_H(QP_MUTE_BTN_T_PAD)
#define	CALL_QUICKPANEL_BTN_MUTE_B REL_QP_H(QP_MUTE_BTN_T_PAD+QP_END_BTN_HEIGHT)

#define	CALL_QUICKPANEL_BTN_END_L REL_QP_W(QP_END_BTN_L_PAD)
#define	CALL_QUICKPANEL_BTN_END_R REL_QP_W(QP_END_BTN_L_PAD+QP_END_BTN_WIDTH)
#define	CALL_QUICKPANEL_BTN_END_T REL_QP_H(QP_END_BTN_T_PAD)
#define	CALL_QUICKPANEL_BTN_END_B REL_QP_H(QP_END_BTN_T_PAD+QP_END_BTN_HEIGHT)

#define	CALL_QUICKPANEL_NAME_L REL_QP_W(QP_NAME_L_PAD)
#define	CALL_QUICKPANEL_NAME_R REL_QP_W(QP_NAME_L_PAD+QP_NAME_WIDTH)
#define	CALL_QUICKPANEL_NAME_T REL_QP_H(QP_NAME_T_PAD)
#define	CALL_QUICKPANEL_NAME_B REL_QP_H(QP_NAME_T_PAD+QP_NAME_HEIGHT)
/*
 * End of QUICK-PANEL layout
 */


/*
 * NBEAT-HD GUI Widget Dimensions
 * In Landscape mode
 */
#define MAIN_SCREEN_LSCAPE_W 1280
#define MAIN_SCREEN_LSCAPE_H 720

#define	LSCAPE_TITLE_T_PAD 50
#define	LSCAPE_TITLE_HEIGHT 100

#define	LSCAPE_BODY_BG_T_PAD (LSCAPE_TITLE_T_PAD+LSCAPE_TITLE_HEIGHT)

#define	LSCAPE_SCROLLER_WIDTH (266*5+30*2) /*CID(266) Gap(30)*/
#define	LSCAPE_SCROLLER_HEIGHT 388

/*CID Data*/
#define LSCAPE_CID_WIDTH 266
#define LSCAPE_CID_HEIGHT 348

#define	FIRST_CID_OUTER_BG_POS1_L_PAD 30
#define	FIRST_CID_OUTER_BG_POS2_L_PAD 108
#define	FIRST_CID_OUTER_BG_POS3_L_PAD 241
#define	FIRST_CID_OUTER_BG_POS4_L_PAD 374
#define	CID_OUTER_BG_WIDTH LSCAPE_CID_WIDTH
#define	CID_OUTER_BG_T_PAD 30
#define	CID_OUTER_BG_HEIGHT LSCAPE_CID_HEIGHT

#define CID_INNER_BG_L_PAD 20
#define CID_INNER_BG_WIDTH 226
#define CID_INNER_BG_T_PAD 0
#define CID_INNER_BG_HEIGHT (CID_OUTER_BG_HEIGHT-20)

#define CID_END_L_PAD (CID_OUTER_BG_WIDTH-60)
#define CID_END_WIDTH 60
#define CID_END_T_PAD (-20)
#define CID_END_HEIGHT 60

#define CID_NAME_T_PAD 18
#define CID_NAME_HEIGHT 40

#define CID_IMG_L_PAD 42
#define CID_IMG_WIDTH 182
#define CID_IMG_T_PAD 66
#define CID_IMG_HEIGHT 182

#define CID_SPLIT_L_PAD 32
#define CID_SPLIT_WIDTH 202
#define CID_SPLIT_T_PAD 256
#define CID_SPLIT_HEIGHT 60

#define LSCAPE_HOLD_L_PAD 24
#define LSCAPE_HOLD_WIDTH 60
#define LSCAPE_HOLD_T_PAD (LSCAPE_TITLE_T_PAD+LSCAPE_TITLE_HEIGHT+LSCAPE_SCROLLER_HEIGHT)
#define LSCAPE_HOLD_HEIGHT 60

#define LSCAPE_TIMER_WIDTH 1232

#define LSCAPE_BIG_END_T_PAD (LSCAPE_HOLD_T_PAD+LSCAPE_HOLD_HEIGHT+26)
#define LSCAPE_BIG_END_HEIGHT 80

#define LSCAPE_SPLIT_CID1_L_PAD 307
#define LSCAPE_SPLIT_CID1_WIDTH 304
#define LSCAPE_SPLIT_CID1_T_PAD 182
#define LSCAPE_SPLIT_CID1_HEIGHT 304

#define LSCAPE_SPLIT_PAUSE_L_PAD (LSCAPE_SPLIT_CID1_L_PAD+8)
#define LSCAPE_SPLIT_PAUSE_WIDTH 62
#define LSCAPE_SPLIT_PAUSE_HEIGHT 62
#define LSCAPE_SPLIT_PAUSE_T_PAD (LSCAPE_SPLIT_CID1_T_PAD+LSCAPE_SPLIT_CID1_HEIGHT-8-LSCAPE_SPLIT_PAUSE_HEIGHT)

#define LSCAPE_SPLIT_CID2_L_PAD (LSCAPE_SPLIT_CID1_L_PAD+LSCAPE_SPLIT_CID1_WIDTH+142)
#define LSCAPE_SPLIT_CID2_WIDTH 208
#define LSCAPE_SPLIT_CID2_T_PAD 230
#define LSCAPE_SPLIT_CID2_HEIGHT 208

#define LSCAPE_SPLIT_PLAY_L_PAD (LSCAPE_SPLIT_CID2_L_PAD+12)
#define LSCAPE_SPLIT_PLAY_WIDTH 40
#define LSCAPE_SPLIT_PLAY_HEIGHT 40
#define LSCAPE_SPLIT_PLAY_T_PAD (LSCAPE_SPLIT_CID2_T_PAD+LSCAPE_SPLIT_CID2_HEIGHT-12-LSCAPE_SPLIT_PLAY_HEIGHT)

#define LSCAPE_SPLIT_NAME1_L_PAD (LSCAPE_SPLIT_CID1_L_PAD-37)
#define LSCAPE_SPLIT_NAME1_WIDTH 390
#define LSCAPE_SPLIT_NAME1_T_PAD 108
#define LSCAPE_SPLIT_NAME1_HEIGHT 58

#define LSCAPE_SPLIT_NAME2_L_PAD (LSCAPE_SPLIT_CID2_L_PAD-21)
#define LSCAPE_SPLIT_NAME2_WIDTH 250
#define LSCAPE_SPLIT_NAME2_T_PAD 180
#define LSCAPE_SPLIT_NAME2_HEIGHT 40

#define LSCAPE_SPLIT_TIMER_T_PAD 512
#define LSCAPE_SPLIT_TIMER_HEIGHT 46

#define LSCAPE_SPLIT_MORE_BTN_WIDTH 40
#define LSCAPE_SPLIT_MORE_BTN_L_PAD (LSCAPE_SPLIT_CID2_L_PAD+LSCAPE_SPLIT_CID2_WIDTH-LSCAPE_SPLIT_MORE_BTN_WIDTH)
#define LSCAPE_SPLIT_ONHOLD_TXT_W_ICON_WIDTH (LSCAPE_SPLIT_CID2_WIDTH-LSCAPE_SPLIT_MORE_BTN_WIDTH)
#define	LSCAPE_SPLIT_ONHOLD_TXT_T_PAD 456
#define	LSCAPE_SPLIT_ONHOLD_TXT_HEIGHT 40

#define	LSCAPE_SPLIT_SWAP_CID1_L_PAD 307
#define LSCAPE_SPLIT_SWAP_CID1_WIDTH 208

#define	LSCAPE_SPLIT_SWAP_PLAY_L_PAD (LSCAPE_SPLIT_SWAP_CID1_L_PAD+12)
#define LSCAPE_SPLIT_SWAP_PLAY_WIDTH 40

#define	LSCAPE_SPLIT_SWAP_CID2_L_PAD (LSCAPE_SPLIT_SWAP_CID1_L_PAD+LSCAPE_SPLIT_SWAP_CID1_WIDTH+142)
#define LSCAPE_SPLIT_SWAP_CID2_WIDTH 304

#define	LSCAPE_SPLIT_SWAP_PAUSE_L_PAD (LSCAPE_SPLIT_SWAP_CID2_L_PAD+8)
#define LSCAPE_SPLIT_SWAP_PAUSE_WIDTH 62

#define	LSCAPE_SPLIT_SWAP_NAME1_L_PAD (LSCAPE_SPLIT_CID1_L_PAD-21)
#define LSCAPE_SPLIT_SWAP_NAME1_WIDTH 250

#define	LSCAPE_SPLIT_SWAP_NAME2_L_PAD (LSCAPE_SPLIT_SWAP_CID2_L_PAD-37)
#define LSCAPE_SPLIT_SWAP_NAME2_WIDTH 390

#define LSCAPE_SPLIT_SWAP_MORE_BTN_WIDTH 60
#define LSCAPE_SPLIT_SWAP_MORE_BTN_L_PAD (LSCAPE_SPLIT_SWAP_CID2_L_PAD+LSCAPE_SPLIT_SWAP_CID2_WIDTH-LSCAPE_SPLIT_SWAP_MORE_BTN_WIDTH)
#define LSCAPE_SPLIT_SWAP_MORE_BTN_T_PAD (LSCAPE_SPLIT_TIMER_T_PAD-7)
#define LSCAPE_SPLIT_SWAP_MORE_BTN_HEIGHT 60
#define LSCAPE_SPLIT_TIMER_TXT_W_ICON_WIDTH (LSCAPE_SPLIT_SWAP_CID2_WIDTH-LSCAPE_SPLIT_SWAP_MORE_BTN_WIDTH)

#define LSCAPE_SPLIT_JOIN_BTN_L_PAD 40
#define LSCAPE_SPLIT_JOIN_BTN_WIDTH 584
#define LSCAPE_SPLIT_JOIN_BTN_T_PAD 614
#define LSCAPE_SPLIT_JOIN_BTN_HEIGHT 80

#define LSCAPE_SPLIT_BIG_END_BTN_L_PAD (LSCAPE_SPLIT_JOIN_BTN_L_PAD+LSCAPE_SPLIT_JOIN_BTN_WIDTH+32)
#define LSCAPE_SPLIT_BIG_END_BTN_WIDTH LSCAPE_SPLIT_JOIN_BTN_WIDTH

#define LSCAPE_QP_WIN_W MAIN_SCREEN_LSCAPE_W
#define LSCAPE_QP_WIN_H 170

#define LSCAPE_QP_CID_L_PAD 20
#define LSCAPE_QP_CID_WIDTH 105
#define LSCAPE_QP_CID_T_PAD 32
#define LSCAPE_QP_CID_HEIGHT 105

#define LSCAPE_QP_MUTE_BTN_L_PAD 338
#define LSCAPE_QP_MUTE_BTN_WIDTH 368
#define LSCAPE_QP_MUTE_BTN_T_PAD 78
#define LSCAPE_QP_MUTE_BTN_HEIGHT 74

#define LSCAPE_QP_END_BTN_L_PAD 726
#define LSCAPE_QP_END_BTN_WIDTH 367
#define LSCAPE_QP_END_BTN_T_PAD LSCAPE_QP_MUTE_BTN_T_PAD
#define LSCAPE_QP_END_BTN_HEIGHT LSCAPE_QP_MUTE_BTN_HEIGHT

#define LSCAPE_QP_NAME_L_PAD LSCAPE_QP_MUTE_BTN_L_PAD
#define LSCAPE_QP_NAME_WIDTH 922
#define LSCAPE_QP_NAME_T_PAD 22
#define LSCAPE_QP_NAME_HEIGHT 36

/*
 * End of NBEAT-HD GUI Widget Dimensions
 */


/*
 * Relative positions
 * In Landscape mode
 */
#define REL_LSCAPE_W(x) ((x)/MAIN_SCREEN_LSCAPE_W)
#define REL_LSCAPE_H(y) ((y)/MAIN_SCREEN_LSCAPE_H)

#define	REL_SCROLLER_W(x) ((x)/LSCAPE_SCROLLER_WIDTH)
#define	REL_SCROLLER_H(y) ((y)/LSCAPE_SCROLLER_HEIGHT)

#define	REL_LSCAPE_CID_W(x) ((x)/LSCAPE_CID_WIDTH)
#define	REL_LSCAPE_CID_H(y) ((y)/LSCAPE_CID_HEIGHT)

/* Relative X & Y positions of widgets w.r.t. Quick-panel layout */
#define REL_LSCAPE_QP_W(x) ((x)/LSCAPE_QP_WIN_W)
#define REL_LSCAPE_QP_H(y) ((y)/LSCAPE_QP_WIN_H)

/*
 * End of Relative positions
 */


/*
 * MULTI-CALL CONF View
 * In Landscape mode
 */
/*
#define INCALL_LANDSCAPE_BACKGROUND_CID_L REL_LSCAPE_W(0)
#define INCALL_LANDSCAPE_BACKGROUND_CID_R REL_LSCAPE_W(MAIN_SCREEN_H)
#define INCALL_LANDSCAPE_BACKGROUND_CID_T REL_LSCAPE_H(0)
#define INCALL_LANDSCAPE_BACKGROUND_CID_B REL_LSCAPE_H(MAIN_SCREEN_W)
*/

#define	INCALL_LANDSCAPE_TITLE_BG_L REL_LSCAPE_W(0)
#define	INCALL_LANDSCAPE_TITLE_BG_R REL_LSCAPE_W(MAIN_SCREEN_LSCAPE_W)
#define	INCALL_LANDSCAPE_TITLE_BG_T REL_LSCAPE_H(LSCAPE_TITLE_T_PAD)
#define	INCALL_LANDSCAPE_TITLE_BG_B REL_LSCAPE_H(LSCAPE_TITLE_T_PAD+LSCAPE_TITLE_HEIGHT)

#define	INCALL_LANDSCAPE_TITLE_TXT_L INCALL_LANDSCAPE_TITLE_BG_L
#define	INCALL_LANDSCAPE_TITLE_TXT_R INCALL_LANDSCAPE_TITLE_BG_R
#define	INCALL_LANDSCAPE_TITLE_TXT_T INCALL_LANDSCAPE_TITLE_BG_T
#define	INCALL_LANDSCAPE_TITLE_TXT_B INCALL_LANDSCAPE_TITLE_BG_B

/*
#define	INCALL_LANDSCAPE_SEPARATOR_L REL_LSCAPE_W(0)
#define	INCALL_LANDSCAPE_SEPARATOR_R REL_LSCAPE_W(MAIN_SCREEN_LSCAPE_W)
#define	INCALL_LANDSCAPE_SEPARATOR_T REL_LSCAPE_H(50)
#define	INCALL_LANDSCAPE_SEPARATOR_B REL_LSCAPE_H(55)
*/

#define	INCALL_LANDSCAPE_BODY_BG_L REL_LSCAPE_W(0)
#define	INCALL_LANDSCAPE_BODY_BG_R REL_LSCAPE_W(MAIN_SCREEN_LSCAPE_W)
#define	INCALL_LANDSCAPE_BODY_BG_T REL_LSCAPE_H(LSCAPE_BODY_BG_T_PAD)
#define	INCALL_LANDSCAPE_BODY_BG_B REL_LSCAPE_H(MAIN_SCREEN_LSCAPE_H)

#define	INCALL_LANDSCAPE_SCROLLER_L REL_LSCAPE_W(0)
#define	INCALL_LANDSCAPE_SCROLLER_R REL_LSCAPE_W(MAIN_SCREEN_LSCAPE_W)
#define	INCALL_LANDSCAPE_SCROLLER_T INCALL_LANDSCAPE_BODY_BG_T
#define	INCALL_LANDSCAPE_SCROLLER_B REL_LSCAPE_H(LSCAPE_BODY_BG_T_PAD+LSCAPE_SCROLLER_HEIGHT)

/*
#define INCALL_LANDSCAPE_CID_BG2_L REL_LSCAPE_W(0)
#define INCALL_LANDSCAPE_CID_BG2_R REL_LSCAPE_W(800)
#define INCALL_LANDSCAPE_CID_BG2_T REL_LSCAPE_H(0)
#define INCALL_LANDSCAPE_CID_BG2_B REL_LSCAPE_H(306)
*/

/*LSCAPE: CID-1 BG initial position*/
/*5 in conference*/
#define INCALL_LANDSCAPE_FIRST_CID_OUTER_BG_POS1_L REL_SCROLLER_W(FIRST_CID_OUTER_BG_POS1_L_PAD)
#define INCALL_LANDSCAPE_FIRST_CID_OUTER_BG_POS1_R REL_SCROLLER_W(FIRST_CID_OUTER_BG_POS1_L_PAD+CID_OUTER_BG_WIDTH)
/*4 in conference*/
#define INCALL_LANDSCAPE_FIRST_CID_OUTER_BG_POS2_L REL_LSCAPE_W(FIRST_CID_OUTER_BG_POS2_L_PAD)
#define INCALL_LANDSCAPE_FIRST_CID_OUTER_BG_POS2_R REL_LSCAPE_W(FIRST_CID_OUTER_BG_POS2_L_PAD+CID_OUTER_BG_WIDTH)
/*3 in conference*/
#define INCALL_LANDSCAPE_FIRST_CID_OUTER_BG_POS3_L REL_LSCAPE_W(FIRST_CID_OUTER_BG_POS3_L_PAD)
#define INCALL_LANDSCAPE_FIRST_CID_OUTER_BG_POS3_R REL_LSCAPE_W(FIRST_CID_OUTER_BG_POS3_L_PAD+CID_OUTER_BG_WIDTH)
/*2 in conference*/
#define INCALL_LANDSCAPE_FIRST_CID_OUTER_BG_POS4_L REL_LSCAPE_W(FIRST_CID_OUTER_BG_POS4_L_PAD)
#define INCALL_LANDSCAPE_FIRST_CID_OUTER_BG_POS4_R REL_LSCAPE_W(FIRST_CID_OUTER_BG_POS4_L_PAD+CID_OUTER_BG_WIDTH)
/*LSCAPE: CID-1 BG initial position*/
#define INCALL_LANDSCAPE_FIRST_CID_OUTER_BG_T REL_SCROLLER_H(CID_OUTER_BG_T_PAD)
#define INCALL_LANDSCAPE_FIRST_CID_OUTER_BG_B REL_SCROLLER_H(CID_OUTER_BG_HEIGHT)

#define INCALL_LANDSCAPE_CID_INNER_BG_L REL_LSCAPE_CID_W(CID_INNER_BG_L_PAD)
#define INCALL_LANDSCAPE_CID_INNER_BG_R REL_LSCAPE_CID_W(CID_INNER_BG_L_PAD+CID_INNER_BG_WIDTH)
#define INCALL_LANDSCAPE_CID_INNER_BG_T REL_LSCAPE_CID_H(CID_INNER_BG_T_PAD)
#define INCALL_LANDSCAPE_CID_INNER_BG_B REL_LSCAPE_CID_H(CID_INNER_BG_T_PAD+CID_INNER_BG_HEIGHT)

#define INCALL_LANDSCAPE_CID_END_L REL_LSCAPE_CID_W(CID_END_L_PAD)
#define INCALL_LANDSCAPE_CID_END_R REL_LSCAPE_CID_W(CID_END_L_PAD+CID_END_WIDTH)
#define INCALL_LANDSCAPE_CID_END_T REL_LSCAPE_CID_H(CID_END_T_PAD)
#define INCALL_LANDSCAPE_CID_END_B REL_LSCAPE_CID_H(CID_END_T_PAD+CID_END_HEIGHT)

#define INCALL_LANDSCAPE_CID_NAME_L INCALL_LANDSCAPE_CID_INNER_BG_L
#define INCALL_LANDSCAPE_CID_NAME_R INCALL_LANDSCAPE_CID_INNER_BG_R
#define INCALL_LANDSCAPE_CID_NAME_T REL_LSCAPE_CID_H(CID_NAME_T_PAD)
#define INCALL_LANDSCAPE_CID_NAME_B REL_LSCAPE_CID_H(CID_NAME_T_PAD+CID_NAME_HEIGHT)

#define INCALL_LANDSCAPE_CID_IMG_L REL_LSCAPE_CID_W(CID_IMG_L_PAD)
#define INCALL_LANDSCAPE_CID_IMG_R REL_LSCAPE_CID_W(CID_IMG_L_PAD+CID_IMG_WIDTH)
#define INCALL_LANDSCAPE_CID_IMG_T REL_LSCAPE_CID_H(CID_IMG_T_PAD)
#define INCALL_LANDSCAPE_CID_IMG_B REL_LSCAPE_CID_H(CID_IMG_T_PAD+CID_IMG_HEIGHT)

#define INCALL_LANDSCAPE_BTN_CID_SPLIT_L REL_LSCAPE_CID_W(CID_SPLIT_L_PAD)
#define INCALL_LANDSCAPE_BTN_CID_SPLIT_R REL_LSCAPE_CID_W(CID_SPLIT_L_PAD+CID_SPLIT_WIDTH)
#define INCALL_LANDSCAPE_BTN_CID_SPLIT_T REL_LSCAPE_CID_H(CID_SPLIT_T_PAD)
#define INCALL_LANDSCAPE_BTN_CID_SPLIT_B REL_LSCAPE_CID_H(CID_SPLIT_T_PAD+CID_SPLIT_HEIGHT)
/*LSCAPE: CID-1 Data*/

/*LSCAPE: Other CID Data*/
#define INCALL_LANDSCAPE_OTHER_CID_OUTER_BG_L REL_LSCAPE_CID_W(CID_OUTER_BG_WIDTH)
#define INCALL_LANDSCAPE_OTHER_CID_OUTER_BG_R REL_LSCAPE_CID_W(CID_OUTER_BG_WIDTH*2)
#define INCALL_LANDSCAPE_OTHER_CID_OUTER_BG_T REL_LSCAPE_CID_H(0)
#define INCALL_LANDSCAPE_OTHER_CID_OUTER_BG_B REL_LSCAPE_CID_H(CID_OUTER_BG_HEIGHT)
/*LSCAPE: Other CID Data*/

#define INCALL_LANDSCAPE_HOLD_L REL_LSCAPE_W(LSCAPE_HOLD_L_PAD)
#define INCALL_LANDSCAPE_HOLD_R REL_LSCAPE_W(LSCAPE_HOLD_L_PAD+LSCAPE_HOLD_WIDTH)
#define INCALL_LANDSCAPE_HOLD_T REL_LSCAPE_H(LSCAPE_HOLD_T_PAD)
#define INCALL_LANDSCAPE_HOLD_B REL_LSCAPE_H(LSCAPE_HOLD_T_PAD+LSCAPE_HOLD_HEIGHT)

#define INCALL_LANDSCAPE_TIMER_L INCALL_LANDSCAPE_HOLD_L
#define INCALL_LANDSCAPE_TIMER_R REL_LSCAPE_W(LSCAPE_HOLD_L_PAD+LSCAPE_TIMER_WIDTH)
#define INCALL_LANDSCAPE_TIMER_T INCALL_LANDSCAPE_HOLD_T
#define INCALL_LANDSCAPE_TIMER_B INCALL_LANDSCAPE_HOLD_B

#define	INCALL_LANDSCAPE_BIG_END_L INCALL_LANDSCAPE_HOLD_L
#define	INCALL_LANDSCAPE_BIG_END_R INCALL_LANDSCAPE_TIMER_R
#define	INCALL_LANDSCAPE_BIG_END_T REL_LSCAPE_H(LSCAPE_BIG_END_T_PAD)
#define	INCALL_LANDSCAPE_BIG_END_B REL_LSCAPE_H(LSCAPE_BIG_END_T_PAD+LSCAPE_BIG_END_HEIGHT)

/*
#define INCALL_LANDSCAPE_BACKGROUND_SHARE_L	REL_W(0)
#define INCALL_LANDSCAPE_BACKGROUND_SHARE_R	REL_W(MAIN_SCREEN_W)
#define INCALL_LANDSCAPE_BACKGROUND_SHARE_T	REL_H(365)
#define INCALL_LANDSCAPE_BACKGROUND_SHARE_B	REL_H(774)
*/
/*
 * End of MULTI-CALL CONF View
 */


/*
 * MULTI-CALL SPLIT View
 * In Landscape mode
 */
/* L[ACT] + R[HLD] */
#define MULTICALL_SPLIT_LANDSCAPE_BACKGROUND_CID_L REL_LSCAPE_W(0)
#define MULTICALL_SPLIT_LANDSCAPE_BACKGROUND_CID_R REL_LSCAPE_W(MAIN_SCREEN_LSCAPE_W)
#define MULTICALL_SPLIT_LANDSCAPE_BACKGROUND_CID_T REL_LSCAPE_H(0)
#define MULTICALL_SPLIT_LANDSCAPE_BACKGROUND_CID_B REL_LSCAPE_H(MAIN_SCREEN_LSCAPE_H)

#define MULTICALL_SPLIT_LANDSCAPE_CID_1_L REL_LSCAPE_W(LSCAPE_SPLIT_CID1_L_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_CID_1_R REL_LSCAPE_W(LSCAPE_SPLIT_CID1_L_PAD+LSCAPE_SPLIT_CID1_WIDTH)
#define MULTICALL_SPLIT_LANDSCAPE_CID_1_T REL_LSCAPE_H(LSCAPE_SPLIT_CID1_T_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_CID_1_B REL_LSCAPE_H(LSCAPE_SPLIT_CID1_T_PAD+LSCAPE_SPLIT_CID1_HEIGHT)

#define MULTICALL_SPLIT_LANDSCAPE_PAUSE_L REL_LSCAPE_W(LSCAPE_SPLIT_PAUSE_L_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_PAUSE_R REL_LSCAPE_W(LSCAPE_SPLIT_PAUSE_L_PAD+LSCAPE_SPLIT_PAUSE_WIDTH)
#define MULTICALL_SPLIT_LANDSCAPE_PAUSE_T REL_LSCAPE_H(LSCAPE_SPLIT_PAUSE_T_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_PAUSE_B REL_LSCAPE_H(LSCAPE_SPLIT_PAUSE_T_PAD+LSCAPE_SPLIT_PAUSE_HEIGHT)

#define MULTICALL_SPLIT_LANDSCAPE_CID_2_L REL_LSCAPE_W(LSCAPE_SPLIT_CID2_L_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_CID_2_R REL_LSCAPE_W(LSCAPE_SPLIT_CID2_L_PAD+LSCAPE_SPLIT_CID2_WIDTH)
#define MULTICALL_SPLIT_LANDSCAPE_CID_2_T REL_LSCAPE_H(LSCAPE_SPLIT_CID2_T_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_CID_2_B REL_LSCAPE_H(LSCAPE_SPLIT_CID2_T_PAD+LSCAPE_SPLIT_CID2_HEIGHT)

#define MULTICALL_SPLIT_LANDSCAPE_PLAY_L REL_LSCAPE_W(LSCAPE_SPLIT_PLAY_L_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_PLAY_R REL_LSCAPE_W(LSCAPE_SPLIT_PLAY_L_PAD+LSCAPE_SPLIT_PLAY_WIDTH)
#define MULTICALL_SPLIT_LANDSCAPE_PLAY_T REL_LSCAPE_H(LSCAPE_SPLIT_PLAY_T_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_PLAY_B REL_LSCAPE_H(LSCAPE_SPLIT_PLAY_T_PAD+LSCAPE_SPLIT_PLAY_HEIGHT)

#define MULTICALL_SPLIT_LANDSCAPE_NAME_1_L REL_LSCAPE_W(LSCAPE_SPLIT_NAME1_L_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_NAME_1_R REL_LSCAPE_W(LSCAPE_SPLIT_NAME1_L_PAD+LSCAPE_SPLIT_NAME1_WIDTH)
#define MULTICALL_SPLIT_LANDSCAPE_NAME_1_T REL_LSCAPE_H(LSCAPE_SPLIT_NAME1_T_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_NAME_1_B REL_LSCAPE_H(LSCAPE_SPLIT_NAME1_T_PAD+LSCAPE_SPLIT_NAME1_HEIGHT)

#define MULTICALL_SPLIT_LANDSCAPE_NAME_2_L REL_LSCAPE_W(LSCAPE_SPLIT_NAME2_L_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_NAME_2_R REL_LSCAPE_W(LSCAPE_SPLIT_NAME2_L_PAD+LSCAPE_SPLIT_NAME2_WIDTH)
#define MULTICALL_SPLIT_LANDSCAPE_NAME_2_T REL_LSCAPE_H(LSCAPE_SPLIT_NAME2_T_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_NAME_2_B REL_LSCAPE_H(LSCAPE_SPLIT_NAME2_T_PAD+LSCAPE_SPLIT_NAME2_HEIGHT)

#define MULTICALL_SPLIT_LANDSCAPE_TIMER_L MULTICALL_SPLIT_LANDSCAPE_CID_1_L
#define MULTICALL_SPLIT_LANDSCAPE_TIMER_R MULTICALL_SPLIT_LANDSCAPE_CID_1_R
#define MULTICALL_SPLIT_LANDSCAPE_TIMER_T REL_LSCAPE_H(LSCAPE_SPLIT_TIMER_T_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_TIMER_B REL_LSCAPE_H(LSCAPE_SPLIT_TIMER_T_PAD+LSCAPE_SPLIT_TIMER_HEIGHT)

#define MULTICALL_SPLIT_LANDSCAPE_ON_HOLD_TXT_L MULTICALL_SPLIT_LANDSCAPE_CID_2_L
#define MULTICALL_SPLIT_LANDSCAPE_ON_HOLD_TXT_R MULTICALL_SPLIT_LANDSCAPE_CID_2_R
#define MULTICALL_SPLIT_LANDSCAPE_ON_HOLD_TXT_T REL_LSCAPE_H(LSCAPE_SPLIT_ONHOLD_TXT_T_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_ON_HOLD_TXT_B REL_LSCAPE_H(LSCAPE_SPLIT_ONHOLD_TXT_T_PAD+LSCAPE_SPLIT_ONHOLD_TXT_HEIGHT)

#define MULTICALL_SPLIT_LANDSCAPE_ON_HOLD_TXT_WITH_ICON_L MULTICALL_SPLIT_LANDSCAPE_ON_HOLD_TXT_L
#define MULTICALL_SPLIT_LANDSCAPE_ON_HOLD_TXT_WITH_ICON_R REL_LSCAPE_W(LSCAPE_SPLIT_CID2_L_PAD+LSCAPE_SPLIT_ONHOLD_TXT_W_ICON_WIDTH)
#define MULTICALL_SPLIT_LANDSCAPE_ON_HOLD_TXT_WITH_ICON_T MULTICALL_SPLIT_LANDSCAPE_ON_HOLD_TXT_T
#define MULTICALL_SPLIT_LANDSCAPE_ON_HOLD_TXT_WITH_ICON_B MULTICALL_SPLIT_LANDSCAPE_ON_HOLD_TXT_B

#define MULTICALL_SPLIT_LANDSCAPE_MORE_ICON_L REL_LSCAPE_W(LSCAPE_SPLIT_MORE_BTN_L_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_MORE_ICON_R MULTICALL_SPLIT_LANDSCAPE_CID_2_R
#define MULTICALL_SPLIT_LANDSCAPE_MORE_ICON_T MULTICALL_SPLIT_LANDSCAPE_ON_HOLD_TXT_T
#define MULTICALL_SPLIT_LANDSCAPE_MORE_ICON_B MULTICALL_SPLIT_LANDSCAPE_ON_HOLD_TXT_B
/* L[ACT] + R[HLD] */

/* L[HLD] + R[ACT] */
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_CID_1_L REL_LSCAPE_W(LSCAPE_SPLIT_SWAP_CID1_L_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_CID_1_R REL_LSCAPE_W(LSCAPE_SPLIT_SWAP_CID1_L_PAD+LSCAPE_SPLIT_SWAP_CID1_WIDTH)
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_CID_1_T MULTICALL_SPLIT_LANDSCAPE_CID_2_T
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_CID_1_B MULTICALL_SPLIT_LANDSCAPE_CID_2_B

#define MULTICALL_SPLIT_LANDSCAPE_SWAP_PLAY_L REL_LSCAPE_W(LSCAPE_SPLIT_SWAP_PLAY_L_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_PLAY_R REL_LSCAPE_W(LSCAPE_SPLIT_SWAP_PLAY_L_PAD+LSCAPE_SPLIT_SWAP_PLAY_WIDTH)
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_PLAY_T MULTICALL_SPLIT_LANDSCAPE_PLAY_T
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_PLAY_B MULTICALL_SPLIT_LANDSCAPE_PLAY_B

#define MULTICALL_SPLIT_LANDSCAPE_SWAP_CID_2_L REL_LSCAPE_W(LSCAPE_SPLIT_SWAP_CID2_L_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_CID_2_R REL_LSCAPE_W(LSCAPE_SPLIT_SWAP_CID2_L_PAD+LSCAPE_SPLIT_SWAP_CID2_WIDTH)
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_CID_2_T MULTICALL_SPLIT_LANDSCAPE_CID_1_T
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_CID_2_B MULTICALL_SPLIT_LANDSCAPE_CID_1_B

#define MULTICALL_SPLIT_LANDSCAPE_SWAP_PAUSE_L REL_LSCAPE_W(LSCAPE_SPLIT_SWAP_PAUSE_L_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_PAUSE_R REL_LSCAPE_W(LSCAPE_SPLIT_SWAP_PAUSE_L_PAD+LSCAPE_SPLIT_SWAP_PAUSE_WIDTH)
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_PAUSE_T MULTICALL_SPLIT_LANDSCAPE_PAUSE_T
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_PAUSE_B MULTICALL_SPLIT_LANDSCAPE_PAUSE_B

#define MULTICALL_SPLIT_LANDSCAPE_SWAP_NAME_1_L REL_LSCAPE_W(LSCAPE_SPLIT_SWAP_NAME1_L_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_NAME_1_R REL_LSCAPE_W(LSCAPE_SPLIT_SWAP_NAME1_L_PAD+LSCAPE_SPLIT_SWAP_NAME1_WIDTH)
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_NAME_1_T MULTICALL_SPLIT_LANDSCAPE_NAME_2_T
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_NAME_1_B MULTICALL_SPLIT_LANDSCAPE_NAME_2_B

#define MULTICALL_SPLIT_LANDSCAPE_SWAP_NAME_2_L REL_LSCAPE_W(LSCAPE_SPLIT_SWAP_NAME2_L_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_NAME_2_R REL_LSCAPE_W(LSCAPE_SPLIT_SWAP_NAME2_L_PAD+LSCAPE_SPLIT_SWAP_NAME2_WIDTH)
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_NAME_2_T MULTICALL_SPLIT_LANDSCAPE_NAME_1_T
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_NAME_2_B MULTICALL_SPLIT_LANDSCAPE_NAME_1_B

#define MULTICALL_SPLIT_LANDSCAPE_SWAP_ON_HOLD_TXT_L MULTICALL_SPLIT_LANDSCAPE_SWAP_CID_1_L
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_ON_HOLD_TXT_R MULTICALL_SPLIT_LANDSCAPE_SWAP_CID_1_R
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_ON_HOLD_TXT_T MULTICALL_SPLIT_LANDSCAPE_ON_HOLD_TXT_T
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_ON_HOLD_TXT_B MULTICALL_SPLIT_LANDSCAPE_ON_HOLD_TXT_T

#define MULTICALL_SPLIT_LANDSCAPE_SWAP_TIMER_L MULTICALL_SPLIT_LANDSCAPE_SWAP_CID_2_L
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_TIMER_R MULTICALL_SPLIT_LANDSCAPE_SWAP_CID_2_R
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_TIMER_T MULTICALL_SPLIT_LANDSCAPE_TIMER_T
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_TIMER_B MULTICALL_SPLIT_LANDSCAPE_TIMER_B

#define MULTICALL_SPLIT_LANDSCAPE_SWAP_TIMER_WITH_ICON_L MULTICALL_SPLIT_LANDSCAPE_SWAP_CID_2_L
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_TIMER_WITH_ICON_R REL_LSCAPE_W(LSCAPE_SPLIT_SWAP_CID2_L_PAD+LSCAPE_SPLIT_TIMER_TXT_W_ICON_WIDTH)
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_TIMER_WITH_ICON_T MULTICALL_SPLIT_LANDSCAPE_TIMER_T
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_TIMER_WITH_ICON_B MULTICALL_SPLIT_LANDSCAPE_TIMER_B

#define MULTICALL_SPLIT_LANDSCAPE_SWAP_MORE_ICON_L REL_LSCAPE_W(LSCAPE_SPLIT_SWAP_MORE_BTN_L_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_MORE_ICON_R REL_LSCAPE_W(LSCAPE_SPLIT_SWAP_MORE_BTN_L_PAD+LSCAPE_SPLIT_SWAP_MORE_BTN_WIDTH)
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_MORE_ICON_T REL_LSCAPE_H(LSCAPE_SPLIT_SWAP_MORE_BTN_T_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_SWAP_MORE_ICON_B REL_LSCAPE_H(LSCAPE_SPLIT_SWAP_MORE_BTN_T_PAD+LSCAPE_SPLIT_SWAP_MORE_BTN_HEIGHT)
/* L[HLD] + R[ACT] */

#define MULTICALL_SPLIT_LANDSCAPE_JOIN_L REL_LSCAPE_W(LSCAPE_SPLIT_JOIN_BTN_L_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_JOIN_R REL_LSCAPE_W(LSCAPE_SPLIT_JOIN_BTN_L_PAD+LSCAPE_SPLIT_JOIN_BTN_WIDTH)
#define MULTICALL_SPLIT_LANDSCAPE_JOIN_T REL_LSCAPE_H(LSCAPE_SPLIT_JOIN_BTN_T_PAD)
#define MULTICALL_SPLIT_LANDSCAPE_JOIN_B REL_LSCAPE_H(LSCAPE_SPLIT_JOIN_BTN_T_PAD+LSCAPE_SPLIT_JOIN_BTN_HEIGHT)

#define	MULTICALL_SPLIT_LANDSCAPE_BIG_END_L	REL_LSCAPE_W(LSCAPE_SPLIT_BIG_END_BTN_L_PAD)
#define	MULTICALL_SPLIT_LANDSCAPE_BIG_END_R	REL_LSCAPE_W(LSCAPE_SPLIT_BIG_END_BTN_L_PAD+LSCAPE_SPLIT_BIG_END_BTN_WIDTH)
#define	MULTICALL_SPLIT_LANDSCAPE_BIG_END_T	MULTICALL_SPLIT_LANDSCAPE_JOIN_T
#define	MULTICALL_SPLIT_LANDSCAPE_BIG_END_B	MULTICALL_SPLIT_LANDSCAPE_JOIN_B
/*
 * End of MULTI-CALL SPLIT View
 */

/*
 * QUICK-PANEL layout
 * In Portrait mode
 */
#define	LSCAPE_QUICKPANEL_CID_L REL_LSCAPE_QP_W(LSCAPE_QP_CID_L_PAD)
#define	LSCAPE_QUICKPANEL_CID_R REL_LSCAPE_QP_W(LSCAPE_QP_CID_L_PAD+LSCAPE_QP_CID_WIDTH)
#define	LSCAPE_QUICKPANEL_CID_T REL_LSCAPE_QP_H(LSCAPE_QP_CID_T_PAD)
#define	LSCAPE_QUICKPANEL_CID_B REL_LSCAPE_QP_H(LSCAPE_QP_CID_T_PAD+LSCAPE_QP_CID_HEIGHT)

#define	LSCAPE_QUICKPANEL_BTN_MUTE_L REL_LSCAPE_QP_W(LSCAPE_QP_MUTE_BTN_L_PAD)
#define	LSCAPE_QUICKPANEL_BTN_MUTE_R REL_LSCAPE_QP_W(LSCAPE_QP_MUTE_BTN_L_PAD+LSCAPE_QP_END_BTN_WIDTH)
#define	LSCAPE_QUICKPANEL_BTN_MUTE_T REL_LSCAPE_QP_H(LSCAPE_QP_MUTE_BTN_T_PAD)
#define	LSCAPE_QUICKPANEL_BTN_MUTE_B REL_LSCAPE_QP_H(LSCAPE_QP_MUTE_BTN_T_PAD+LSCAPE_QP_END_BTN_HEIGHT)

#define	LSCAPE_QUICKPANEL_BTN_END_L REL_LSCAPE_QP_W(LSCAPE_QP_END_BTN_L_PAD)
#define	LSCAPE_QUICKPANEL_BTN_END_R REL_LSCAPE_QP_W(LSCAPE_QP_END_BTN_L_PAD+LSCAPE_QP_END_BTN_WIDTH)
#define	LSCAPE_QUICKPANEL_BTN_END_T REL_LSCAPE_QP_H(LSCAPE_QP_END_BTN_T_PAD)
#define	LSCAPE_QUICKPANEL_BTN_END_B REL_LSCAPE_QP_H(LSCAPE_QP_END_BTN_T_PAD+LSCAPE_QP_END_BTN_HEIGHT)

#define	LSCAPE_QUICKPANEL_NAME_L REL_LSCAPE_QP_W(LSCAPE_QP_NAME_L_PAD)
#define	LSCAPE_QUICKPANEL_NAME_R REL_LSCAPE_QP_W(LSCAPE_QP_NAME_L_PAD+LSCAPE_QP_NAME_WIDTH)
#define	LSCAPE_QUICKPANEL_NAME_T REL_LSCAPE_QP_H(LSCAPE_QP_NAME_T_PAD)
#define	LSCAPE_QUICKPANEL_NAME_B REL_LSCAPE_QP_H(LSCAPE_QP_NAME_T_PAD+LSCAPE_QP_NAME_HEIGHT)

/*
 * Caller info layout
 * In Portrait mode
 */

#define CALLER_INFO_L REL_W(CALLER_INFO_L_PAD)
#define CALLER_INFO_R REL_W(CALLER_INFO_L_PAD+CALLER_INFO_WIDTH)
#define CALLER_INFO_T REL_H(CALLER_INFO_T_PAD)
#define CALLER_INFO_B REL_H(CALLER_INFO_T_PAD+CALLER_INFO_HEIGHT)

#define CALLER_INFO_HOLD_L REL_W(CALLER_INFO_L_PAD)
#define CALLER_INFO_HOLD_R REL_W(CALLER_INFO_L_PAD+CALLER_INFO_WIDTH)
#define CALLER_INFO_HOLD_T REL_H(CALLER_INFO_HOLD_T_PAD)
#define CALLER_INFO_HOLD_B REL_H(CALLER_INFO_HOLD_T_PAD+CALLER_INFO_HEIGHT)

#define CALLER_INFO_TOP_L REL_W(0)
#define CALLER_INFO_TOP_R REL_W(MAIN_SCREEN_W)
#define CALLER_INFO_TOP_T REL_CALLER_INFO_H(0)
#define CALLER_INFO_TOP_B REL_CALLER_INFO_H(CALLER_INFO_TOP_PAD_HEIGHT)

#define CALLER_INFO_NAME_L REL_W(CALLER_INFO_NAME_L_PAD)
#define CALLER_INFO_NAME_R REL_W(CALLER_INFO_NAME_L_PAD+CALLER_INFO_NAME_WIDTH)
#define CALLER_INFO_NAME_T REL_CALLER_INFO_H(CALLER_INFO_NAME_T_PAD)
#define CALLER_INFO_NAME_B REL_CALLER_INFO_H(CALLER_INFO_NAME_T_PAD+CALLER_INFO_NAME_HEIGHT)

#define CALLER_INFO_VERT_SEP_1_L REL_W(CALLER_INFO_VERT_SEP_L_PAD)
#define CALLER_INFO_VERT_SEP_1_R REL_W(CALLER_INFO_VERT_SEP_L_PAD+CALLER_INFO_VERT_SEP_WIDTH)
#define CALLER_INFO_VERT_SEP_1_T REL_CALLER_INFO_H(CALLER_INFO_VERT_SEP_T_PAD)
#define CALLER_INFO_VERT_SEP_1_B REL_CALLER_INFO_H(CALLER_INFO_VERT_SEP_T_PAD+CALLER_INFO_VERT_SEP_HEIGHT)
#define CALLER_INFO_VERT_SEP_2_L CALLER_INFO_VERT_SEP_1_R
#define CALLER_INFO_VERT_SEP_2_R REL_W(CALLER_INFO_VERT_SEP_L_PAD+2*CALLER_INFO_VERT_SEP_WIDTH)
#define CALLER_INFO_VERT_SEP_2_T CALLER_INFO_VERT_SEP_1_T
#define CALLER_INFO_VERT_SEP_2_B CALLER_INFO_VERT_SEP_1_B

#define CALLER_INFO_ICON_L REL_W(CALLER_INFO_ICON_L_PAD)
#define CALLER_INFO_ICON_R REL_W(CALLER_INFO_ICON_L_PAD+CALLER_INFO_ICON_WIDTH)
#define CALLER_INFO_ICON_T REL_CALLER_INFO_H(CALLER_INFO_ICON_T_PAD)
#define CALLER_INFO_ICON_B REL_CALLER_INFO_H(CALLER_INFO_ICON_T_PAD+CALLER_INFO_ICON_HEIGHT)

#define CALLER_INFO_NUMBER_L REL_W(CALLER_INFO_NUMBER_L_PAD)
#define CALLER_INFO_NUMBER_R REL_W(CALLER_INFO_NUMBER_L_PAD+CALL_NUMBER_WIDTH)
#define CALLER_INFO_NUMBER_T REL_CALLER_INFO_H(CALLER_INFO_NUMBER_T_PAD)
#define CALLER_INFO_NUMBER_B REL_CALLER_INFO_H(CALLER_INFO_NUMBER_T_PAD+CALLER_INFO_NUMBER_HEIGHT)

#define CALLER_INFO_TIMER_L REL_W(CALLER_INFO_TIME_L_PAD)
#define CALLER_INFO_TIMER_R REL_W(CALLER_INFO_TIME_L_PAD+CALLER_INFO_TIME_WIDTH)
#define CALLER_INFO_TIMER_T REL_CALLER_INFO_H(CALLER_INFO_TIME_T_PAD)
#define CALLER_INFO_TIMER_B REL_CALLER_INFO_H(CALLER_INFO_TIME_T_PAD+CALLER_INFO_TIME_HEIGHT)

/*
 * End of Caller info layout
 */

/*
 * Ctxpoup layout
 * In Portrait mode
 */

#define MORE_MENU_CTXPOPUP_ROW_H			97
#define MORE_MENU_CTXPOPUP_ROW_ICON_W		64
#define MORE_MENU_CTXPOPUP_ROW_ICON_H		64
#define MORE_MENU_CTXPOPUP_ROW_ICON_PAD		16

#define MORE_MENU_CTXPOPUP_SEPARATOR_W		478
#define MORE_MENU_CTXPOPUP_SEPARATOR_H		1

#define MORE_MENU_CTXPOPUP_ARROW_W			42
#define MORE_MENU_CTXPOPUP_ARROW_H			22

#define MORE_MENU_CTXPOPUP_SHADOW_PADDING 	3
#define MORE_MENU_CTXPOPUP_PADDING 			10

/*
 * End of Ctxpoup layout
 */


/*
 * SNS alerts layout
 */
#define	ALERTS_BDAY_ICON_L REL_ALERTS_LY_W(BIRTHDAY_ICON_L_PAD)
#define	ALERTS_BDAY_ICON_R REL_ALERTS_LY_W(BIRTHDAY_ICON_L_PAD+BIRTHDAY_ICON_WIDTH)
#define	ALERTS_BDAY_ICON_T REL_ALERTS_LY_H(BIRTHDAY_ICON_T_PAD)
#define	ALERTS_BDAY_ICON_B REL_ALERTS_LY_H(BIRTHDAY_ICON_T_PAD+BIRTHDAY_ICON_HEIGHT)

#define	ALERTS_BDAY_ICON_EXPANDED_T REL_ALERTS_EXP_LY_H(BIRTHDAY_ICON_T_PAD)
#define	ALERTS_BDAY_ICON_EXPANDED_B REL_ALERTS_EXP_LY_H(BIRTHDAY_ICON_T_PAD+BIRTHDAY_ICON_HEIGHT)

#define	ALERTS_BDAY_TEXT_L REL_ALERTS_LY_W(BIRTHDAY_TEXT_L_PAD)
#define	ALERTS_BDAY_TEXT_R REL_ALERTS_LY_W(BIRTHDAY_TEXT_L_PAD+BIRTHDAY_TEXT_WIDTH)
#define	ALERTS_BDAY_TEXT_T REL_ALERTS_LY_H(BIRTHDAY_TEXT_T_PAD)
#define	ALERTS_BDAY_TEXT_B REL_ALERTS_LY_H(BIRTHDAY_TEXT_T_PAD+BIRTHDAY_TEXT_HEIGHT)

#define	ALERTS_BDAY_TEXT_EXPANDED_T REL_ALERTS_EXP_LY_H(BIRTHDAY_TEXT_T_PAD)
#define	ALERTS_BDAY_TEXT_EXPANDED_B REL_ALERTS_EXP_LY_H(BIRTHDAY_TEXT_T_PAD+BIRTHDAY_TEXT_HEIGHT)

#define ALERTS_SNS_ICON_L REL_ALERTS_LY_W(SNS_STATUS_ICON_L_PAD)
#define ALERTS_SNS_ICON_R REL_ALERTS_LY_W(SNS_STATUS_ICON_L_PAD+SNS_STATUS_ICON_WIDTH)
#define ALERTS_SNS_ICON_T REL_ALERTS_LY_H(SNS_STATUS_ICON_T_PAD)
#define ALERTS_SNS_ICON_B REL_ALERTS_LY_H(SNS_STATUS_ICON_T_PAD+SNS_STATUS_ICON_HEIGHT)

#define ALERTS_SNS_ICON_EXPANDED_T REL_ALERTS_EXP_LY_H(SNS_STATUS_ICON_T_PAD)
#define ALERTS_SNS_ICON_EXPANDED_B REL_ALERTS_EXP_LY_H(SNS_STATUS_ICON_T_PAD+SNS_STATUS_ICON_HEIGHT)

#define ALERTS_SNS_TEXT_L REL_ALERTS_LY_W(SNS_STATUS_TEXT_L_PAD)
#define ALERTS_SNS_TEXT_R REL_ALERTS_LY_W(SNS_STATUS_TEXT_L_PAD+SNS_STATUS_TEXT_WIDTH)
#define ALERTS_SNS_TEXT_T REL_ALERTS_LY_H(SNS_STATUS_TEXT_T_PAD)
#define ALERTS_SNS_TEXT_B REL_ALERTS_LY_H(SNS_STATUS_TEXT_T_PAD+SNS_STATUS_TEXT_HEIGHT)

#define ALERTS_SNS_EXPANDED_TEXT_L REL_ALERTS_LY_W(SNS_STATUS_TEXT_L_PAD)
#define ALERTS_SNS_EXPANDED_TEXT_R REL_ALERTS_LY_W(SNS_STATUS_TEXT_L_PAD+SNS_STATUS_EXPANDED_TEXT_WIDTH)
#define ALERTS_SNS_EXPANDED_TEXT_T REL_ALERTS_EXP_LY_H(SNS_STATUS_TEXT_T_PAD)
#define ALERTS_SNS_EXPANDED_TEXT_B REL_ALERTS_EXP_LY_H(SNS_STATUS_TEXT_T_PAD+SNS_STATUS_EXPANDED_TEXT_HEIGHT)

#define ALERTS_SNS_ARROW_L REL_ALERTS_LY_W(SNS_STATUS_ARROW_L_PAD)
#define ALERTS_SNS_ARROW_R REL_ALERTS_LY_W(SNS_STATUS_ARROW_L_PAD+SNS_STATUS_ARROW_WIDTH)
#define ALERTS_SNS_ARROW_T REL_ALERTS_LY_H(SNS_STATUS_ARROW_T_PAD)
#define ALERTS_SNS_ARROW_B REL_ALERTS_LY_H(SNS_STATUS_ARROW_T_PAD+SNS_STATUS_ARROW_HEIGHT)

#define ALERTS_SNS_EXPANDED_ARROW_T REL_ALERTS_EXP_LY_H(SNS_STATUS_ARROW_T_PAD)
#define ALERTS_SNS_EXPANDED_ARROW_B REL_ALERTS_EXP_LY_H(SNS_STATUS_ARROW_T_PAD+SNS_STATUS_ARROW_HEIGHT)
/*
 * End of SNS alerts layout
 */
#endif				/*_VCUI_VIEW_LAYOUT_HD_H_*/
