/*
 * Copyright 2012  Samsung Electronics Co., Ltd
 *
 * Licensed under the Flora License, Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.tizenopensource.org/license
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#ifndef __VCUI_VIEW_LAYOUT_HD__
#define __VCUI_VIEW_LAYOUT_HD__

#define COLOR_DEFAULT 0 0 0 255
#define COLOR_BG_ALPHA 0 0 0 0
#define COLOR_BG_FOR_HELD_CALL_DIM 0 0 0 150

/*#define BTN_EDGE_W 9*/

/*
 * HD GUI Widget Dimensions
 * In Portrait mode
 */
#define MAIN_SCREEN_W 720
#define MAIN_SCREEN_H 1280

#define INDICATOR_HEIGHT 50
#define NAVIFRAME_TITLE_HEIGHT 100

#define MAIN_NAVIFRAME_W MAIN_SCREEN_W
#define MAIN_NAVIFRAME_H (MAIN_SCREEN_H-INDICATOR_HEIGHT-NAVIFRAME_TITLE_HEIGHT)
#define NAVIFRAME_T_PAD 50

#define QP_WIN_W MAIN_SCREEN_W
#define QP_WIN_H 166	/*approx*/

#define DIALING_STATUS_L_PAD 0
#define DIALING_STATUS_WIDTH MAIN_SCREEN_W
#define DIALING_STATUS_T_PAD 687
#define	DIALING_STATUS_HEIGHT 52

#define CALL_NAME_L_PAD 20
#define CALL_NAME_WIDTH 680
#define CALL_NAME_T_PAD 83
#define	CALL_NAME_HEIGHT 80

#define CALL_NUMBER_T_GAP 6

#define CALL_NUMBER_L_PAD CALL_NAME_L_PAD
#define CALL_NUMBER_WIDTH CALL_NAME_WIDTH
#define CALL_NUMBER_T_PAD (CALL_NAME_T_PAD+CALL_NAME_HEIGHT+CALL_NUMBER_T_GAP)
#define	CALL_NUMBER_HEIGHT 52

#define CALLER_ID_L_PAD 208
#define CALLER_ID_WIDTH 304
#define CALLER_ID_T_PAD 268
#define	CALLER_ID_HEIGHT 304

#define BACKGROUND_CID_L_PAD 0
#define BACKGROUND_CID_WIDTH MAIN_SCREEN_W
#define BACKGROUND_CID_T_PAD 0
#define BACKGROUND_CID_HEIGHT MAIN_SCREEN_H

#define	MT_CALLING_NAME_BG_WIDTH MAIN_SCREEN_W
#define	MT_CALLING_NAME_BG_HEIGHT 590

#define	ACCEPT_BTN_L_PAD 40
#define	ACCEPT_BTN_WIDTH 300
#define	ACCEPT_BTN_T_PAD 992
#define	ACCEPT_BTN_HEIGHT 112

#define REJECT_BTN_L_GAP 40

#define	REJECT_BTN_L_PAD (ACCEPT_BTN_L_PAD+ACCEPT_BTN_WIDTH+REJECT_BTN_L_GAP)
#define	REJECT_BTN_WIDTH ACCEPT_BTN_WIDTH
#define	REJECT_BTN_T_PAD ACCEPT_BTN_T_PAD
#define	REJECT_BTN_HEIGHT ACCEPT_BTN_HEIGHT

#define REJECT_W_MSG_BTN_T_GAP 40

#define	REJECT_W_MSG_BTN_L_PAD ACCEPT_BTN_L_PAD
#define	REJECT_W_MSG_BTN_WIDTH 640
#define	REJECT_W_MSG_BTN_T_PAD (ACCEPT_BTN_T_PAD+ACCEPT_BTN_HEIGHT+REJECT_W_MSG_BTN_T_GAP)
#define	REJECT_W_MSG_BTN_HEIGHT 90

#define	INCALL_HOLD_BTN_L_PAD 40
#define	INCALL_HOLD_BTN_WIDTH 108 /*approx*/
#define	INCALL_HOLD_BTN_T_PAD 670 /*approx*/
#define	INCALL_HOLD_BTN_HEIGHT 86 /*approx*/

#define	INCALL_TIMER_L_PAD 40
#define	INCALL_TIMER_WIDTH 640
#define	INCALL_TIMER_T_PAD 687
#define	INCALL_TIMER_HEIGHT 52

#define INCALL_SHARE_BG_T_PAD 584 /*approx*/
#define INCALL_SHARE_BG_HEIGHT 654 /*approx*/

#define KEYPAD_TIMER_L_PAD 40
#define KEYPAD_TIMER_WIDTH 640
#define KEYPAD_TIMER_T_PAD 384
#define KEYPAD_TIMER_HEIGHT 52

#define KEYPAD_ENTRY_TXT_L_PAD KEYPAD_TIMER_L_PAD
#define KEYPAD_ENTRY_TXT_WIDTH KEYPAD_TIMER_WIDTH
#define KEYPAD_ENTRY_TXT_T_PAD 90
#define KEYPAD_ENTRY_TXT_HEIGHT 114

#define	KEYPAD_BTNS_T_PAD 461
#define	KEYPAD_BTNS_WIDTH MAIN_SCREEN_W
#define	KEYPAD_BTNS_HEIGHT 620

#define KEYPAD_HIDE_BTN_L_PAD KEYPAD_TIMER_L_PAD
#define KEYPAD_HIDE_BTN_WIDTH 300
#define KEYPAD_HIDE_BTN_T_PAD 1140
#define KEYPAD_HIDE_BTN_HEIGHT 112

#define KEYPAD_BTN_GAP 40
#define KEYPAD_END_BTN_L_PAD (KEYPAD_HIDE_BTN_L_PAD+KEYPAD_HIDE_BTN_WIDTH+KEYPAD_BTN_GAP)
#define KEYPAD_END_BTN_WIDTH KEYPAD_HIDE_BTN_WIDTH

#define	SPLIT_CID1_L_PAD 56
#define SPLIT_CID1_WIDTH 304
#define SPLIT_CID1_T_PAD 219
#define SPLIT_CID1_HEIGHT 304

#define	SPLIT_PAUSE_L_PAD (SPLIT_CID1_L_PAD+8)
#define SPLIT_PAUSE_WIDTH 62
#define SPLIT_PAUSE_HEIGHT 62
#define SPLIT_PAUSE_T_PAD (SPLIT_CID1_T_PAD+SPLIT_CID1_HEIGHT-8-SPLIT_PAUSE_HEIGHT)

#define	SPLIT_CID2_L_PAD 456
#define SPLIT_CID2_WIDTH 208
#define SPLIT_CID2_T_PAD 267
#define SPLIT_CID2_HEIGHT 208

#define	SPLIT_PLAY_L_PAD (SPLIT_CID2_L_PAD+12)
#define SPLIT_PLAY_WIDTH 40
#define SPLIT_PLAY_HEIGHT 40
#define SPLIT_PLAY_T_PAD (SPLIT_CID2_T_PAD+SPLIT_CID2_HEIGHT-8-SPLIT_PLAY_HEIGHT)

#define	SPLIT_NAME1_L_PAD 38
#define SPLIT_NAME1_WIDTH 364
#define SPLIT_NAME1_T_PAD 145
#define SPLIT_NAME1_HEIGHT 58

#define	SPLIT_NAME2_L_PAD (SPLIT_NAME1_L_PAD+SPLIT_NAME1_WIDTH+22)
#define SPLIT_NAME2_WIDTH 258
#define SPLIT_NAME2_T_PAD 217
#define SPLIT_NAME2_HEIGHT 40

#define SPLIT_TIMER_TXT_T_PAD 549
#define SPLIT_TIMER_TXT_HEIGHT 46

#define SPLIT_MORE_BTN_WIDTH 40
#define SPLIT_MORE_BTN_L_PAD (SPLIT_CID2_L_PAD+SPLIT_CID2_WIDTH-SPLIT_MORE_BTN_WIDTH)
#define SPLIT_ONHOLD_TXT_W_ICON_WIDTH (SPLIT_CID2_WIDTH-SPLIT_MORE_BTN_WIDTH)
#define SPLIT_ONHOLD_TXT_T_PAD 492
#define SPLIT_ONHOLD_TXT_HEIGHT 40

#define	SPLIT_SWAP_CID1_L_PAD 70
#define SPLIT_SWAP_CID1_WIDTH 208

#define	SPLIT_SWAP_PLAY_L_PAD (SPLIT_SWAP_CID1_L_PAD+12)
#define SPLIT_SWAP_PLAY_WIDTH 40

#define	SPLIT_SWAP_CID2_L_PAD 336
#define SPLIT_SWAP_CID2_WIDTH 304

#define	SPLIT_SWAP_PAUSE_L_PAD (SPLIT_SWAP_CID2_L_PAD+8)
#define SPLIT_SWAP_PAUSE_WIDTH 62

#define	SPLIT_SWAP_NAME1_L_PAD 38
#define SPLIT_SWAP_NAME1_WIDTH 258

#define	SPLIT_SWAP_NAME2_L_PAD (SPLIT_SWAP_NAME1_L_PAD+SPLIT_SWAP_NAME1_WIDTH+22)
#define SPLIT_SWAP_NAME2_WIDTH 364

#define SPLIT_SWAP_MORE_BTN_WIDTH 60
#define SPLIT_SWAP_MORE_BTN_L_PAD (SPLIT_SWAP_CID2_L_PAD+SPLIT_SWAP_CID2_WIDTH-SPLIT_SWAP_MORE_BTN_WIDTH)
#define SPLIT_SWAP_MORE_BTN_T_PAD (SPLIT_TIMER_TXT_T_PAD-7)
#define SPLIT_SWAP_MORE_BTN_HEIGHT 60
#define SPLIT_TIMER_TXT_W_ICON_WIDTH (SPLIT_SWAP_CID2_WIDTH-SPLIT_SWAP_MORE_BTN_WIDTH)

#define	CONF_LIST_T_PAD 182
#define	CONF_LIST_HEIGHT 566

#define	CONF_HOLD_WIDTH 110
#define	CONF_HOLD_L_PAD (MAIN_SCREEN_W-40-CONF_HOLD_WIDTH)
#define	CONF_HOLD_T_PAD 866
#define	CONF_HOLD_HEIGHT 76

#define	CONF_TIMER_T_PAD 878
#define	CONF_TIMER_HEIGHT 52

#define	CONF_CALL_BIG_END_T_PAD 1026

#define	REJ_MSG_NEW_BTN_L_PAD 40 /*approx*/
#define	REJ_MSG_NEW_BTN_WIDTH 640 /*approx*/
#define	REJ_MSG_NEW_BTN_T_PAD 120 /*approx*/
#define	REJ_MSG_NEW_BTN_HEIGHT 128 /*approx*/

#define REJ_MSG_LIST_T_PAD 32 /*approx*/
#define	REJ_MSG_LIST_HEIGHT 1096 /*approx*/

#define SIX_BTN_COL1_L_PAD 40
#define SIX_BTN_COL1_WIDTH 200
#define SIX_BTN_COL2_L_PAD (SIX_BTN_COL1_L_PAD+SIX_BTN_COL1_WIDTH+20)
#define SIX_BTN_COL3_L_PAD (SIX_BTN_COL2_L_PAD+SIX_BTN_COL1_WIDTH+20)
#define SIX_BTN_ROW1_T_PAD 792
#define SIX_BTN_ROW1_HEIGHT 140
#define SIX_BTN_ROW2_T_PAD (SIX_BTN_ROW1_T_PAD+SIX_BTN_ROW1_HEIGHT+20)

#define	CALL_BIG_END_L_PAD 40
#define	CALL_BIG_END_WIDTH 640
#define	CALL_BIG_END_T_PAD 1140
#define	CALL_BIG_END_HEIGHT 112

#define INCMG_CALL_BTN1_T_PAD 700
#define INCMG_CALL_BTN_HEIGHT CALL_BIG_END_HEIGHT
#define INCMG_CALL_BTN2_T_PAD 838
#define INCMG_CALL_BTN3_T_PAD 976

#define	VIDEO_BTN_POS1_L_PAD 40
#define	VIDEO_BTN_POS1_WIDTH 300
#define	VIDEO_BTN_POS1_T_PAD 864
#define	VIDEO_BTN_POS1_HEIGHT 112
#define	VIDEO_BTN_POS2_L_PAD VIDEO_BTN_POS1_L_PAD
#define	VIDEO_BTN_POS2_WIDTH VIDEO_BTN_POS1_WIDTH
#define	VIDEO_BTN_POS2_T_PAD 1002
#define	VIDEO_BTN_POS2_HEIGHT VIDEO_BTN_POS1_HEIGHT

#define	VOICE_BTN_POS1_L_PAD (VIDEO_BTN_POS1_L_PAD+VIDEO_BTN_POS1_WIDTH+40)
#define	VOICE_BTN_POS1_WIDTH VIDEO_BTN_POS1_WIDTH

#define	MSG_BTN_POS1_L_PAD VIDEO_BTN_POS1_L_PAD
#define	MSG_BTN_POS1_WIDTH 640
#define	MSG_BTN_POS1_T_PAD 1002
#define	MSG_BTN_POS1_HEIGHT VIDEO_BTN_POS1_HEIGHT
#define	MSG_BTN_POS2_T_PAD 1140
#define	MSG_BTN_POS2_HEIGHT VIDEO_BTN_POS1_HEIGHT

#define	CONTACT_BTN_POS1_L_PAD VIDEO_BTN_POS1_L_PAD
#define	CONTACT_BTN_POS1_WIDTH MSG_BTN_POS1_WIDTH
#define	CONTACT_BTN_POS1_T_PAD 1140
#define	CONTACT_BTN_POS1_HEIGHT VIDEO_BTN_POS1_HEIGHT

#define QP_CID_L_PAD 15	/*approx*/
#define QP_CID_WIDTH 123 /*approx*/
#define QP_CID_T_PAD 18 /*approx*/
#define QP_CID_HEIGHT 130 /*approx*/

#define QP_END_BTN_L_PAD 153 /*approx*/
#define QP_END_BTN_WIDTH 552 /*approx*/
#define QP_END_BTN_T_PAD 80 /*approx*/
#define QP_END_BTN_HEIGHT 64 /*approx*/

#define QP_NAME_L_PAD 153 /*approx*/
#define QP_NAME_WIDTH 372 /*approx*/
#define QP_NAME_T_PAD 13 /*approx*/
#define QP_NAME_HEIGHT 48 /*approx*/

#define QP_TIMER_L_PAD 555 /*approx*/
/*
 * End of HD GUI Widget Dimensions
 */


/*
 * Relative positions
 * In Portrait mode
 */
/* Relative X & Y positions of widgets w.r.t. Full Screen */
#define REL_W(x) ((x)/MAIN_SCREEN_W)
#define REL_H(y) ((y)/MAIN_SCREEN_H)

/* Relative X & Y positions of widgets w.r.t. Navi-frame layout */
/*#define WL_NB_H 94*/
#define REL_NAVIFRAME_W(x) ((x)/MAIN_NAVIFRAME_W)
#define REL_NAVIFRAME_H(y) ((y)/MAIN_NAVIFRAME_H)

/* Relative X & Y positions of widgets w.r.t. ACC/REJ ICON layout */
#define REL_LOCK_W(x) ((x)/483) /*approx*/
#define REL_LOCK_H(y) ((y)/198) /*approx*/
/* Relative X & Y positions of widgets w.r.t. REJ-W-MSG ICON layout */
#define REL_LOCK_MSG_W(x) ((x)/348)	/*approx*/
#define REL_LOCK_MSG_H(y) ((y)/200) /*approx*/

/* Relative X & Y positions of widgets w.r.t. Keypad Buttons layout */
#define REL_KEYPAD_W(x) ((x)/KEYPAD_BTNS_WIDTH)
#define REL_KEYPAD_H(y) ((y)/KEYPAD_BTNS_HEIGHT)
/*
 * End of Relative positions
 */


/*
 * MO/Dialing view & MT/Incoming view
 * In Portrait mode
 */
#define DIALLING_STATUS_L REL_W(DIALING_STATUS_L_PAD)
#define DIALLING_STATUS_R REL_W(DIALING_STATUS_L_PAD+DIALING_STATUS_WIDTH)
#define DIALLING_STATUS_T REL_H(DIALING_STATUS_T_PAD)
#define DIALLING_STATUS_B REL_H(DIALING_STATUS_T_PAD+DIALING_STATUS_HEIGHT)

/*
#define DIALLING_MT_STATUS_L REL_W(123)
#define DIALLING_MT_STATUS_R REL_W(357)
#define DIALLING_MT_STATUS_T REL_H(375)
#define DIALLING_MT_STATUS_B REL_H(407)
*/

#define DIALLING_NAME_L REL_W(CALL_NAME_L_PAD)
#define DIALLING_NAME_R REL_W(CALL_NAME_L_PAD+CALL_NAME_WIDTH)
#define DIALLING_NAME_T REL_H(CALL_NAME_T_PAD)
#define DIALLING_NAME_B REL_H(CALL_NAME_T_PAD+CALL_NAME_HEIGHT)

#define DIALLING_NUMBER_L REL_W(CALL_NUMBER_L_PAD)
#define DIALLING_NUMBER_R REL_W(CALL_NUMBER_L_PAD+CALL_NUMBER_WIDTH)
#define DIALLING_NUMBER_T REL_H(CALL_NUMBER_T_PAD)
#define DIALLING_NUMBER_B REL_H(CALL_NUMBER_T_PAD+CALL_NUMBER_HEIGHT)

#define DIALLING_CID_L REL_W(CALLER_ID_L_PAD)
#define DIALLING_CID_R REL_W(CALLER_ID_L_PAD+CALLER_ID_WIDTH)
#define DIALLING_CID_T REL_H(CALLER_ID_T_PAD)
#define DIALLING_CID_B REL_H(CALLER_ID_T_PAD+CALLER_ID_HEIGHT)

#define DIALLING_BACKGROUND_CID_L REL_W(BACKGROUND_CID_L_PAD)
#define DIALLING_BACKGROUND_CID_R REL_W(BACKGROUND_CID_L_PAD+BACKGROUND_CID_WIDTH)
#define DIALLING_BACKGROUND_CID_T REL_H(BACKGROUND_CID_T_PAD)
#define DIALLING_BACKGROUND_CID_B REL_H(BACKGROUND_CID_T_PAD+BACKGROUND_CID_HEIGHT)

#define MT_CALLING_BG_L REL_W(0)
#define MT_CALLING_BG_R REL_W(0+MT_CALLING_NAME_BG_WIDTH)
#define MT_CALLING_BG_T REL_H(0)
#define MT_CALLING_BG_B REL_H(0+MT_CALLING_NAME_BG_HEIGHT)

/* accept - MT view */
#define DIALLING_MT_BTN1_L REL_W(ACCEPT_BTN_L_PAD)
#define DIALLING_MT_BTN1_R REL_W(ACCEPT_BTN_L_PAD+ACCEPT_BTN_WIDTH)
#define DIALLING_MT_BTN1_T REL_H(ACCEPT_BTN_T_PAD)
#define DIALLING_MT_BTN1_B REL_H(ACCEPT_BTN_T_PAD+ACCEPT_BTN_HEIGHT)

/* reject - MT view */
#define DIALLING_MT_BTN2_L  REL_W(REJECT_BTN_L_PAD)
#define DIALLING_MT_BTN2_R  REL_W(REJECT_BTN_L_PAD+REJECT_BTN_WIDTH)
#define DIALLING_MT_BTN2_T  REL_H(REJECT_BTN_T_PAD)
#define DIALLING_MT_BTN2_B  REL_H(REJECT_BTN_T_PAD+REJECT_BTN_HEIGHT)
/*
 * End of MO/Dialing view & MT/Incoming view
 */


/*
 * MT LOCK View - check
 * In Portrait mode
 */
#define INCOMING_LOCK_ACCEPT_BG_L REL_W(-273)
#define INCOMING_LOCK_ACCEPT_BG_R REL_W(210)
#define INCOMING_LOCK_ACCEPT_BG_T REL_H(945)
#define INCOMING_LOCK_ACCEPT_BG_B REL_H(1144)

#define INCOMING_LOCK_ACCEPT_ICON_L REL_LOCK_W(303)
#define INCOMING_LOCK_ACCEPT_ICON_R REL_LOCK_W(408)
#define INCOMING_LOCK_ACCEPT_ICON_T REL_LOCK_H(37)
#define INCOMING_LOCK_ACCEPT_ICON_B REL_LOCK_H(149)

#define INCOMING_LOCK_ACCEPT_TEXT_L REL_LOCK_W(45)
#define INCOMING_LOCK_ACCEPT_TEXT_R REL_LOCK_W(273)
#define INCOMING_LOCK_ACCEPT_TEXT_T INCOMING_LOCK_ACCEPT_ICON_T
#define INCOMING_LOCK_ACCEPT_TEXT_B INCOMING_LOCK_ACCEPT_ICON_B

#define INCOMING_LOCK_REJECT_BG_L REL_W(510)
#define INCOMING_LOCK_REJECT_BG_R REL_W(993)
#define INCOMING_LOCK_REJECT_BG_T INCOMING_LOCK_ACCEPT_BG_T
#define INCOMING_LOCK_REJECT_BG_B INCOMING_LOCK_ACCEPT_BG_B

#define INCOMING_LOCK_REJECT_ICON_L REL_LOCK_W(75)
#define INCOMING_LOCK_REJECT_ICON_R REL_LOCK_W(180)
#define INCOMING_LOCK_REJECT_ICON_T INCOMING_LOCK_ACCEPT_ICON_T
#define INCOMING_LOCK_REJECT_ICON_B INCOMING_LOCK_ACCEPT_ICON_B

#define INCOMING_LOCK_REJECT_TEXT_L REL_LOCK_W(195)
#define INCOMING_LOCK_REJECT_TEXT_R REL_LOCK_W(423)
#define INCOMING_LOCK_REJECT_TEXT_T INCOMING_LOCK_REJECT_ICON_T
#define INCOMING_LOCK_REJECT_TEXT_B INCOMING_LOCK_REJECT_ICON_B
/*
 * End of MT LOCK View
 */


/*
 * KEYPAD View
 * In Portrait mode
 */
#define INCALL_DIALER_TIMER_L REL_W(KEYPAD_TIMER_L_PAD)
#define INCALL_DIALER_TIMER_R REL_W(KEYPAD_TIMER_L_PAD+KEYPAD_TIMER_WIDTH)
#define INCALL_DIALER_TIMER_T REL_H(KEYPAD_TIMER_T_PAD)
#define INCALL_DIALER_TIMER_B REL_H(KEYPAD_TIMER_T_PAD+KEYPAD_TIMER_HEIGHT)

#define INCALL_DIALER_NAME_L INCALL_DIALER_TIMER_L
#define INCALL_DIALER_NAME_R INCALL_DIALER_TIMER_R
#define INCALL_DIALER_NAME_T INCALL_DIALER_TIMER_T
#define INCALL_DIALER_NAME_B INCALL_DIALER_TIMER_B

/*
#define DIALLING_KEYPAD_T_BF REL_H(319)
#define DIALLING_KEYPAD_B_BF REL_H(710)
*/

#define DIALLING_KEYPAD_L REL_W(0)
#define DIALLING_KEYPAD_R REL_W(MAIN_SCREEN_W)
#define DIALLING_KEYPAD_T REL_H(KEYPAD_BTNS_T_PAD)
#define DIALLING_KEYPAD_B REL_H(KEYPAD_BTNS_T_PAD+KEYPAD_BTNS_HEIGHT)

#define DIALLING_ENTRY_TEXT_L REL_W(KEYPAD_ENTRY_TXT_L_PAD)
#define DIALLING_ENTRY_TEXT_R REL_W(KEYPAD_ENTRY_TXT_L_PAD+KEYPAD_ENTRY_TXT_WIDTH)
#define DIALLING_ENTRY_TEXT_T REL_H(KEYPAD_ENTRY_TXT_T_PAD)
#define DIALLING_ENTRY_TEXT_B REL_H(KEYPAD_ENTRY_TXT_T_PAD+KEYPAD_ENTRY_TXT_HEIGHT)

#define DIALER_BTN1_L REL_W(KEYPAD_HIDE_BTN_L_PAD)
#define DIALER_BTN1_R REL_W(KEYPAD_HIDE_BTN_L_PAD+KEYPAD_HIDE_BTN_WIDTH)
#define DIALER_BTN1_T REL_H(KEYPAD_HIDE_BTN_T_PAD)
#define DIALER_BTN1_B REL_H(KEYPAD_HIDE_BTN_T_PAD+KEYPAD_HIDE_BTN_HEIGHT)

#define DIALER_BTN2_L REL_W(KEYPAD_END_BTN_L_PAD)
#define DIALER_BTN2_R REL_W(KEYPAD_END_BTN_L_PAD+KEYPAD_END_BTN_WIDTH)
#define DIALER_BTN2_T DIALER_BTN1_T
#define DIALER_BTN2_B DIALER_BTN1_B
/*
 * End of KEYPAD View
 */


/*
 * INCALL View
 * In Portrait mode
 */
#define INCALL_CID_L DIALLING_CID_L
#define INCALL_CID_R DIALLING_CID_R
#define INCALL_CID_T DIALLING_CID_T
#define INCALL_CID_B DIALLING_CID_B

/*
#define INCALL_CID_DIM_T DIALLING_CID_T
#define INCALL_CID_DIM_B DIALLING_CID_B
#define INCALL_CID_DIM_L REL_W(145)
#define INCALL_CID_DIM_R REL_W(334)
*/

#define INCALL_BACKGROUND_CID_L DIALLING_BACKGROUND_CID_L
#define INCALL_BACKGROUND_CID_R DIALLING_BACKGROUND_CID_R
#define INCALL_BACKGROUND_CID_T DIALLING_BACKGROUND_CID_T
#define INCALL_BACKGROUND_CID_B DIALLING_BACKGROUND_CID_B

#define INCALL_NAME_L DIALLING_NAME_L
#define INCALL_NAME_R DIALLING_NAME_R
#define INCALL_NAME_T DIALLING_NAME_T
#define INCALL_NAME_B DIALLING_NAME_B

#define INCALL_NUMBER_L DIALLING_NUMBER_L
#define INCALL_NUMBER_R DIALLING_NUMBER_R
#define INCALL_NUMBER_T DIALLING_NUMBER_T
#define INCALL_NUMBER_B DIALLING_NUMBER_B

#define INCALL_HOLD_L REL_W(INCALL_HOLD_BTN_L_PAD)
#define INCALL_HOLD_R REL_W(INCALL_HOLD_BTN_L_PAD+INCALL_HOLD_BTN_WIDTH)
#define INCALL_HOLD_T REL_H(INCALL_HOLD_BTN_T_PAD)
#define INCALL_HOLD_B REL_H(INCALL_HOLD_BTN_T_PAD+INCALL_HOLD_BTN_HEIGHT)

#define INCALL_TIMER_L REL_W(INCALL_TIMER_L_PAD)
#define INCALL_TIMER_R REL_W(INCALL_TIMER_L_PAD+INCALL_TIMER_WIDTH)
#define INCALL_TIMER_T REL_H(INCALL_TIMER_T_PAD)
#define INCALL_TIMER_B REL_H(INCALL_TIMER_T_PAD+INCALL_TIMER_HEIGHT)

#define INCALL_BACKGROUND_SHARE_L	REL_W(0)
#define INCALL_BACKGROUND_SHARE_R	REL_W(MAIN_SCREEN_W)
#define INCALL_BACKGROUND_SHARE_T	REL_H(INCALL_SHARE_BG_T_PAD)
#define INCALL_BACKGROUND_SHARE_B	REL_H(INCALL_SHARE_BG_T_PAD+INCALL_SHARE_BG_HEIGHT)
/*
 * End of INCALL View
 */


/*
 * MULTI-CALL SPLIT View
 * In Portrait mode
 */
/* L[ACT] + R[HLD] */
#define MULTICALL_SPLIT_BACKGROUND_CID_L INCALL_BACKGROUND_CID_L
#define MULTICALL_SPLIT_BACKGROUND_CID_R INCALL_BACKGROUND_CID_R
#define MULTICALL_SPLIT_BACKGROUND_CID_T INCALL_BACKGROUND_CID_T
#define MULTICALL_SPLIT_BACKGROUND_CID_B INCALL_BACKGROUND_CID_B

#define MULTICALL_SPLIT_CID_1_L REL_W(SPLIT_CID1_L_PAD)
#define MULTICALL_SPLIT_CID_1_R REL_W(SPLIT_CID1_L_PAD+SPLIT_CID1_WIDTH)
#define MULTICALL_SPLIT_CID_1_T REL_H(SPLIT_CID1_T_PAD)
#define MULTICALL_SPLIT_CID_1_B REL_H(SPLIT_CID1_T_PAD+SPLIT_CID1_HEIGHT)

#define MULTICALL_SPLIT_PAUSE_L REL_W(SPLIT_PAUSE_L_PAD)
#define MULTICALL_SPLIT_PAUSE_R REL_W(SPLIT_PAUSE_L_PAD+SPLIT_PAUSE_WIDTH)
#define MULTICALL_SPLIT_PAUSE_T REL_H(SPLIT_PAUSE_T_PAD)
#define MULTICALL_SPLIT_PAUSE_B REL_H(SPLIT_PAUSE_T_PAD+SPLIT_PAUSE_HEIGHT)

#define MULTICALL_SPLIT_CID_2_L REL_W(SPLIT_CID2_L_PAD)
#define MULTICALL_SPLIT_CID_2_R REL_W(SPLIT_CID2_L_PAD+SPLIT_CID2_WIDTH)
#define MULTICALL_SPLIT_CID_2_T REL_H(SPLIT_CID2_T_PAD)
#define MULTICALL_SPLIT_CID_2_B REL_H(SPLIT_CID2_T_PAD+SPLIT_CID2_HEIGHT)

#define MULTICALL_SPLIT_PLAY_L REL_W(SPLIT_PLAY_L_PAD)
#define MULTICALL_SPLIT_PLAY_R REL_W(SPLIT_PLAY_L_PAD+SPLIT_PLAY_WIDTH)
#define MULTICALL_SPLIT_PLAY_T REL_H(SPLIT_PLAY_T_PAD)
#define MULTICALL_SPLIT_PLAY_B REL_H(SPLIT_PLAY_T_PAD+SPLIT_PLAY_HEIGHT)

#define MULTICALL_SPLIT_NAME_1_L REL_W(SPLIT_NAME1_L_PAD)
#define MULTICALL_SPLIT_NAME_1_R REL_W(SPLIT_NAME1_L_PAD+SPLIT_NAME1_WIDTH)
#define MULTICALL_SPLIT_NAME_1_T REL_H(SPLIT_NAME1_T_PAD)
#define MULTICALL_SPLIT_NAME_1_B REL_H(SPLIT_NAME1_T_PAD+SPLIT_NAME1_HEIGHT)

#define MULTICALL_SPLIT_NAME_2_L REL_W(SPLIT_NAME2_L_PAD)
#define MULTICALL_SPLIT_NAME_2_R REL_W(SPLIT_NAME2_L_PAD+SPLIT_NAME2_WIDTH)
#define MULTICALL_SPLIT_NAME_2_T REL_H(SPLIT_NAME2_T_PAD)
#define MULTICALL_SPLIT_NAME_2_B REL_H(SPLIT_NAME2_T_PAD+SPLIT_NAME2_HEIGHT)

#define MULTICALL_SPLIT_TIMER_L MULTICALL_SPLIT_CID_1_L
#define MULTICALL_SPLIT_TIMER_R MULTICALL_SPLIT_CID_1_R
#define MULTICALL_SPLIT_TIMER_T REL_H(SPLIT_TIMER_TXT_T_PAD)
#define MULTICALL_SPLIT_TIMER_B REL_H(SPLIT_TIMER_TXT_T_PAD+SPLIT_TIMER_TXT_HEIGHT)

#define MULTICALL_SPLIT_ON_HOLD_TXT_L MULTICALL_SPLIT_CID_2_L
#define MULTICALL_SPLIT_ON_HOLD_TXT_R MULTICALL_SPLIT_CID_2_R
#define MULTICALL_SPLIT_ON_HOLD_TXT_T REL_H(SPLIT_ONHOLD_TXT_T_PAD)
#define MULTICALL_SPLIT_ON_HOLD_TXT_B REL_H(SPLIT_ONHOLD_TXT_T_PAD+SPLIT_ONHOLD_TXT_HEIGHT)

#define MULTICALL_SPLIT_ON_HOLD_TXT_WITH_ICON_L MULTICALL_SPLIT_CID_2_L
#define MULTICALL_SPLIT_ON_HOLD_TXT_WITH_ICON_R REL_W(SPLIT_CID2_L_PAD+SPLIT_CID2_WIDTH-SPLIT_MORE_BTN_WIDTH)
#define MULTICALL_SPLIT_ON_HOLD_TXT_WITH_ICON_T MULTICALL_SPLIT_ON_HOLD_TXT_T
#define MULTICALL_SPLIT_ON_HOLD_TXT_WITH_ICON_B MULTICALL_SPLIT_ON_HOLD_TXT_B

#define MULTICALL_SPLIT_MORE_ICON_L REL_W(SPLIT_MORE_BTN_L_PAD)
#define MULTICALL_SPLIT_MORE_ICON_R REL_W(SPLIT_MORE_BTN_L_PAD+SPLIT_MORE_BTN_WIDTH)
#define MULTICALL_SPLIT_MORE_ICON_T MULTICALL_SPLIT_ON_HOLD_TXT_T
#define MULTICALL_SPLIT_MORE_ICON_B MULTICALL_SPLIT_ON_HOLD_TXT_B
/* L[ACT] + R[HLD] */

/* L[HLD] + R[ACT] */
#define MULTICALL_SPLIT_SWAP_CID_1_L REL_W(SPLIT_SWAP_CID1_L_PAD)
#define MULTICALL_SPLIT_SWAP_CID_1_R REL_W(SPLIT_SWAP_CID1_L_PAD+SPLIT_SWAP_CID1_WIDTH)
#define MULTICALL_SPLIT_SWAP_CID_1_T MULTICALL_SPLIT_CID_2_T
#define MULTICALL_SPLIT_SWAP_CID_1_B MULTICALL_SPLIT_CID_2_B

#define MULTICALL_SPLIT_SWAP_PLAY_L REL_W(SPLIT_SWAP_PLAY_L_PAD)
#define MULTICALL_SPLIT_SWAP_PLAY_R REL_W(SPLIT_SWAP_PLAY_L_PAD+SPLIT_SWAP_PLAY_WIDTH)
#define MULTICALL_SPLIT_SWAP_PLAY_T MULTICALL_SPLIT_PLAY_T
#define MULTICALL_SPLIT_SWAP_PLAY_B MULTICALL_SPLIT_PLAY_B

#define MULTICALL_SPLIT_SWAP_CID_2_L REL_W(SPLIT_SWAP_CID2_L_PAD)
#define MULTICALL_SPLIT_SWAP_CID_2_R REL_W(SPLIT_SWAP_CID2_L_PAD+SPLIT_SWAP_CID2_WIDTH)
#define MULTICALL_SPLIT_SWAP_CID_2_T MULTICALL_SPLIT_CID_1_T
#define MULTICALL_SPLIT_SWAP_CID_2_B MULTICALL_SPLIT_CID_1_B

#define MULTICALL_SPLIT_SWAP_PAUSE_L REL_W(SPLIT_SWAP_PAUSE_L_PAD)
#define MULTICALL_SPLIT_SWAP_PAUSE_R REL_W(SPLIT_SWAP_PAUSE_L_PAD+SPLIT_SWAP_PAUSE_WIDTH)
#define MULTICALL_SPLIT_SWAP_PAUSE_T MULTICALL_SPLIT_PAUSE_T
#define MULTICALL_SPLIT_SWAP_PAUSE_B MULTICALL_SPLIT_PAUSE_B

#define MULTICALL_SPLIT_SWAP_NAME_1_L MULTICALL_SPLIT_NAME_1_L
#define MULTICALL_SPLIT_SWAP_NAME_1_R REL_W(SPLIT_SWAP_NAME1_L_PAD+SPLIT_SWAP_NAME1_WIDTH)
#define MULTICALL_SPLIT_SWAP_NAME_1_T MULTICALL_SPLIT_NAME_2_T
#define MULTICALL_SPLIT_SWAP_NAME_1_B MULTICALL_SPLIT_NAME_2_B

#define MULTICALL_SPLIT_SWAP_NAME_2_L REL_W(SPLIT_SWAP_NAME2_L_PAD)
#define MULTICALL_SPLIT_SWAP_NAME_2_R REL_W(SPLIT_SWAP_NAME2_L_PAD+SPLIT_SWAP_NAME2_WIDTH)
#define MULTICALL_SPLIT_SWAP_NAME_2_T MULTICALL_SPLIT_NAME_1_T
#define MULTICALL_SPLIT_SWAP_NAME_2_B MULTICALL_SPLIT_NAME_1_B

#define MULTICALL_SPLIT_SWAP_ON_HOLD_TXT_L MULTICALL_SPLIT_SWAP_CID_1_L
#define MULTICALL_SPLIT_SWAP_ON_HOLD_TXT_R MULTICALL_SPLIT_SWAP_CID_1_R
#define MULTICALL_SPLIT_SWAP_ON_HOLD_TXT_T MULTICALL_SPLIT_ON_HOLD_TXT_T
#define MULTICALL_SPLIT_SWAP_ON_HOLD_TXT_B MULTICALL_SPLIT_ON_HOLD_TXT_B

#define MULTICALL_SPLIT_SWAP_TIMER_L MULTICALL_SPLIT_SWAP_CID_2_L
#define MULTICALL_SPLIT_SWAP_TIMER_R MULTICALL_SPLIT_SWAP_CID_2_R
#define MULTICALL_SPLIT_SWAP_TIMER_T MULTICALL_SPLIT_TIMER_T
#define MULTICALL_SPLIT_SWAP_TIMER_B MULTICALL_SPLIT_TIMER_B

#define MULTICALL_SPLIT_SWAP_TIMER_WITH_ICON_L MULTICALL_SPLIT_SWAP_CID_2_L
#define MULTICALL_SPLIT_SWAP_TIMER_WITH_ICON_R REL_W(SPLIT_CID2_L_PAD+SPLIT_CID2_WIDTH-SPLIT_MORE_BTN_WIDTH)
#define MULTICALL_SPLIT_SWAP_TIMER_WITH_ICON_T MULTICALL_SPLIT_TIMER_T
#define MULTICALL_SPLIT_SWAP_TIMER_WITH_ICON_B MULTICALL_SPLIT_TIMER_B

#define MULTICALL_SPLIT_SWAP_MORE_ICON_L REL_W(SPLIT_SWAP_MORE_BTN_L_PAD)
#define MULTICALL_SPLIT_SWAP_MORE_ICON_R REL_W(SPLIT_SWAP_MORE_BTN_L_PAD+SPLIT_SWAP_MORE_BTN_WIDTH)
#define MULTICALL_SPLIT_SWAP_MORE_ICON_T REL_H(SPLIT_SWAP_MORE_BTN_T_PAD)
#define MULTICALL_SPLIT_SWAP_MORE_ICON_B REL_H(SPLIT_SWAP_MORE_BTN_T_PAD+SPLIT_SWAP_MORE_BTN_HEIGHT)
/* L[HLD] + R[ACT] */
/*
 * End of MULTI-CALL SPLIT View
 */

/*
 * MULTI-CALL LIST View
 * In Portrait mode
 */
#define MULTICALL_LIST_L REL_W(0)
#define MULTICALL_LIST_R REL_W(MAIN_SCREEN_W)
#define MULTICALL_LIST_T REL_H(CONF_LIST_T_PAD)
#define MULTICALL_LIST_B REL_H(CONF_LIST_T_PAD+CONF_LIST_HEIGHT)

#define MULTICALL_LIST_HOLD_L REL_W(CONF_HOLD_L_PAD)
#define MULTICALL_LIST_HOLD_R REL_W(CONF_HOLD_L_PAD+CONF_HOLD_WIDTH)
#define MULTICALL_LIST_HOLD_T REL_H(CONF_HOLD_T_PAD)
#define MULTICALL_LIST_HOLD_B REL_H(CONF_HOLD_T_PAD+CONF_HOLD_HEIGHT)

#define MULTICALL_LIST_TIMER_L REL_W(0)
#define MULTICALL_LIST_TIMER_R REL_W(MAIN_SCREEN_W)
#define MULTICALL_LIST_TIMER_T REL_H(CONF_TIMER_T_PAD)
#define MULTICALL_LIST_TIMER_B REL_H(CONF_TIMER_T_PAD+CONF_TIMER_HEIGHT)

#define MULTICALL_LIST_BIG_END_L REL_W(CALL_BIG_END_L_PAD)
#define MULTICALL_LIST_BIG_END_R REL_W(CALL_BIG_END_L_PAD+CALL_BIG_END_WIDTH)
#define MULTICALL_LIST_BIG_END_T REL_H(CONF_CALL_BIG_END_T_PAD)
#define MULTICALL_LIST_BIG_END_B REL_H(CONF_CALL_BIG_END_T_PAD+CALL_BIG_END_HEIGHT)
/*
 * End of MULTI-CALL LIST View
 */


/*
 * SIX Button Layout
 * In Portrait mode
 */
#define SIX_BTN_1_L REL_W(SIX_BTN_COL1_L_PAD)
#define SIX_BTN_1_R REL_W(SIX_BTN_COL1_L_PAD+SIX_BTN_COL1_WIDTH)
#define SIX_BTN_2_L REL_W(SIX_BTN_COL2_L_PAD)
#define SIX_BTN_2_R REL_W(SIX_BTN_COL2_L_PAD+SIX_BTN_COL1_WIDTH)
#define SIX_BTN_3_L REL_W(SIX_BTN_COL3_L_PAD)
#define SIX_BTN_3_R REL_W(SIX_BTN_COL3_L_PAD+SIX_BTN_COL1_WIDTH)

#define SIX_BTN_1_T REL_H(SIX_BTN_ROW1_T_PAD)
#define SIX_BTN_1_B REL_H(SIX_BTN_ROW1_T_PAD+SIX_BTN_ROW1_HEIGHT)
#define SIX_BTN_2_T REL_H(SIX_BTN_ROW2_T_PAD)
#define SIX_BTN_2_B REL_H(SIX_BTN_ROW2_T_PAD+SIX_BTN_ROW1_HEIGHT)

#define SIX_BTN_BIG_END_L REL_W(CALL_BIG_END_L_PAD)
#define SIX_BTN_BIG_END_R REL_W(CALL_BIG_END_L_PAD+CALL_BIG_END_WIDTH)
#define SIX_BTN_BIG_END_T REL_H(CALL_BIG_END_T_PAD)
#define SIX_BTN_BIG_END_B REL_H(CALL_BIG_END_T_PAD+CALL_BIG_END_HEIGHT)

#define SIX_BTN_INCOMING_1_L SIX_BTN_BIG_END_L
#define SIX_BTN_INCOMING_1_R SIX_BTN_BIG_END_R
#define SIX_BTN_INCOMING_1_T REL_H(INCMG_CALL_BTN1_T_PAD)
#define SIX_BTN_INCOMING_1_B REL_H(INCMG_CALL_BTN1_T_PAD+INCMG_CALL_BTN_HEIGHT)

#define SIX_BTN_INCOMING_2_L SIX_BTN_BIG_END_L
#define SIX_BTN_INCOMING_2_R SIX_BTN_BIG_END_R
#define SIX_BTN_INCOMING_2_T REL_H(INCMG_CALL_BTN2_T_PAD)
#define SIX_BTN_INCOMING_2_B REL_H(INCMG_CALL_BTN2_T_PAD+INCMG_CALL_BTN_HEIGHT)

#define SIX_BTN_INCOMING_3_L SIX_BTN_BIG_END_L
#define SIX_BTN_INCOMING_3_R SIX_BTN_BIG_END_R
#define SIX_BTN_INCOMING_3_T REL_H(INCMG_CALL_BTN3_T_PAD)
#define SIX_BTN_INCOMING_3_B REL_H(INCMG_CALL_BTN3_T_PAD+INCMG_CALL_BTN_HEIGHT)
/*
 * End of SIX Button Layout
 */


/*
 * Navigation bar layout
 */
#define CALL_NAVIGATION_BAR_T REL_H(NAVIFRAME_T_PAD)
#define CALL_NAVIGATION_BAR_B REL_H(MAIN_SCREEN_H)
#define CALL_NAVIGATION_BAR_L REL_W(0)
#define CALL_NAVIGATION_BAR_R REL_W(MAIN_SCREEN_W)
/*
 * End of Navigation bar layout
 */


/*
 * END CALL View
 * In Portrait mode
 */
#define	ENDSINGLECALL_BACKGROUND_CID_L DIALLING_BACKGROUND_CID_L
#define	ENDSINGLECALL_BACKGROUND_CID_R DIALLING_BACKGROUND_CID_R
#define	ENDSINGLECALL_BACKGROUND_CID_T DIALLING_BACKGROUND_CID_T
#define	ENDSINGLECALL_BACKGROUND_CID_B DIALLING_BACKGROUND_CID_B

#define ENDSINGLECALL_CID_L DIALLING_CID_L
#define ENDSINGLECALL_CID_R DIALLING_CID_R
#define ENDSINGLECALL_CID_T DIALLING_CID_T
#define ENDSINGLECALL_CID_B DIALLING_CID_B

#define ENDSINGLECALL_NAME_L DIALLING_NAME_L
#define ENDSINGLECALL_NAME_R DIALLING_NAME_R
#define ENDSINGLECALL_NAME_T DIALLING_NAME_T
#define ENDSINGLECALL_NAME_B DIALLING_NAME_B

#define ENDSINGLECALL_NUMBER_L DIALLING_NUMBER_L
#define ENDSINGLECALL_NUMBER_R DIALLING_NUMBER_R
#define ENDSINGLECALL_NUMBER_T DIALLING_NUMBER_T
#define ENDSINGLECALL_NUMBER_B DIALLING_NUMBER_B

#define ENDSINGLECALL_TIMER_L INCALL_TIMER_L
#define ENDSINGLECALL_TIMER_R INCALL_TIMER_R
#define ENDSINGLECALL_TIMER_T INCALL_TIMER_T
#define ENDSINGLECALL_TIMER_B INCALL_TIMER_B

#define	ENDSINGLECALL_VIDEO_BTN_L REL_W(VIDEO_BTN_POS1_L_PAD)
#define	ENDSINGLECALL_VIDEO_BTN_R REL_W(VIDEO_BTN_POS1_L_PAD+VIDEO_BTN_POS1_WIDTH)
#define	ENDSINGLECALL_VIDEO_BTN_T REL_H(VIDEO_BTN_POS1_T_PAD)
#define	ENDSINGLECALL_VIDEO_BTN_B REL_H(VIDEO_BTN_POS1_T_PAD+VIDEO_BTN_POS1_HEIGHT)

#define	ENDSINGLECALL_VIDEO2_BTN_L REL_W(VIDEO_BTN_POS2_L_PAD)
#define	ENDSINGLECALL_VIDEO2_BTN_R REL_W(VIDEO_BTN_POS2_L_PAD+VIDEO_BTN_POS2_WIDTH)
#define	ENDSINGLECALL_VIDEO2_BTN_T REL_H(VIDEO_BTN_POS2_T_PAD)
#define	ENDSINGLECALL_VIDEO2_BTN_B REL_H(VIDEO_BTN_POS2_T_PAD+VIDEO_BTN_POS2_HEIGHT)

#define	ENDSINGLECALL_VOICE_BTN_L REL_W(VOICE_BTN_POS1_L_PAD)
#define	ENDSINGLECALL_VOICE_BTN_R REL_W(VOICE_BTN_POS1_L_PAD+VOICE_BTN_POS1_WIDTH)
#define	ENDSINGLECALL_VOICE_BTN_T ENDSINGLECALL_VIDEO_BTN_T
#define	ENDSINGLECALL_VOICE_BTN_B ENDSINGLECALL_VIDEO_BTN_B

#define	ENDSINGLECALL_VOICE2_BTN_L ENDSINGLECALL_VOICE_BTN_L
#define	ENDSINGLECALL_VOICE2_BTN_R ENDSINGLECALL_VOICE_BTN_R
#define	ENDSINGLECALL_VOICE2_BTN_T ENDSINGLECALL_VIDEO2_BTN_T
#define	ENDSINGLECALL_VOICE2_BTN_B ENDSINGLECALL_VIDEO2_BTN_B

#define	ENDSINGLECALL_MSG_BTN_L REL_W(MSG_BTN_POS1_L_PAD)
#define	ENDSINGLECALL_MSG_BTN_R REL_W(MSG_BTN_POS1_L_PAD+MSG_BTN_POS1_WIDTH)
#define	ENDSINGLECALL_MSG_BTN_T REL_H(MSG_BTN_POS1_T_PAD)
#define	ENDSINGLECALL_MSG_BTN_B REL_H(MSG_BTN_POS1_T_PAD+MSG_BTN_POS1_HEIGHT)

#define	ENDSINGLECALL_MSG2_BTN_L ENDSINGLECALL_MSG_BTN_L
#define	ENDSINGLECALL_MSG2_BTN_R ENDSINGLECALL_MSG_BTN_R
#define	ENDSINGLECALL_MSG2_BTN_T REL_H(MSG_BTN_POS2_T_PAD)
#define	ENDSINGLECALL_MSG2_BTN_B REL_H(MSG_BTN_POS2_T_PAD+MSG_BTN_POS2_HEIGHT)

#define	ENDSINGLECALL_CONTACT_BTN_L REL_W(CONTACT_BTN_POS1_L_PAD)
#define	ENDSINGLECALL_CONTACT_BTN_R REL_W(CONTACT_BTN_POS1_L_PAD+CONTACT_BTN_POS1_WIDTH)
#define	ENDSINGLECALL_CONTACT_BTN_T REL_H(CONTACT_BTN_POS1_T_PAD)
#define	ENDSINGLECALL_CONTACT_BTN_B REL_H(CONTACT_BTN_POS1_T_PAD+CONTACT_BTN_POS1_HEIGHT)
/*
 * End of END CALL View
 */
#endif				/*__VCUI_VIEW_LAYOUT_HD__*/
