/*
 * Copyright 2012  Samsung Electronics Co., Ltd
 *
 * Licensed under the Flora License, Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.tizenopensource.org/license
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#ifndef __VCUI_VIEW_LAYOUT__
#define __VCUI_VIEW_LAYOUT__

#define COLOR_DEFAULT 0 0 0 255
#define COLOR_BG_ALPHA 0 0 0 0
#define COLOR_BG_FOR_HELD_CALL_DIM 0 0 0 150

/*#define BTN_EDGE_W 9*/

/*List of the screen and widget dimensions as per GUI*/
/*Portrait mode*/
#define MAIN_SCREEN_W 480
#define MAIN_SCREEN_H 800

#define REL_W(x) (x / MAIN_SCREEN_W)
#define REL_H(x) (x / MAIN_SCREEN_H)

/* Window layout with nothing (only indicator) */
/*
#define WL_INDI_H 52
#define MAIN_INDICATOR_W MAIN_SCREEN_W
#define MAIN_INDICATOR_H 748
#define REL_INDI_W(x) (x / MAIN_INDICATOR_W)
#define REL_INDI_H(x) (x / MAIN_INDICATOR_H)
*/

/* Window layout with titlebar */
/*
#define WL_TB_H 92
#define MAIN_TITLEBAR_W MAIN_SCREEN_W
#define MAIN_TITLEBAR_H 702
#define REL_TITLEBAR_W(x) (x / MAIN_TITLEBAR_W)
#define REL_TITLEBAR_H(x) (x / MAIN_TITLEBAR_H)
*/

/* Window layout with navibar */
/*#define WL_NB_H 94*/
#define MAIN_NAVIBAR_W MAIN_SCREEN_W
#define MAIN_NAVIBAR_H 706
#define REL_NAVIBAR_W(x) (x / MAIN_NAVIBAR_W)
#define REL_NAVIBAR_H(x) (x / MAIN_NAVIBAR_H)

/* Main View (MO/MT view) */
#define DIALLING_STATUS_L REL_W(12)
#define DIALLING_STATUS_R REL_W(468)
#define DIALLING_STATUS_T REL_H(428)
#define DIALLING_STATUS_B REL_H(460)

#define DIALLING_MT_STATUS_L REL_W(123)
#define DIALLING_MT_STATUS_R REL_W(357)
#define DIALLING_MT_STATUS_T REL_H(375)
#define DIALLING_MT_STATUS_B REL_H(407)

#define DIALLING_NAME_L REL_W(12)
#define DIALLING_NAME_R REL_W(468)
#define DIALLING_NAME_T REL_H(52)
#define DIALLING_NAME_B REL_H(102)

#define DIALLING_NUMBER_L DIALLING_NAME_L
#define DIALLING_NUMBER_R DIALLING_NAME_R
#define DIALLING_NUMBER_T REL_H(106)
#define DIALLING_NUMBER_B REL_H(138)

#define DIALLING_CID_L  REL_W(145)
#define DIALLING_CID_R  REL_W(335)
#define DIALLING_CID_T REL_H(145)
#define DIALLING_CID_B REL_H(335)

#define DIALLING_BACKGROUND_CID_L  REL_W(0)
#define DIALLING_BACKGROUND_CID_R  REL_W(MAIN_SCREEN_W)
#define DIALLING_BACKGROUND_CID_T REL_H(0)
#define DIALLING_BACKGROUND_CID_B REL_H(MAIN_SCREEN_H)

/* accept */
#define DIALLING_MT_BTN1_L REL_W(26)
#define DIALLING_MT_BTN1_R REL_W(228)
#define DIALLING_MT_BTN1_T REL_H(620)
#define DIALLING_MT_BTN1_B REL_H(690)

/* reject */
#define DIALLING_MT_BTN2_L  REL_W(252)
#define DIALLING_MT_BTN2_R  REL_W(454)
#define DIALLING_MT_BTN2_T  DIALLING_MT_BTN1_T
#define DIALLING_MT_BTN2_B  DIALLING_MT_BTN1_B
/* End of Main View (MO/MT view) */

/* MT LOCK View */
#define REL_LOCK_W(x) (x / 322)
#define REL_LOCK_H(x) (x / 124)

#define INCOMING_LOCK_ACCEPT_BG_L REL_W(-182)
#define INCOMING_LOCK_ACCEPT_BG_R REL_W(140)
#define INCOMING_LOCK_ACCEPT_BG_T REL_H(591)
#define INCOMING_LOCK_ACCEPT_BG_B REL_H(715)

#define INCOMING_LOCK_ACCEPT_ICON_L REL_LOCK_W(202)
#define INCOMING_LOCK_ACCEPT_ICON_R REL_LOCK_W(272)
#define INCOMING_LOCK_ACCEPT_ICON_T REL_LOCK_H(23)
#define INCOMING_LOCK_ACCEPT_ICON_B REL_LOCK_H(93)

#define INCOMING_LOCK_ACCEPT_TEXT_L REL_LOCK_W(30)
#define INCOMING_LOCK_ACCEPT_TEXT_R REL_LOCK_W(182)
#define INCOMING_LOCK_ACCEPT_TEXT_T INCOMING_LOCK_ACCEPT_ICON_T
#define INCOMING_LOCK_ACCEPT_TEXT_B INCOMING_LOCK_ACCEPT_ICON_B

#define INCOMING_LOCK_REJECT_BG_L REL_W(340)
#define INCOMING_LOCK_REJECT_BG_R REL_W(662)
#define INCOMING_LOCK_REJECT_BG_T INCOMING_LOCK_ACCEPT_BG_T
#define INCOMING_LOCK_REJECT_BG_B INCOMING_LOCK_ACCEPT_BG_B

#define INCOMING_LOCK_REJECT_ICON_L REL_LOCK_W(50)
#define INCOMING_LOCK_REJECT_ICON_R REL_LOCK_W(120)
#define INCOMING_LOCK_REJECT_ICON_T INCOMING_LOCK_ACCEPT_ICON_T
#define INCOMING_LOCK_REJECT_ICON_B INCOMING_LOCK_ACCEPT_ICON_B

#define INCOMING_LOCK_REJECT_TEXT_L REL_LOCK_W(130)
#define INCOMING_LOCK_REJECT_TEXT_R REL_LOCK_W(282)
#define INCOMING_LOCK_REJECT_TEXT_T INCOMING_LOCK_REJECT_ICON_T
#define INCOMING_LOCK_REJECT_TEXT_B INCOMING_LOCK_REJECT_ICON_B

#define REL_LOCK_MSG_W(x) (x / 232)
#define REL_LOCK_MSG_H(x) (x / 125)
/* End of MT LOCK View */

/* KEYPAD View */
#define INCALL_DIALER_TIMER_T REL_H(241)
#define INCALL_DIALER_TIMER_B REL_H(271)
#define INCALL_DIALER_TIMER_L REL_W(300)
#define INCALL_DIALER_TIMER_R REL_W(454)

#define INCALL_DIALER_NAME_T INCALL_DIALER_TIMER_T
#define INCALL_DIALER_NAME_B INCALL_DIALER_TIMER_B
#define INCALL_DIALER_NAME_L REL_W(27)
#define INCALL_DIALER_NAME_R REL_W(300)

/*
#define DIALLING_KEYPAD_T_BF REL_H(319)
#define DIALLING_KEYPAD_B_BF REL_H(710)
*/

#define DIALLING_KEYPAD_T REL_H(289)
#define DIALLING_KEYPAD_B REL_H(680)
#define DIALLING_KEYPAD_L REL_W(0)
#define DIALLING_KEYPAD_R REL_W(MAIN_SCREEN_W)
#define KEYPAD_W MAIN_SCREEN_W
#define KEYPAD_H 391

#define DIALLING_ENTRY_TEXT_T REL_H(46)
#define DIALLING_ENTRY_TEXT_B REL_H(186)
#define DIALLING_ENTRY_TEXT_L REL_W(26)
#define DIALLING_ENTRY_TEXT_R REL_W(454)
#define REL_KEYPAD_W(x) ((x)/KEYPAD_W)
#define REL_KEYPAD_H(y) ((y)/KEYPAD_H)

#define DIALER_BTN1_T REL_H(712)
#define DIALER_BTN1_B REL_H(782)
#define DIALER_BTN1_L REL_W(27)
#define DIALER_BTN1_R REL_W(229)

#define DIALER_BTN2_T DIALER_BTN1_T
#define DIALER_BTN2_B DIALER_BTN1_B
#define DIALER_BTN2_L REL_W(252)
#define DIALER_BTN2_R REL_W(454)
/* End of KEYPAD View */

/* INCALL View  : Use Windows Layout with nothing (only indicator) */
/*Portrait view - START*/
#define INCALL_CID_T DIALLING_CID_T
#define INCALL_CID_B DIALLING_CID_B
#define INCALL_CID_L DIALLING_CID_L
#define INCALL_CID_R DIALLING_CID_R

/*
#define INCALL_CID_DIM_T DIALLING_CID_T
#define INCALL_CID_DIM_B DIALLING_CID_B
#define INCALL_CID_DIM_L REL_W(145)
#define INCALL_CID_DIM_R REL_W(334)
*/

#define INCALL_BACKGROUND_CID_L  DIALLING_BACKGROUND_CID_L
#define INCALL_BACKGROUND_CID_R  DIALLING_BACKGROUND_CID_R
#define INCALL_BACKGROUND_CID_T DIALLING_BACKGROUND_CID_T
#define INCALL_BACKGROUND_CID_B DIALLING_BACKGROUND_CID_B

#define INCALL_NAME_T DIALLING_NAME_T
#define INCALL_NAME_B DIALLING_NAME_B
#define INCALL_NAME_L DIALLING_NAME_L
#define INCALL_NAME_R DIALLING_NAME_R

#define INCALL_NUMBER_T DIALLING_NUMBER_T
#define INCALL_NUMBER_B DIALLING_NUMBER_B
#define INCALL_NUMBER_L DIALLING_NUMBER_L
#define INCALL_NUMBER_R DIALLING_NUMBER_R

#define INCALL_HOLD_T REL_H(389)
#define INCALL_HOLD_B REL_H(443)
#define INCALL_HOLD_L REL_W(26)
#define INCALL_HOLD_R REL_W(99)

#define INCALL_TIMER_T REL_H(400)
#define INCALL_TIMER_B REL_H(432)
#define INCALL_TIMER_L REL_W(173)
#define INCALL_TIMER_R REL_W(454)

#define INCALL_BACKGROUND_SHARE_L	REL_W(0)
#define INCALL_BACKGROUND_SHARE_R	REL_W(MAIN_SCREEN_W)
#define INCALL_BACKGROUND_SHARE_T	REL_H(365)
#define INCALL_BACKGROUND_SHARE_B	REL_H(774)
/*Portrait view - END*/

/* MULTICALL_SPLIT View  : Use Windows Layout with no indicator */
/*portrait mode - START*/
/*L[ACT] + R[HLD]*/
#define MULTICALL_SPLIT_BACKGROUND_CID_L INCALL_BACKGROUND_CID_L
#define MULTICALL_SPLIT_BACKGROUND_CID_R INCALL_BACKGROUND_CID_R
#define MULTICALL_SPLIT_BACKGROUND_CID_T INCALL_BACKGROUND_CID_T
#define MULTICALL_SPLIT_BACKGROUND_CID_B INCALL_BACKGROUND_CID_B

#define MULTICALL_SPLIT_CID_1_T REL_H(136)
#define MULTICALL_SPLIT_CID_1_B REL_H(326)
#define MULTICALL_SPLIT_CID_1_L REL_W(50)
#define MULTICALL_SPLIT_CID_1_R REL_W(240)

#define MULTICALL_SPLIT_PAUSE_T REL_H(282)
#define MULTICALL_SPLIT_PAUSE_B REL_H(322)
#define MULTICALL_SPLIT_PAUSE_L REL_W(54)
#define MULTICALL_SPLIT_PAUSE_R REL_W(94)

#define MULTICALL_SPLIT_CID_2_T REL_H(169)
#define MULTICALL_SPLIT_CID_2_B REL_H(299)
#define MULTICALL_SPLIT_CID_2_L REL_W(305)
#define MULTICALL_SPLIT_CID_2_R REL_W(435)

#define MULTICALL_SPLIT_PLAY_T REL_H(266)
#define MULTICALL_SPLIT_PLAY_B REL_H(291)
#define MULTICALL_SPLIT_PLAY_L REL_W(313)
#define MULTICALL_SPLIT_PLAY_R REL_W(338)

#define MULTICALL_SPLIT_NAME_1_T REL_H(90)
#define MULTICALL_SPLIT_NAME_1_B REL_H(126)
#define MULTICALL_SPLIT_NAME_1_L REL_W(24)
#define MULTICALL_SPLIT_NAME_1_R REL_W(266)

#define MULTICALL_SPLIT_NAME_2_T REL_H(136)
#define MULTICALL_SPLIT_NAME_2_B REL_H(160)
#define MULTICALL_SPLIT_NAME_2_L REL_W(280)
#define MULTICALL_SPLIT_NAME_2_R REL_W(450)

/*
#define MULTICALL_SPLIT_ACTIVE_ICON_T REL_H(343)
#define MULTICALL_SPLIT_ACTIVE_ICON_B REL_H(371)
#define MULTICALL_SPLIT_ACTIVE_ICON_L REL_W(97)
#define MULTICALL_SPLIT_ACTIVE_ICON_R REL_W(118)
*/

#define MULTICALL_SPLIT_ACTIVE_TXT_T MULTICALL_SPLIT_ACTIVE_ICON_T
#define MULTICALL_SPLIT_ACTIVE_TXT_B MULTICALL_SPLIT_ACTIVE_ICON_B
#define MULTICALL_SPLIT_ACTIVE_TXT_L REL_W(120)
#define MULTICALL_SPLIT_ACTIVE_TXT_R MULTICALL_SPLIT_CID_1_R

#define MULTICALL_SPLIT_MORE_ICON_T REL_H(308)
#define MULTICALL_SPLIT_MORE_ICON_B REL_H(332)
#define MULTICALL_SPLIT_MORE_ICON_L REL_W(409)
#define MULTICALL_SPLIT_MORE_ICON_R REL_W(433)

/*
#define MULTICALL_SPLIT_ON_HOLD_ICON_T REL_H(308)
#define MULTICALL_SPLIT_ON_HOLD_ICON_B REL_H(332)
#define MULTICALL_SPLIT_ON_HOLD_ICON_L REL_W(320)
#define MULTICALL_SPLIT_ON_HOLD_ICON_R REL_W(341)
*/

#define MULTICALL_SPLIT_ON_HOLD_TXT_T REL_H(308)
#define MULTICALL_SPLIT_ON_HOLD_TXT_B REL_H(332)
#define MULTICALL_SPLIT_ON_HOLD_TXT_L REL_W(303)
#define MULTICALL_SPLIT_ON_HOLD_TXT_R REL_W(433)

#define MULTICALL_SPLIT_ON_HOLD_TXT_WITH_ICON_T REL_H(308)
#define MULTICALL_SPLIT_ON_HOLD_TXT_WITH_ICON_B REL_H(332)
#define MULTICALL_SPLIT_ON_HOLD_TXT_WITH_ICON_L REL_W(303)
#define MULTICALL_SPLIT_ON_HOLD_TXT_WITH_ICON_R REL_W(409)

#define MULTICALL_SPLIT_TIMER_T REL_H(343)
#define MULTICALL_SPLIT_TIMER_B REL_H(371)
#define MULTICALL_SPLIT_TIMER_L REL_W(56)
#define MULTICALL_SPLIT_TIMER_R REL_W(246)
/*L[ACT] + R[HLD]*/

/*L[HLD] + R[ACT]*/
#define MULTICALL_SPLIT_SWAP_CID_1_T MULTICALL_SPLIT_CID_2_T
#define MULTICALL_SPLIT_SWAP_CID_1_B MULTICALL_SPLIT_CID_2_B
#define MULTICALL_SPLIT_SWAP_CID_1_L REL_W(49)
#define MULTICALL_SPLIT_SWAP_CID_1_R REL_W(179)

#define MULTICALL_SPLIT_SWAP_PLAY_T MULTICALL_SPLIT_PLAY_T
#define MULTICALL_SPLIT_SWAP_PLAY_B MULTICALL_SPLIT_PLAY_B
#define MULTICALL_SPLIT_SWAP_PLAY_L REL_W(57)
#define MULTICALL_SPLIT_SWAP_PLAY_R REL_W(82)

#define MULTICALL_SPLIT_SWAP_CID_2_T MULTICALL_SPLIT_CID_1_T
#define MULTICALL_SPLIT_SWAP_CID_2_B MULTICALL_SPLIT_CID_1_B
#define MULTICALL_SPLIT_SWAP_CID_2_L REL_W(244)
#define MULTICALL_SPLIT_SWAP_CID_2_R REL_W(434)

#define MULTICALL_SPLIT_SWAP_PAUSE_T MULTICALL_SPLIT_PAUSE_T
#define MULTICALL_SPLIT_SWAP_PAUSE_B MULTICALL_SPLIT_PAUSE_B
#define MULTICALL_SPLIT_SWAP_PAUSE_L REL_W(248)
#define MULTICALL_SPLIT_SWAP_PAUSE_R REL_W(288)

#define MULTICALL_SPLIT_SWAP_NAME_1_T MULTICALL_SPLIT_NAME_2_T
#define MULTICALL_SPLIT_SWAP_NAME_1_B MULTICALL_SPLIT_NAME_2_B
#define MULTICALL_SPLIT_SWAP_NAME_1_L MULTICALL_SPLIT_NAME_1_L
#define MULTICALL_SPLIT_SWAP_NAME_1_R REL_W(194)

#define MULTICALL_SPLIT_SWAP_NAME_2_T MULTICALL_SPLIT_NAME_1_T
#define MULTICALL_SPLIT_SWAP_NAME_2_B MULTICALL_SPLIT_NAME_1_B
#define MULTICALL_SPLIT_SWAP_NAME_2_L REL_W(208)
#define MULTICALL_SPLIT_SWAP_NAME_2_R REL_W(450)

/*
#define MULTICALL_SPLIT_SWAP_ACTIVE_ICON_T MULTICALL_SPLIT_ACTIVE_ICON_T
#define MULTICALL_SPLIT_SWAP_ACTIVE_ICON_B MULTICALL_SPLIT_ACTIVE_ICON_B
#define MULTICALL_SPLIT_SWAP_ACTIVE_ICON_L REL_W(287)
#define MULTICALL_SPLIT_SWAP_ACTIVE_ICON_R REL_W(308)
*/

#define MULTICALL_SPLIT_SWAP_ACTIVE_TXT_T MULTICALL_SPLIT_ACTIVE_ICON_T
#define MULTICALL_SPLIT_SWAP_ACTIVE_TXT_B MULTICALL_SPLIT_ACTIVE_ICON_B
#define MULTICALL_SPLIT_SWAP_ACTIVE_TXT_L REL_W(310)
#define MULTICALL_SPLIT_SWAP_ACTIVE_TXT_R MULTICALL_SPLIT_SWAP_CID_2_R

/*
#define MULTICALL_SPLIT_SWAP_ON_HOLD_ICON_T MULTICALL_SPLIT_ON_HOLD_ICON_T
#define MULTICALL_SPLIT_SWAP_ON_HOLD_ICON_B MULTICALL_SPLIT_ON_HOLD_ICON_B
#define MULTICALL_SPLIT_SWAP_ON_HOLD_ICON_L REL_W(67)
#define MULTICALL_SPLIT_SWAP_ON_HOLD_ICON_R REL_W(88)
*/

#define MULTICALL_SPLIT_SWAP_ON_HOLD_TXT_T REL_H(308)
#define MULTICALL_SPLIT_SWAP_ON_HOLD_TXT_B REL_H(332)
#define MULTICALL_SPLIT_SWAP_ON_HOLD_TXT_L REL_W(50)
#define MULTICALL_SPLIT_SWAP_ON_HOLD_TXT_R REL_W(180)

#define MULTICALL_SPLIT_SWAP_MORE_ICON_T REL_H(343)
#define MULTICALL_SPLIT_SWAP_MORE_ICON_B REL_H(371)
#define MULTICALL_SPLIT_SWAP_MORE_ICON_L REL_W(412)
#define MULTICALL_SPLIT_SWAP_MORE_ICON_R REL_W(436)

#define MULTICALL_SPLIT_SWAP_TIMER_T REL_H(343)
#define MULTICALL_SPLIT_SWAP_TIMER_B REL_H(371)
#define MULTICALL_SPLIT_SWAP_TIMER_L REL_W(246)
#define MULTICALL_SPLIT_SWAP_TIMER_R REL_W(436)

#define MULTICALL_SPLIT_SWAP_TIMER_WITH_ICON_T REL_H(343)
#define MULTICALL_SPLIT_SWAP_TIMER_WITH_ICON_B REL_H(371)
#define MULTICALL_SPLIT_SWAP_TIMER_WITH_ICON_L REL_W(246)
#define MULTICALL_SPLIT_SWAP_TIMER_WITH_ICON_R REL_W(406)
/*L[HLD] + R[ACT]*/
/*portrait mode - END*/
/* End of MULTICALL_SPLIT View  : Use Windows Layout with no indicator */

/* MULTICALL_LIST View */
/*
#define MULTICALL_CID_T REL_TITLEBAR_H(8)
#define MULTICALL_CID_B REL_TITLEBAR_H(428)
#define MULTICALL_CID_L REL_TITLEBAR_W(15)
#define MULTICALL_CID_R REL_TITLEBAR_W(468)

#define MULTICALL_NAME_T REL_TITLEBAR_H(218)
#define MULTICALL_NAME_B REL_TITLEBAR_H(268)

#define MULTICALL_NUM_T REL_TITLEBAR_H(48)
#define MULTICALL_NUM_B REL_TITLEBAR_H(88)
*/

#define MULTICALL_LIST_T REL_H(120)
#define MULTICALL_LIST_B REL_H(475)
#define MULTICALL_LIST_L REL_W(0)
#define MULTICALL_LIST_R REL_W(MAIN_SCREEN_W)

#define MULTICALL_LIST_HOLD_T REL_H(609)
#define MULTICALL_LIST_HOLD_B REL_H(663)
#define MULTICALL_LIST_HOLD_L REL_W(381)
#define MULTICALL_LIST_HOLD_R REL_W(454)

#define MULTICALL_LIST_TIMER_T REL_H(620)
#define MULTICALL_LIST_TIMER_B REL_H(652)
#define MULTICALL_LIST_TIMER_L REL_W(0)
#define MULTICALL_LIST_TIMER_R REL_W(MAIN_SCREEN_W)

#define MULTICALL_LIST_BIG_END_T REL_H(704)
#define MULTICALL_LIST_BIG_END_B REL_H(774)
#define MULTICALL_LIST_BIG_END_L REL_W(26)
#define MULTICALL_LIST_BIG_END_R REL_W(454)
/* End of MULTICALL_LIST View */

/* Six button layout, Without Window Layout */
#define SIX_BTN_1_L REL_W(26)
#define SIX_BTN_1_R REL_W(160)
#define SIX_BTN_2_L REL_W(173)
#define SIX_BTN_2_R REL_W(307)
#define SIX_BTN_3_L REL_W(320)
#define SIX_BTN_3_R REL_W(454)

#define SIX_BTN_1_T REL_H(494)
#define SIX_BTN_1_B REL_H(582)
#define SIX_BTN_2_T REL_H(595)
#define SIX_BTN_2_B REL_H(683)

#define SIX_BTN_BIG_END_L REL_W(26)
#define SIX_BTN_BIG_END_R REL_W(454)
#define SIX_BTN_BIG_END_T REL_H(712)
#define SIX_BTN_BIG_END_B REL_H(782)

#define SIX_BTN_INCOMING_1_L SIX_BTN_BIG_END_L
#define SIX_BTN_INCOMING_1_R SIX_BTN_BIG_END_R
#define SIX_BTN_INCOMING_1_T REL_H(438)
#define SIX_BTN_INCOMING_1_B REL_H(508)

#define SIX_BTN_INCOMING_2_L SIX_BTN_BIG_END_L
#define SIX_BTN_INCOMING_2_R SIX_BTN_BIG_END_R
#define SIX_BTN_INCOMING_2_T REL_H(524)
#define SIX_BTN_INCOMING_2_B REL_H(594)

#define SIX_BTN_INCOMING_3_L SIX_BTN_BIG_END_L
#define SIX_BTN_INCOMING_3_R SIX_BTN_BIG_END_R
#define SIX_BTN_INCOMING_3_T REL_H(610)
#define SIX_BTN_INCOMING_3_B REL_H(680)
/* Six Button Layout End */

/* Six button layout, Window Layout : INDICATOR */
/*
#define INDI_SIX_BTN_1_L REL_INDI_W(26)
#define INDI_SIX_BTN_1_R REL_INDI_W(160)
#define INDI_SIX_BTN_2_L REL_INDI_W(173)
#define INDI_SIX_BTN_2_R REL_INDI_W(307)
#define INDI_SIX_BTN_3_L REL_INDI_W(320)
#define INDI_SIX_BTN_3_R REL_INDI_W(454)

#define INDI_SIX_BTN_1_T_BF REL_INDI_H(417)
#define INDI_SIX_BTN_1_B_BF REL_INDI_H(505)
#define INDI_SIX_BTN_2_T_BF REL_INDI_H(518)
#define INDI_SIX_BTN_2_B_BF REL_INDI_H(606)

#define INDI_SIX_BTN_1_T REL_INDI_H(467)
#define INDI_SIX_BTN_1_B REL_INDI_H(555)
#define INDI_SIX_BTN_2_T REL_INDI_H(568)
#define INDI_SIX_BTN_2_B REL_INDI_H(656)

#define INDI_SIX_BTN_BIG_END_L REL_INDI_W(26)
#define INDI_SIX_BTN_BIG_END_R REL_INDI_W(454)

#define INDI_SIX_BTN_BIG_END_T_BF REL_INDI_H(635)
#define INDI_SIX_BTN_BIG_END_B_BF REL_INDI_H(705)

#define INDI_SIX_BTN_BIG_END_T REL_INDI_H(685)
#define INDI_SIX_BTN_BIG_END_B REL_INDI_H(755)

#define INDI_SIX_BTN_INCOMING_1_L INDI_SIX_BTN_BIG_END_L
#define INDI_SIX_BTN_INCOMING_1_R INDI_SIX_BTN_BIG_END_R
#define INDI_SIX_BTN_INCOMING_1_T REL_INDI_H(411)
#define INDI_SIX_BTN_INCOMING_1_B REL_INDI_H(481)

#define INDI_SIX_BTN_INCOMING_2_L INDI_SIX_BTN_BIG_END_L
#define INDI_SIX_BTN_INCOMING_2_R INDI_SIX_BTN_BIG_END_R
#define INDI_SIX_BTN_INCOMING_2_T REL_INDI_H(497)
#define INDI_SIX_BTN_INCOMING_2_B REL_INDI_H(567)

#define INDI_SIX_BTN_INCOMING_3_L INDI_SIX_BTN_BIG_END_L
#define INDI_SIX_BTN_INCOMING_3_R INDI_SIX_BTN_BIG_END_R
#define INDI_SIX_BTN_INCOMING_3_T REL_INDI_H(583)
#define INDI_SIX_BTN_INCOMING_3_B REL_INDI_H(653)
*/
/* Six Button Layout End */

/* Six button layout, Window Layout : Titlebar */
/*
#define TITLEBAR_SIX_BTN_1_L REL_TITLEBAR_W(18)
#define TITLEBAR_SIX_BTN_1_R REL_TITLEBAR_W(160)
#define TITLEBAR_SIX_BTN_2_L REL_TITLEBAR_W(169)
#define TITLEBAR_SIX_BTN_2_R REL_TITLEBAR_W(311)
#define TITLEBAR_SIX_BTN_3_L REL_TITLEBAR_W(320)
#define TITLEBAR_SIX_BTN_3_R REL_TITLEBAR_W(462)

#define TITLEBAR_SIX_BTN_1_T REL_TITLEBAR_H(477)
#define TITLEBAR_SIX_BTN_1_B REL_TITLEBAR_H(569)
#define TITLEBAR_SIX_BTN_2_T REL_TITLEBAR_H(580)
#define TITLEBAR_SIX_BTN_2_B REL_TITLEBAR_H(672)

#define TITLEBAR_SIX_BTN_TXT_1_T REL_TITLEBAR_H(533)
#define TITLEBAR_SIX_BTN_TXT_1_B REL_TITLEBAR_H(562)
#define TITLEBAR_SIX_BTN_TXT_2_T REL_TITLEBAR_H(636)
#define TITLEBAR_SIX_BTN_TXT_2_B REL_TITLEBAR_H(665)

#define TITLEBAR_SIX_BTN_TXT_1_M1_T REL_TITLEBAR_H(580)
#define TITLEBAR_SIX_BTN_TXT_1_M1_B REL_TITLEBAR_H(625)
#define TITLEBAR_SIX_BTN_TXT_1_M2_T REL_TITLEBAR_H(627)
#define TITLEBAR_SIX_BTN_TXT_1_M2_B REL_TITLEBAR_H(672)

#define TITLEBAR_SIX_BTN_TXT_2_M1_T REL_TITLEBAR_H(477)
#define TITLEBAR_SIX_BTN_TXT_2_M1_B REL_TITLEBAR_H(569)
#define TITLEBAR_SIX_BTN_TXT_2_M2_T REL_TITLEBAR_H(580)
#define TITLEBAR_SIX_BTN_TXT_2_M2_B REL_TITLEBAR_H(672)
*/
/* Six Button Layout End */

/* Navigation bar layout */
#define CALL_NAVIGATION_BAR_T	REL_H(40)
#define CALL_NAVIGATION_BAR_B	REL_H(MAIN_SCREEN_H)
#define CALL_NAVIGATION_BAR_L	REL_W(0)
#define CALL_NAVIGATION_BAR_R	REL_W(MAIN_SCREEN_W)
/* Navigation bar layout */

/* End call layout */
#define	ENDSINGLECALL_BACKGROUND_CID_L		DIALLING_BACKGROUND_CID_L
#define	ENDSINGLECALL_BACKGROUND_CID_R		DIALLING_BACKGROUND_CID_R
#define	ENDSINGLECALL_BACKGROUND_CID_T		DIALLING_BACKGROUND_CID_T
#define	ENDSINGLECALL_BACKGROUND_CID_B		DIALLING_BACKGROUND_CID_B

#define ENDSINGLECALL_CID_L				REL_W(145)
#define ENDSINGLECALL_CID_R				REL_W(335)
#define ENDSINGLECALL_CID_T				REL_H(145)
#define ENDSINGLECALL_CID_B				REL_H(335)

#define ENDSINGLECALL_NAME_L				DIALLING_NAME_L
#define ENDSINGLECALL_NAME_R				DIALLING_NAME_R
#define ENDSINGLECALL_NAME_T				DIALLING_NAME_T
#define ENDSINGLECALL_NAME_B				DIALLING_NAME_B

#define ENDSINGLECALL_NUMBER_L		DIALLING_NUMBER_L
#define ENDSINGLECALL_NUMBER_R		DIALLING_NUMBER_R
#define ENDSINGLECALL_NUMBER_T		DIALLING_NUMBER_T
#define ENDSINGLECALL_NUMBER_B		DIALLING_NUMBER_B

#define ENDSINGLECALL_TIMER_L				REL_W(173)
#define ENDSINGLECALL_TIMER_R				REL_W(454)
#define ENDSINGLECALL_TIMER_T				REL_H(400)
#define ENDSINGLECALL_TIMER_B				REL_H(432)

#define	ENDSINGLECALL_VIDEO_BTN_L			REL_W(26)
#define	ENDSINGLECALL_VIDEO_BTN_R			REL_W(228)
#define	ENDSINGLECALL_VIDEO_BTN_T			REL_H(534)
#define	ENDSINGLECALL_VIDEO_BTN_B			REL_H(604)

#define	ENDSINGLECALL_VIDEO2_BTN_L			REL_W(26)
#define	ENDSINGLECALL_VIDEO2_BTN_R			REL_W(228)
#define	ENDSINGLECALL_VIDEO2_BTN_T			REL_H(620)
#define	ENDSINGLECALL_VIDEO2_BTN_B			REL_H(690)

#define	ENDSINGLECALL_VOICE_BTN_L			REL_W(252)
#define	ENDSINGLECALL_VOICE_BTN_R			REL_W(454)
#define	ENDSINGLECALL_VOICE_BTN_T			ENDSINGLECALL_VIDEO_BTN_T
#define	ENDSINGLECALL_VOICE_BTN_B			ENDSINGLECALL_VIDEO_BTN_B

#define	ENDSINGLECALL_VOICE2_BTN_L			REL_W(252)
#define	ENDSINGLECALL_VOICE2_BTN_R			REL_W(454)
#define	ENDSINGLECALL_VOICE2_BTN_T			ENDSINGLECALL_VIDEO2_BTN_T
#define	ENDSINGLECALL_VOICE2_BTN_B			ENDSINGLECALL_VIDEO2_BTN_B

#define	ENDSINGLECALL_MSG_BTN_L				REL_W(26)
#define	ENDSINGLECALL_MSG_BTN_R				REL_W(454)
#define	ENDSINGLECALL_MSG_BTN_T				REL_H(620)
#define	ENDSINGLECALL_MSG_BTN_B				REL_H(690)

#define	ENDSINGLECALL_MSG2_BTN_L			REL_W(26)
#define	ENDSINGLECALL_MSG2_BTN_R			REL_W(454)
#define	ENDSINGLECALL_MSG2_BTN_T			REL_H(706)
#define	ENDSINGLECALL_MSG2_BTN_B			REL_H(776)

#define	ENDSINGLECALL_CONTACT_BTN_L			REL_W(26)
#define	ENDSINGLECALL_CONTACT_BTN_R			REL_W(454)
#define	ENDSINGLECALL_CONTACT_BTN_T			REL_H(706)
#define	ENDSINGLECALL_CONTACT_BTN_B			REL_H(776)
/* End call layout */
 #endif				/*__VCUI_VIEW_LAYOUT__*/
